using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using Newtonsoft.Json;
using UnityEngine;

[Serializable]
public sealed class NativeSynapticSlot
{
    public string name;
    [JsonIgnore] public float[] importance,reference,path,start,gradient;

    public NativeSynapticSlot Clone()=>new NativeSynapticSlot{name=name,importance=Copy(importance),reference=Copy(reference),path=Copy(path),start=Copy(start),gradient=Copy(gradient)};
    private static float[] Copy(float[] value)=>value==null?null:(float[])value.Clone();
}

[Serializable]
public sealed class NativeSynapticIntelligence
{
    public const int WarmupUpdates=256,ConsolidationInterval=128;
    public const float Strength=.2f,ImportanceCap=10f,Epsilon=1e-3f;
    [JsonIgnore] public List<NativeSynapticSlot> slots=new List<NativeSynapticSlot>();

    public NativeSynapticIntelligence Clone(){var copy=new NativeSynapticIntelligence();foreach(var slot in slots??new List<NativeSynapticSlot>())copy.slots.Add(slot.Clone());return copy;}
    public NativeSynapticSlot Get(string name,int length,float[] parameter)
    {
        if(slots==null)slots=new List<NativeSynapticSlot>();NativeSynapticSlot slot=slots.FirstOrDefault(s=>s.name==name);
        if(slot==null){slot=new NativeSynapticSlot{name=name};slots.Add(slot);}if(slot.importance==null||slot.importance.Length!=length){slot.importance=new float[length];slot.reference=(float[])parameter.Clone();slot.path=new float[length];slot.start=(float[])parameter.Clone();slot.gradient=new float[length];}return slot;
    }
    public void AddPenalty(IReadOnlyList<KeyValuePair<string,float[]>> parameters,Dictionary<string,float[]> gradients)
    {foreach(var parameter in parameters){NativeSynapticSlot slot=Get(parameter.Key,parameter.Value.Length,parameter.Value);float[] g=gradients[parameter.Key];for(int i=0;i<g.Length;i++)g[i]+=2f*Strength*slot.importance[i]*(parameter.Value[i]-slot.reference[i]);}}
    public void BeginStep(IReadOnlyList<KeyValuePair<string,float[]>> parameters,Dictionary<string,float[]> gradients)
    {foreach(var parameter in parameters){NativeSynapticSlot slot=Get(parameter.Key,parameter.Value.Length,parameter.Value);Array.Copy(parameter.Value,slot.start,parameter.Value.Length);Array.Copy(gradients[parameter.Key],slot.gradient,parameter.Value.Length);}}
    public void EndStep(IReadOnlyList<KeyValuePair<string,float[]>> parameters,int optimizerStep)
    {
        foreach(var parameter in parameters){NativeSynapticSlot slot=Get(parameter.Key,parameter.Value.Length,parameter.Value);for(int i=0;i<parameter.Value.Length;i++)slot.path[i]+=-slot.gradient[i]*(parameter.Value[i]-slot.start[i]);}
        if(optimizerStep<WarmupUpdates||optimizerStep%ConsolidationInterval!=0)return;
        foreach(var parameter in parameters){NativeSynapticSlot slot=Get(parameter.Key,parameter.Value.Length,parameter.Value);float[] contribution=new float[parameter.Value.Length];float maximum=0f;for(int i=0;i<parameter.Value.Length;i++){float delta=parameter.Value[i]-slot.reference[i];contribution[i]=Math.Max(0f,slot.path[i])/(delta*delta+Epsilon);maximum=Math.Max(maximum,contribution[i]);}float scale=maximum>ImportanceCap?ImportanceCap/maximum:1f;for(int i=0;i<parameter.Value.Length;i++)slot.importance[i]=Math.Min(ImportanceCap,slot.importance[i]+contribution[i]*scale);Array.Copy(parameter.Value,slot.reference,parameter.Value.Length);Array.Clear(slot.path,0,slot.path.Length);}
    }
    public bool IsFinite()=>slots==null||slots.All(s=>Finite(s.importance)&&Finite(s.reference)&&Finite(s.path));
    private static bool Finite(float[] values)=>values!=null&&values.All(NativeCreatureModel.IsFinite);
}

[Serializable]
public sealed class NativeReplayBuffer
{
    public const int Capacity=12288,UsefulCapacity=3072;
    public readonly int capacity;
    public long seen;
    public NativeDeterministicRng random=new NativeDeterministicRng(0xC01DF00DUL);
    [JsonIgnore] public List<NativeCompletedSequence> samples=new List<NativeCompletedSequence>();
    [JsonIgnore] private Dictionary<string,List<int>> compatible=new Dictionary<string,List<int>>(StringComparer.Ordinal);
    public int Count=>samples?.Count??0;
    public NativeReplayBuffer(int maxCapacity=Capacity){capacity=Math.Max(1,Math.Min(Capacity,maxCapacity));}

    public void Offer(NativeCompletedSequence sample)
    {
        if(sample?.observation==null)return;seen++;NativeCompletedSequence copy=sample.Clone();if(samples.Count<capacity){samples.Add(copy);Index(samples.Count-1,copy.bodySignature);return;}long candidate=NextLongBelow(seen);if(candidate<capacity){int slot=(int)candidate;Unindex(slot,samples[slot]?.bodySignature);samples[slot]=copy;Index(slot,copy.bodySignature);}
    }
    public List<NativeCompletedSequence> Sample(int count,string bodySignature=null)
    {
        EnsureIndex();List<int> eligible=bodySignature==null?null:(compatible.TryGetValue(bodySignature,out var indexed)?indexed:null);int available=eligible==null?(bodySignature==null?samples.Count:0):eligible.Count;var result=new List<NativeCompletedSequence>(Math.Min(count,available));var selected=new HashSet<int>();while(result.Count<count&&selected.Count<available){int slot=eligible==null?random.NextInt(samples.Count):eligible[random.NextInt(eligible.Count)];if(selected.Add(slot))result.Add(samples[slot]);}return result;
    }
    public NativeReplayBuffer Clone(){var copy=new NativeReplayBuffer(capacity){seen=seen,random=new NativeDeterministicRng(random.State)};foreach(var sample in samples??new List<NativeCompletedSequence>()){copy.samples.Add(sample.Clone());copy.Index(copy.samples.Count-1,sample.bodySignature);}return copy;}
    public void RebuildIndex(){compatible=new Dictionary<string,List<int>>(StringComparer.Ordinal);for(int i=0;i<samples.Count;i++)Index(i,samples[i]?.bodySignature);}
    private void EnsureIndex(){if(compatible==null||compatible.Count==0&&samples.Count>0)RebuildIndex();}
    private void Index(int slot,string signature){signature=signature??string.Empty;if(!compatible.TryGetValue(signature,out var list))compatible[signature]=list=new List<int>();list.Add(slot);}
    private void Unindex(int slot,string signature){signature=signature??string.Empty;if(!compatible.TryGetValue(signature,out var list))return;list.Remove(slot);if(list.Count==0)compatible.Remove(signature);}
    private long NextLongBelow(long exclusiveMax)=>random.NextLong(exclusiveMax);
    public static NativeObservation CloneObservation(NativeObservation value)
    {
        if(value==null)return null;return new NativeObservation{torsoWithGoal=Copy(value.torsoWithGoal),torsoWithoutGoal=Copy(value.torsoWithoutGoal),jointFeatures=Copy(value.jointFeatures),positionEncodings=Copy(value.positionEncodings),limbMask=Copy(value.limbMask),parentSlots=value.parentSlots==null?null:(int[])value.parentSlots.Clone(),limbCount=value.limbCount,tick=value.tick,episode=value.episode,controllerId=value.controllerId,bodySignature=value.bodySignature,practice=value.practice,goalX=value.goalX,goalY=value.goalY,goalHeadingSin=value.goalHeadingSin,goalHeadingCos=value.goalHeadingCos,worldGoalX=value.worldGoalX,worldGoalY=value.worldGoalY,worldGoalHeadingSin=value.worldGoalHeadingSin,worldGoalHeadingCos=value.worldGoalHeadingCos,startWorldX=value.startWorldX,startWorldY=value.startWorldY,startWorldRotationDegrees=value.startWorldRotationDegrees};
    }
    private static float[] Copy(float[] values)=>values==null?null:(float[])values.Clone();
}

public sealed class NativeTrainingResult
{
    public string controllerId,error;public NativeM2BatchMetrics m2;public NativeM3BatchMetrics m3;public NativeM3Evaluation evaluation;public long milliseconds;
}

[Serializable]
public sealed class NativeM3Evaluation { public int sampleCount,modelUpdates;public float torsoPositionRmse,orientationDegrees,endpointRmse,contactBrier,actionSensitivity; }

[Serializable]
public sealed class NativeM3LearningState
{
    public NativeDynamicsWeights dynamics;public NativeOptimizerState optimizer=new NativeOptimizerState();public NativeSynapticIntelligence protection=new NativeSynapticIntelligence();[JsonIgnore] public NativeReplayBuffer replay=new NativeReplayBuffer();[JsonIgnore] public NativeReplayBuffer usefulReplay=new NativeReplayBuffer(NativeReplayBuffer.UsefulCapacity);[JsonIgnore] public List<NativeCompletedSequence> validation=new List<NativeCompletedSequence>();public int freshSequences,optimizerSteps,lastResultTick;
    public NativeM3LearningState Clone(){return new NativeM3LearningState{dynamics=dynamics?.Clone(),optimizer=optimizer?.Clone()??new NativeOptimizerState(),protection=protection?.Clone()??new NativeSynapticIntelligence(),replay=replay?.Clone()??new NativeReplayBuffer(),usefulReplay=usefulReplay?.Clone()??new NativeReplayBuffer(NativeReplayBuffer.UsefulCapacity),validation=(validation??new List<NativeCompletedSequence>()).Select(s=>s.Clone()).ToList(),freshSequences=freshSequences,optimizerSteps=optimizerSteps,lastResultTick=lastResultTick};}
}

[Serializable]
public sealed class NativeSharedLearningState
{
    public NativeBrainWeights m2;public NativeOptimizerState m2Optimizer=new NativeOptimizerState();public NativeSynapticIntelligence m2Protection=new NativeSynapticIntelligence();public NativeM3LearningState m3=new NativeM3LearningState();public int modelVersion;
    public NativeSharedLearningState Clone()=>new NativeSharedLearningState{m2=m2?.Clone(),m2Optimizer=m2Optimizer?.Clone()??new NativeOptimizerState(),m2Protection=m2Protection?.Clone()??new NativeSynapticIntelligence(),m3=m3?.Clone()??new NativeM3LearningState(),modelVersion=modelVersion};
}

public sealed class NativeContinualLearner:IDisposable
{
    private const int MaximumQueuedSequences=64; public const int M3WarmupFreshSequences=0;
    private readonly ConcurrentQueue<NativeCompletedSequence> queue=new ConcurrentQueue<NativeCompletedSequence>();
    private readonly ConcurrentQueue<NativeTrainingResult> results=new ConcurrentQueue<NativeTrainingResult>();
    private readonly AutoResetEvent signal=new AutoResetEvent(false);private readonly Thread worker;private volatile bool stopping;private int queued;
    private readonly object stateLock=new object();private readonly Dictionary<string,NativeM3LearningState> states;
    private readonly Func<string,NativeCreatureModel> resolveModel;
    private readonly NativeCreatureModel sharedM2Model;private NativeSharedLearningState shared;
    public int QueueDepth=>Volatile.Read(ref queued);public int Dropped{get;private set;}public bool Busy{get;private set;}
    public int ReplayCount{get{lock(stateLock)return shared?.m3?.replay?.Count??0;}}
    public int UsefulReplayCount{get{lock(stateLock)return shared?.m3?.usefulReplay?.Count??0;}}

    public NativeContinualLearner(NativeBrainWeights sharedM2Seed,NativeDynamicsWeights sharedM3Seed,Func<string,NativeCreatureModel> resolver)
    {states=new Dictionary<string,NativeM3LearningState>(StringComparer.Ordinal);shared=new NativeSharedLearningState{m2=(sharedM2Seed??NativeBrainWeights.Create(7331)).Clone(),m3=new NativeM3LearningState{dynamics=(sharedM3Seed??NativeDynamicsWeights.Create(7332)).Clone()}};sharedM2Model=new NativeCreatureModel(shared.m2,7331);resolveModel=resolver;worker=new Thread(Run){IsBackground=true,Name="Native continual learner"};worker.Start();}
    public bool Enqueue(NativeCompletedSequence sample){if(sample==null)return false;if(Interlocked.Increment(ref queued)>MaximumQueuedSequences){Interlocked.Decrement(ref queued);Dropped++;return false;}queue.Enqueue(sample.Clone());signal.Set();return true;}
    public void RecordEvaluation(NativeCompletedSequence sample){if(sample==null)return;lock(stateLock){shared.m3.validation.Add(sample.Clone());if(shared.m3.validation.Count>128)shared.m3.validation.RemoveAt(0);}}
    public bool TryResult(out NativeTrainingResult result)=>results.TryDequeue(out result);
    public NativeDynamicsWeights Snapshot(string controllerId){lock(stateLock)return shared.m3.dynamics.Clone();}
    public NativeBrainWeights SnapshotM2(){lock(stateLock)return shared.m2.Clone();}
    public NativeM3LearningState Capture(string controllerId){lock(stateLock)return shared.m3.Clone();}
    public NativeSharedLearningState CaptureShared(){lock(stateLock)return shared.Clone();}
    public void RestoreShared(NativeSharedLearningState value){if(value==null||value.m2==null||value.m3?.dynamics==null)return;lock(stateLock){shared=value.Clone();sharedM2Model.RepairFrom(shared.m2);}}
    public Dictionary<string,NativeM3LearningState> CaptureAll(){lock(stateLock)return new Dictionary<string,NativeM3LearningState>{{"shared",shared.m3.Clone()}};}
    public void SetState(string controllerId,NativeM3LearningState state){}
    public void RemoveState(string controllerId){}
    private void Run()
    {
        while(!stopping){if(!queue.TryDequeue(out NativeCompletedSequence fresh)){signal.WaitOne(50);continue;}Interlocked.Decrement(ref queued);Busy=true;long started=System.Diagnostics.Stopwatch.GetTimestamp();var result=new NativeTrainingResult{controllerId=fresh.controllerId};try{
            NativeDynamicsWeights m3Snapshot;List<NativeCompletedSequence> m3Batch,m2Replay;NativeOptimizerState optimizer;NativeSynapticIntelligence protection;lock(stateLock){NativeM3LearningState state=shared.m3;m3Batch=new List<NativeCompletedSequence>{fresh};m3Batch.AddRange(state.replay.Sample(7));m2Replay=state.usefulReplay.Sample(2);m2Replay.AddRange(state.replay.Sample(Math.Max(0,7-m2Replay.Count)));state.replay.Offer(fresh);if(IsUsefulMovement(fresh))state.usefulReplay.Offer(fresh);m3Snapshot=state.dynamics.Clone();optimizer=state.optimizer.Clone();protection=state.protection.Clone();}result.m3=NativeCreatureModel.TrainSharedM3Batch(m3Batch,m3Snapshot,optimizer,protection);if(!m3Snapshot.IsFinite()||!protection.IsFinite())throw new InvalidOperationException("M3 update produced invalid state");
            {var observations=new List<NativeObservation>{fresh.observation};observations.AddRange(m2Replay.Select(s=>s.observation));result.m2=sharedM2Model.TrainM2Batch(observations,m3Snapshot,fresh.observation.tick);}
            lock(stateLock){shared.m3.dynamics=m3Snapshot;shared.m3.optimizer=optimizer;shared.m3.protection=protection;shared.m3.freshSequences++;shared.m3.optimizerSteps=result.m3.optimizerSteps;shared.m2=sharedM2Model.Weights.Clone();shared.m2Optimizer=sharedM2Model.M2Optimizer.Clone();shared.m2Protection=sharedM2Model.M2Protection.Clone();shared.modelVersion++;if(shared.m3.optimizerSteps%128==0)result.evaluation=NativeCreatureModel.EvaluateM3(shared.m3.validation,m3Snapshot,shared.m3.optimizerSteps);}
        }catch(Exception e){result.error=e.ToString();}finally{result.milliseconds=(long)((System.Diagnostics.Stopwatch.GetTimestamp()-started)*1000d/System.Diagnostics.Stopwatch.Frequency);results.Enqueue(result);Busy=false;}}
    }
    public void Dispose(){stopping=true;signal.Set();if(worker.IsAlive)worker.Join(2000);signal.Dispose();}
    private static bool IsUsefulMovement(NativeCompletedSequence sample){if(sample?.observation==null||sample.actualPoses==null||sample.actualAuxiliary==null)return false;int last=(NativeCreatureModel.PlanningHorizon-1)*NativeCreatureModel.PoseValueCount;Vector2 end=new Vector2(sample.actualPoses[last],sample.actualPoses[last+1]);float improvement=sample.observation.goal.magnitude-(sample.observation.goal-end).magnitude;int aux=(NativeCreatureModel.PlanningHorizon-1)*NativeCreatureModel.AuxiliaryValueCount+NativeCreatureModel.MaxLimbs*NativeCreatureModel.EndpointValueCount;bool contact=false;for(int limb=0;limb<sample.observation.limbCount;limb++)contact|=sample.actualAuxiliary[aux+limb*NativeCreatureModel.ContactValueCount]>.5f;return improvement>=.05f&&contact;}
}

// v26 movement school.  This is intentionally a plain-C# learner: Unity owns
// physics and observations, while this class owns the only published M2/M3
// snapshot.  Rollouts always use an immutable clone of that snapshot.
[Serializable]
public sealed class NativeMovementWeights
{
    public const int Width=64,HistoryLength=4,NodeInput=HistoryLength*NativeCreatureModel.JointFeatureSize+NativeCreatureModel.PositionEncodingSize+4,GlobalInput=25,PolicyLimbOutputs=4,TargetSize=66,M3Input=Width+NativeCreatureModel.MaxLimbs+3;
    [JsonIgnore] public float[] nodeInput,nodeBias,messageSelf,messageParent,messageChild,messageBias,frequency,limbPolicy,value,m3Head0,m3Head1,m3Head2,m3Bias0,m3Bias1,m3Bias2,inverse,logStd;
    public static NativeMovementWeights Create(int seed)
    {
        var r=new System.Random(seed);int w=Width,t=TargetSize,m3in=M3Input;
        return new NativeMovementWeights{nodeInput=Xavier(r,NodeInput,w),nodeBias=new float[w],messageSelf=Xavier(r,w,w),messageParent=Xavier(r,w,w),messageChild=Xavier(r,w,w),messageBias=new float[w],frequency=Xavier(r,w+GlobalInput,1),limbPolicy=Xavier(r,w+GlobalInput,PolicyLimbOutputs),value=Xavier(r,w+GlobalInput,1),m3Head0=Xavier(r,m3in,t),m3Head1=Xavier(r,m3in,t),m3Head2=Xavier(r,m3in,t),m3Bias0=new float[t],m3Bias1=new float[t],m3Bias2=new float[t],inverse=Xavier(r,m3in,1),logStd=Enumerable.Repeat(-.7f,1+NativeCreatureModel.MaxLimbs*PolicyLimbOutputs).ToArray()};
    }
    public NativeMovementWeights Clone(){var c=new NativeMovementWeights();foreach(var f in typeof(NativeMovementWeights).GetFields().Where(f=>f.FieldType==typeof(float[]))){float[] a=(float[])f.GetValue(this);f.SetValue(c,a==null?null:(float[])a.Clone());}return c;}
    public IEnumerable<KeyValuePair<string,float[]>> Parameters(){foreach(var f in typeof(NativeMovementWeights).GetFields().Where(f=>f.FieldType==typeof(float[])))yield return new KeyValuePair<string,float[]>(f.Name,(float[])f.GetValue(this));}
    public bool IsFinite()=>Parameters().All(p=>p.Value!=null&&p.Value.All(NativeCreatureModel.IsFinite));
    private static float[] Xavier(System.Random r,int input,int output){float[] a=new float[input*output];double s=Math.Sqrt(6d/(input+output));for(int i=0;i<a.Length;i++)a[i]=(float)((r.NextDouble()*2d-1d)*s);return a;}
}

[Serializable]
public sealed class NativeMovementObservation
{
    public NativeObservation[] history=new NativeObservation[NativeMovementWeights.HistoryLength];
    public float oscillatorSin,oscillatorCos,angularVelocity,rhythmTicksRemaining;
    public float[] heldRhythm=new float[1+NativeCreatureModel.MaxLimbs*3];
    public int limbCount,episode,tick;public string controllerId,bodySignature;
    public Vector2 command,gravityLocal;
    public NativeMovementObservation Clone()=>new NativeMovementObservation{history=(history??Array.Empty<NativeObservation>()).Select(NativeReplayBuffer.CloneObservation).ToArray(),oscillatorSin=oscillatorSin,oscillatorCos=oscillatorCos,angularVelocity=angularVelocity,rhythmTicksRemaining=rhythmTicksRemaining,heldRhythm=heldRhythm==null?null:(float[])heldRhythm.Clone(),limbCount=limbCount,episode=episode,tick=tick,controllerId=controllerId,bodySignature=bodySignature,command=command,gravityLocal=gravityLocal};
}

[Serializable]
public sealed class NativePolicyDecision
{
    public float[] mean,sample,requested,executed,heldRhythm;public float oldLogProbability,value,frequency,phase,curiosity;public bool sampledRhythm;public int modelVersion;
    public NativePolicyDecision Clone()=>new NativePolicyDecision{mean=Copy(mean),sample=Copy(sample),requested=Copy(requested),executed=Copy(executed),heldRhythm=Copy(heldRhythm),oldLogProbability=oldLogProbability,value=value,frequency=frequency,phase=phase,curiosity=curiosity,sampledRhythm=sampledRhythm,modelVersion=modelVersion};
    private static float[] Copy(float[] x)=>x==null?null:(float[])x.Clone();
}

[Serializable]
public sealed class NativeMovementTransition
{
    public string sampleId,controllerId,bodySignature;public NativeMovementObservation observation,nextObservation;public NativePolicyDecision decision;public float[] measuredJointMovement=new float[NativeCreatureModel.MaxLimbs];public float reward,travelReward,effortPenalty,curiosityReward,torsoDeltaX,torsoDeltaY,headingDelta,angularVelocityDelta;public bool terminal,contactTransition,evaluation;public int episode,horizonSteps=1;
    public NativeMovementTransition Clone()=>new NativeMovementTransition{sampleId=sampleId,controllerId=controllerId,bodySignature=bodySignature,observation=observation?.Clone(),nextObservation=nextObservation?.Clone(),decision=decision?.Clone(),measuredJointMovement=(float[])(measuredJointMovement?.Clone()??new float[NativeCreatureModel.MaxLimbs]),reward=reward,travelReward=travelReward,effortPenalty=effortPenalty,curiosityReward=curiosityReward,torsoDeltaX=torsoDeltaX,torsoDeltaY=torsoDeltaY,headingDelta=headingDelta,angularVelocityDelta=angularVelocityDelta,terminal=terminal,contactTransition=contactTransition,evaluation=evaluation,episode=episode,horizonSteps=horizonSteps};
}

[Serializable]
public sealed class NativeMovementLearningState
{
    [JsonIgnore] public NativeMovementWeights weights,qualifiedWeights;[JsonIgnore] public NativeOptimizerState optimizer=new NativeOptimizerState(),qualifiedOptimizer;public int modelVersion,policyUpdates,m3Updates,freshTransitions;public ulong randomState=26001;public bool curiosityReady,simpleBodyQualified;[JsonIgnore] public List<NativeMovementTransition> recent=new List<NativeMovementTransition>(),progress=new List<NativeMovementTransition>(),contact=new List<NativeMovementTransition>(),imitation=new List<NativeMovementTransition>(),validation=new List<NativeMovementTransition>();
    public NativeMovementLearningState Clone(bool includeReplay=true)=>new NativeMovementLearningState{weights=weights?.Clone(),optimizer=CloneOptimizer(optimizer,weights),qualifiedWeights=qualifiedWeights?.Clone(),qualifiedOptimizer=CloneOptimizer(qualifiedOptimizer,qualifiedWeights),modelVersion=modelVersion,policyUpdates=policyUpdates,m3Updates=m3Updates,freshTransitions=freshTransitions,randomState=randomState,curiosityReady=curiosityReady,simpleBodyQualified=simpleBodyQualified,recent=includeReplay?recent.Select(x=>x.Clone()).ToList():new List<NativeMovementTransition>(),progress=includeReplay?progress.Select(x=>x.Clone()).ToList():new List<NativeMovementTransition>(),contact=includeReplay?contact.Select(x=>x.Clone()).ToList():new List<NativeMovementTransition>(),imitation=includeReplay?imitation.Select(x=>x.Clone()).ToList():new List<NativeMovementTransition>(),validation=includeReplay?validation.Select(x=>x.Clone()).ToList():new List<NativeMovementTransition>()};
    internal static NativeOptimizerState CloneOptimizer(NativeOptimizerState source,NativeMovementWeights weights){var o=new NativeOptimizerState{step=source?.step??0};if(source==null||weights==null)return o;foreach(var p in weights.Parameters()){NativeOptimizerSlot a=source.Get(p.Key,p.Value.Length),b=o.Get(p.Key,p.Value.Length);Array.Copy(a.first,b.first,a.first.Length);Array.Copy(a.second,b.second,a.second.Length);}return o;}
}

public sealed class NativeMovementMetrics
{
    public int policyUpdates,m3Updates,batchSize;public bool evaluation;public float policyLoss,valueLoss,entropy,approximateKl,m3Loss,inverseAccuracy,curiosity,noChangeLoss,constantVelocityLoss,actionBlindLoss,movingLoss,stationaryLoss,contactLoss;
}

internal sealed class NativeGraphCache
{
    public NativeMovementObservation observation;public float[][] input;public float[][][] state;public float[] global,pooled,policyContext;public int[] parent;
}

public sealed class NativeMovementLearner:IDisposable
{
    public const int RolloutSize=1024,MiniBatchSize=128,PpoEpochs=4,FastActionTicks=5,RhythmActionTicks=25;
    public const float LearningRate=.0003f,Gamma=.99f,GaeLambda=.95f,PpoClip=.2f,MaxKl=.02f,CuriosityCap=.02f,ImitationCoefficient=.05f;
    private const int ReplayCapacity=4096,SpecialReplayCapacity=1024,ValidationCapacity=256;
    private readonly object stateLock=new object();private readonly ConcurrentQueue<NativeMovementTransition> queue=new ConcurrentQueue<NativeMovementTransition>(),rollout=new ConcurrentQueue<NativeMovementTransition>();private readonly ConcurrentQueue<NativeMovementMetrics> results=new ConcurrentQueue<NativeMovementMetrics>();private readonly Dictionary<string,List<NativeMovementTransition>> horizonWindows=new Dictionary<string,List<NativeMovementTransition>>(StringComparer.Ordinal);private readonly AutoResetEvent signal=new AutoResetEvent(false);private readonly Thread worker;private readonly bool trainM3,allowCuriosity;private volatile bool stopping;private NativeMovementLearningState state;private NativeMovementWeights published;private NativeOptimizerState publishedOptimizer;private NativeDeterministicRng rng=new NativeDeterministicRng(26001);private int queued;
    public int QueueDepth=>Volatile.Read(ref queued);public int Dropped{get;private set;}public bool Busy{get;private set;}public int ReplayCount{get{lock(stateLock)return state.recent.Count;}}public int ProgressReplayCount{get{lock(stateLock)return state.progress.Count;}}public int ContactReplayCount{get{lock(stateLock)return state.contact.Count;}}public bool CuriosityReady{get{lock(stateLock)return allowCuriosity&&state.curiosityReady&&!state.simpleBodyQualified;}}public float ExplorationSigma{get{lock(stateLock)return Mathf.Exp(Mathf.Clamp(state.weights.logStd.Last(),-2.3f,.4f));}}
    public NativeMovementLearner(NativeMovementLearningState restored=null,int seed=26001,bool trainM3=true,bool allowCuriosity=true){this.trainM3=trainM3;this.allowCuriosity=allowCuriosity;state=restored?.Clone()??new NativeMovementLearningState{weights=NativeMovementWeights.Create(seed),randomState=(ulong)Math.Max(1,seed)};rng=new NativeDeterministicRng(state.randomState==0?(ulong)Math.Max(1,seed):state.randomState);published=state.weights.Clone();publishedOptimizer=NativeMovementLearningState.CloneOptimizer(state.optimizer,state.weights);worker=new Thread(Run){IsBackground=true,Name="Native v26 movement learner"};worker.Start();}
    public NativeMovementLearningState Capture(){lock(stateLock){state.randomState=rng.State;return state.Clone();}}
    public void Restore(NativeMovementLearningState restored){if(restored?.weights==null)return;lock(stateLock){state=restored.Clone();rng=new NativeDeterministicRng(state.randomState==0?26001UL:state.randomState);published=state.weights.Clone();publishedOptimizer=NativeMovementLearningState.CloneOptimizer(state.optimizer,state.weights);}}
    public void MarkSimpleBodyQualified(){lock(stateLock){state.simpleBodyQualified=true;state.curiosityReady=false;SaveQualifiedLocked(published);}}
    public void SaveQualifiedSnapshot(NativeMovementWeights evaluated,NativeOptimizerState evaluatedOptimizer=null){if(evaluated==null)return;lock(stateLock){state.qualifiedWeights=evaluated.Clone();state.qualifiedOptimizer=NativeMovementLearningState.CloneOptimizer(evaluatedOptimizer??publishedOptimizer,evaluated);}}
    private void SaveQualifiedLocked(NativeMovementWeights evaluated){state.qualifiedWeights=evaluated.Clone();state.qualifiedOptimizer=NativeMovementLearningState.CloneOptimizer(publishedOptimizer,published);}
    public NativeMovementWeights SnapshotQualified(){lock(stateLock)return (state.qualifiedWeights??published).Clone();}
    public NativeOptimizerState SnapshotPublishedOptimizer(){lock(stateLock)return NativeMovementLearningState.CloneOptimizer(publishedOptimizer,published);}
    public void RollbackToQualified(){lock(stateLock){if(state.qualifiedWeights==null)return;state.weights=state.qualifiedWeights.Clone();state.optimizer=NativeMovementLearningState.CloneOptimizer(state.qualifiedOptimizer,state.qualifiedWeights);published=state.weights.Clone();state.modelVersion++;}}
    public bool Enqueue(NativeMovementTransition transition){if(transition==null)return false;if(Interlocked.Increment(ref queued)>2048){Interlocked.Decrement(ref queued);Dropped++;return false;}queue.Enqueue(transition.Clone());signal.Set();return true;}
    public bool TryResult(out NativeMovementMetrics metrics)=>results.TryDequeue(out metrics);
    public NativeMovementWeights SnapshotPublished(){lock(stateLock)return published.Clone();}
    public NativePolicyDecision Decide(NativeMovementObservation observation,bool refreshRhythm,bool stochastic,NativeMovementWeights frozenEvaluationWeights=null)
    {
        NativeMovementWeights w;int version;bool curiosityReady;lock(stateLock){w=frozenEvaluationWeights?.Clone()??published.Clone();version=state.modelVersion;curiosityReady=allowCuriosity&&frozenEvaluationWeights==null&&state.curiosityReady&&!state.simpleBodyQualified;}NativeGraphCache c=ForwardGraph(observation,w);int dims=1+NativeCreatureModel.MaxLimbs*NativeMovementWeights.PolicyLimbOutputs;float[] mean=new float[dims],sample=new float[dims];mean[0]=Dense(c.policyContext,w.frequency,1,0)[0];for(int l=0;l<observation.limbCount;l++){float[] context=Concat(c.state[3][l],c.global);float[] limb=Dense(context,w.limbPolicy,NativeMovementWeights.PolicyLimbOutputs,0);for(int k=0;k<NativeMovementWeights.PolicyLimbOutputs;k++)mean[1+l*NativeMovementWeights.PolicyLimbOutputs+k]=limb[k];}
        float logp=0f;for(int i=0;i<dims;i++){bool active=DimensionActive(i,refreshRhythm,observation.limbCount);float std=Mathf.Exp(Mathf.Clamp(w.logStd[i],-2.3f,.4f));float z=stochastic&&active?Gaussian(ref rng):0f;sample[i]=mean[i]+std*z;if(active)logp+=GaussianLogProbability(sample[i],mean[i],std);}
        float[] held=observation.heldRhythm==null?new float[1+NativeCreatureModel.MaxLimbs*3]:(float[])observation.heldRhythm.Clone();if(refreshRhythm){held[0]=Mathf.Lerp(.25f,3f,Sigmoid(sample[0]));for(int l=0;l<observation.limbCount;l++){int p=1+l*4,h=1+l*3;held[h]=8f*Sigmoid(sample[p]);held[h+1]=Mathf.PI*(float)Math.Tanh(sample[p+1]);held[h+2]=8f*(float)Math.Tanh(sample[p+2]);}}
        float[] requested=new float[NativeCreatureModel.MaxLimbs];for(int l=0;l<observation.limbCount;l++){int p=1+l*4,h=1+l*3;float correction=4f*(float)Math.Tanh(sample[p+3]);requested[l]=Mathf.Clamp(held[h]*Mathf.Sin(Mathf.Atan2(observation.oscillatorSin,observation.oscillatorCos)+held[h+1])+held[h+2]+correction,-8f,8f);}
        float value=Dense(c.policyContext,w.value,1,0)[0],curiosity=curiosityReady?PredictDisagreement(c,requested,w):0f;return new NativePolicyDecision{mean=mean,sample=sample,requested=requested,executed=(float[])requested.Clone(),heldRhythm=held,oldLogProbability=logp,value=value,frequency=held[0],phase=Mathf.Atan2(observation.oscillatorSin,observation.oscillatorCos),curiosity=Mathf.Min(CuriosityCap,curiosity),sampledRhythm=refreshRhythm,modelVersion=version};
    }
    public static float GaussianLogProbability(float sample,float mean,float std){float z=(sample-mean)/Mathf.Max(1e-6f,std);return -.5f*z*z-Mathf.Log(Mathf.Max(1e-6f,std))-.5f*Mathf.Log(2f*Mathf.PI);}
    public static float GaussianMeanGradient(float sample,float mean,float std)=>(sample-mean)/Mathf.Max(1e-6f,std*std);
    public static float PpoSurrogate(float ratio,float advantage)=>-Mathf.Min(ratio*advantage,Mathf.Clamp(ratio,1f-PpoClip,1f+PpoClip)*advantage);
    public static float TravelReward(Vector2 delta,Vector2 command,float oldSpeed,float newSpeed){if(command.sqrMagnitude<.01f)return Mathf.Clamp(oldSpeed-newSpeed,-.1f,.1f);return Mathf.Clamp(Vector2.Dot(delta,command.normalized)/BodyMorphologyRules.TorsoWidth,-.1f,.1f);}
    public static float EffortPenalty(float[] actions,int limbCount){float sum=0f;for(int i=0;i<Mathf.Min(limbCount,actions?.Length??0);i++){float n=actions[i]/8f;sum+=n*n;}return .001f*sum/Mathf.Max(1,limbCount);}
    public static Vector2 GeometryEndpoint(Vector2 currentBase,Vector2 currentEndpoint,float jointDeltaRadians,Vector2 parentDelta){Vector2 arm=currentEndpoint-currentBase;float c=Mathf.Cos(jointDeltaRadians),s=Mathf.Sin(jointDeltaRadians);return currentBase+parentDelta+new Vector2(c*arm.x-s*arm.y,s*arm.x+c*arm.y);}
    public static float GeometryEndpointLoss(Vector2 currentBase,Vector2 currentEndpoint,float jointDeltaRadians,Vector2 parentDelta,Vector2 target){Vector2 e=GeometryEndpoint(currentBase,currentEndpoint,jointDeltaRadians,parentDelta)-target;return .5f*e.sqrMagnitude;}
    public static float GeometryEndpointAngleGradient(Vector2 currentBase,Vector2 currentEndpoint,float jointDeltaRadians,Vector2 parentDelta,Vector2 target){Vector2 arm=currentEndpoint-currentBase;float c=Mathf.Cos(jointDeltaRadians),s=Mathf.Sin(jointDeltaRadians);Vector2 e=GeometryEndpoint(currentBase,currentEndpoint,jointDeltaRadians,parentDelta)-target,d=new Vector2(-s*arm.x-c*arm.y,c*arm.x-s*arm.y);return Vector2.Dot(e,d);}
    public static float ValueLoss(float value,float target)=>.5f*(value-target)*(value-target);
    public static float InverseLoss(float score,float label){float p=Sigmoid(score);return -(label*Mathf.Log(Mathf.Max(1e-6f,p))+(1f-label)*Mathf.Log(Mathf.Max(1e-6f,1f-p)));}
    public static float InverseGradient(float score,float label)=>Sigmoid(score)-label;
    public static float[] HorizonEncodingForTesting(float[] actions,int limbs,int horizon)=>ActionsWithHorizon(actions,limbs,horizon);
    public static float[] PolicyMeanForTesting(NativeMovementObservation observation,NativeMovementWeights weights){NativeGraphCache c=ForwardGraph(observation,weights);return PolicyMean(c,weights,observation.limbCount);}
    public static float[] PolicyGradientForTesting(NativeMovementObservation observation,NativeMovementWeights weights,string parameter,int output){NativeGraphCache c=ForwardGraph(observation,weights);float[] grad=new float[1+NativeCreatureModel.MaxLimbs*NativeMovementWeights.PolicyLimbOutputs];grad[output]=1f;var all=Zero(weights);BackpropPolicy(c,grad,0f,weights,all);return all[parameter];}
    private void Run(){while(!stopping){if(!queue.TryDequeue(out NativeMovementTransition t)){signal.WaitOne(50);continue;}Interlocked.Decrement(ref queued);Busy=true;try{NativeMovementMetrics metrics;lock(stateLock){Offer(t);if(t.evaluation)metrics=EvaluateHeldOut(t);else{rollout.Enqueue(t);metrics=trainM3?TrainDynamics(t):new NativeMovementMetrics{policyUpdates=state.policyUpdates,m3Updates=state.m3Updates,batchSize=1};if(rollout.Count>=RolloutSize){List<NativeMovementTransition> batch=new List<NativeMovementTransition>();while(batch.Count<RolloutSize&&rollout.TryDequeue(out var x))batch.Add(x);TrainPpo(batch,metrics);state.modelVersion++;}state.freshTransitions++;state.curiosityReady=trainM3&&allowCuriosity&&state.freshTransitions>=512&&metrics.inverseAccuracy>=.55f;}}results.Enqueue(metrics);}catch(Exception){Dropped++;}finally{Busy=false;}}}
    private void Offer(NativeMovementTransition t){if(!horizonWindows.TryGetValue(t.controllerId??"",out var window))horizonWindows[t.controllerId??""]=window=new List<NativeMovementTransition>();if(window.Count>0&&(window[window.Count-1].episode!=t.episode||window[window.Count-1].nextObservation?.tick!=t.observation?.tick||window[window.Count-1].evaluation!=t.evaluation))window.Clear();window.Add(t);if(window.Count>20)window.RemoveAt(0);foreach(int horizon in new[]{1,5,10})if(window.Count>=horizon){NativeMovementTransition aggregate=Aggregate(window.Skip(window.Count-horizon).ToList(),horizon);if(aggregate.evaluation)AddBounded(state.validation,aggregate,ValidationCapacity);else{AddBounded(state.recent,aggregate,ReplayCapacity);if(Mathf.Abs(aggregate.travelReward)>=.02f)AddBounded(state.progress,aggregate,SpecialReplayCapacity);if(aggregate.contactTransition)AddBounded(state.contact,aggregate,SpecialReplayCapacity);}}if(!t.evaluation&&window.Count>=20){NativeMovementTransition segment=Aggregate(window.Skip(window.Count-20).ToList(),20);if(segment.reward>segment.decision.value&&Mathf.Abs(segment.travelReward)>=.05f)AddBalancedImitation(segment);}}
    private void AddBalancedImitation(NativeMovementTransition t){string key=(t.bodySignature??"")+":"+Math.Sign(t.observation?.command.x??0f);List<NativeMovementTransition> same=state.imitation.Where(x=>(x.bodySignature??"")+":"+Math.Sign(x.observation?.command.x??0f)==key).ToList();if(same.Count>=128)state.imitation.Remove(same[0]);AddBounded(state.imitation,t,SpecialReplayCapacity);}
    private static NativeMovementTransition Aggregate(List<NativeMovementTransition> steps,int horizon){NativeMovementTransition first=steps[0].Clone(),last=steps[steps.Count-1];first.nextObservation=last.nextObservation?.Clone();first.horizonSteps=horizon;first.torsoDeltaX=steps.Sum(x=>x.torsoDeltaX);first.torsoDeltaY=steps.Sum(x=>x.torsoDeltaY);first.headingDelta=steps.Sum(x=>x.headingDelta);first.angularVelocityDelta=last.angularVelocityDelta;first.reward=steps.Sum(x=>x.reward);first.travelReward=steps.Sum(x=>x.travelReward);first.effortPenalty=steps.Sum(x=>x.effortPenalty);first.curiosityReward=steps.Sum(x=>x.curiosityReward);first.contactTransition=steps.Any(x=>x.contactTransition);first.terminal=last.terminal;if(first.decision?.executed!=null)for(int i=0;i<first.decision.executed.Length;i++)first.decision.executed[i]=steps.Average(x=>x.decision?.executed!=null&&i<x.decision.executed.Length?x.decision.executed[i]:0f);return first;}
    private static void AddBounded(List<NativeMovementTransition> list,NativeMovementTransition t,int capacity){if(list.Count>=capacity)list.RemoveAt(0);list.Add(t.Clone());}
    private NativeMovementMetrics TrainDynamics(NativeMovementTransition fresh)
    {
        var metrics=new NativeMovementMetrics{policyUpdates=state.policyUpdates,m3Updates=state.m3Updates};List<NativeMovementTransition> batch=new List<NativeMovementTransition>{fresh};SampleInto(state.recent,batch,2);SampleInto(state.progress.Count>0?state.progress:state.recent,batch,2);SampleInto(state.contact.Count>0?state.contact:state.recent,batch,2);metrics.batchSize=batch.Count;float total=0f,correct=0f;var gradients=Zero(state.weights);foreach(var t in batch){NativeGraphCache c=ForwardGraph(t.observation,state.weights);float[] action=ActionsWithHorizon(t.decision?.executed,t.observation.limbCount,t.horizonSteps);float[] input=Concat(c.pooled,action),target=PhysicalTarget(t);int head=(int)(Math.Abs((t.sampleId??"").GetHashCode())%3);float[] matrix=head==0?state.weights.m3Head0:head==1?state.weights.m3Head1:state.weights.m3Head2,bias=head==0?state.weights.m3Bias0:head==1?state.weights.m3Bias1:state.weights.m3Bias2;float[] predicted=Dense(input,matrix,NativeMovementWeights.TargetSize,0,bias);float[] outGrad=new float[predicted.Length];for(int i=0;i<predicted.Length;i++){float e=predicted[i]-target[i],weight=PhysicalGroupWeight(i,t.observation.limbCount);total+=weight*e*e;outGrad[i]=2f*weight*e;}AddGeometryConsistency(t,predicted,outGrad);DenseBackward(input,outGrad,matrix,gradients[head==0?"m3Head0":head==1?"m3Head1":"m3Head2"],gradients[head==0?"m3Bias0":head==1?"m3Bias1":"m3Bias2"],out float[] inputGrad);float score=Dot(input,state.weights.inverse),p=Sigmoid(score),d=p-1f;for(int i=0;i<input.Length;i++){gradients["inverse"][i]+=d*input[i];inputGrad[i]+=d*state.weights.inverse[i];}correct+=p>=.5f?1f:0f;float[] shuffled=(float[])action.Clone();if(t.observation.limbCount>1){float q=shuffled[0];shuffled[0]=shuffled[t.observation.limbCount-1];shuffled[t.observation.limbCount-1]=q;}float[] negative=Concat(c.pooled,shuffled);p=Sigmoid(Dot(negative,state.weights.inverse));d=p;for(int i=0;i<negative.Length;i++){gradients["inverse"][i]+=d*negative[i];inputGrad[i]+=d*state.weights.inverse[i];}correct+=p<.5f?1f:0f;if(ReferenceEquals(t,fresh)){float[] encoderGradient=inputGrad.Take(NativeMovementWeights.Width).ToArray();for(int i=0;i<encoderGradient.Length;i++)encoderGradient[i]*=.1f;BackwardGraph(c,encoderGradient,state.weights,gradients);}}
        Scale(gradients,1f/batch.Count);ApplyAdam(state.weights,gradients,state.optimizer,LearningRate,.5f);state.m3Updates++;metrics.m3Updates=state.m3Updates;metrics.m3Loss=total/batch.Count;metrics.inverseAccuracy=correct/(batch.Count*2f);metrics.curiosity=fresh.decision?.curiosity??0f;return metrics;
    }
    private static float PhysicalGroupWeight(int index,int limbs){limbs=Mathf.Max(1,limbs);if(index<6)return 1f/(5f*6f);int channel=(index-6)%10;if(channel<2)return 1f/(5f*2f*limbs);if(channel<6)return 1f/(5f*4f*limbs);if(channel<9)return 1f/(5f*3f*limbs);return 1f/(5f*limbs);}
    private static void AddGeometryConsistency(NativeMovementTransition t,float[] prediction,float[] gradient)
    {
        NativeObservation a=t.observation?.history?.LastOrDefault(x=>x!=null);if(a?.jointFeatures==null)return;const float weight=.1f;for(int l=0;l<Mathf.Min(t.observation.limbCount,NativeCreatureModel.MaxLimbs);l++){int y=6+l*10,j=l*NativeCreatureModel.JointFeatureSize;float sin=a.jointFeatures[j]+prediction[y],cos=a.jointFeatures[j+1]+prediction[y+1],den=Mathf.Max(1e-4f,sin*sin+cos*cos);float oldAngle=Mathf.Atan2(a.jointFeatures[j],a.jointFeatures[j+1]),newAngle=Mathf.Atan2(sin,cos),angle=Mathf.DeltaAngle(oldAngle*Mathf.Rad2Deg,newAngle*Mathf.Rad2Deg)*Mathf.Deg2Rad;Vector2 basePoint=new Vector2(a.jointFeatures[j+7],a.jointFeatures[j+8]),tip=new Vector2(a.jointFeatures[j+9],a.jointFeatures[j+10]),parentDelta=new Vector2(prediction[0],prediction[1]),mechanical=GeometryEndpoint(basePoint,tip,angle,parentDelta),claimed=tip+new Vector2(prediction[y+2],prediction[y+3]),error=claimed-mechanical;gradient[y+2]+=weight*error.x;gradient[y+3]+=weight*error.y;float angleGradient=-weight*GeometryEndpointAngleGradient(basePoint,tip,angle,parentDelta,claimed);gradient[y]+=angleGradient*cos/den;gradient[y+1]-=angleGradient*sin/den;gradient[0]-=weight*error.x;gradient[1]-=weight*error.y;}
    }
    private NativeMovementMetrics EvaluateHeldOut(NativeMovementTransition t)
    {
        NativeGraphCache c=ForwardGraph(t.observation,published);float[] action=ActionsWithHorizon(t.decision?.executed,t.observation.limbCount,t.horizonSteps),input=Concat(c.pooled,action),blind=Concat(c.pooled,ActionsWithHorizon(null,t.observation.limbCount,t.horizonSteps)),target=PhysicalTarget(t),prediction=EnsemblePrediction(input,published),blindPrediction=EnsemblePrediction(blind,published),constant=new float[NativeMovementWeights.TargetSize];NativeObservation current=t.observation?.history?.LastOrDefault(x=>x!=null);float seconds=t.horizonSteps*FastActionTicks*.02f;constant[0]=(current?.torsoWithoutGoal?[2]??0f)*seconds/BodyMorphologyRules.TorsoWidth;constant[1]=(current?.torsoWithoutGoal?[3]??0f)*seconds/BodyMorphologyRules.TorsoHeight;float model=MeanSquared(prediction,target),zero=MeanSquared(new float[target.Length],target),velocity=MeanSquared(constant,target),actionBlind=MeanSquared(blindPrediction,target);bool moving=Mathf.Abs(t.torsoDeltaX)+Mathf.Abs(t.torsoDeltaY)>.01f;return new NativeMovementMetrics{evaluation=true,batchSize=1,policyUpdates=state.policyUpdates,m3Updates=state.m3Updates,m3Loss=model,noChangeLoss=zero,constantVelocityLoss=velocity,actionBlindLoss=actionBlind,movingLoss=moving?model:0f,stationaryLoss=moving?0f:model,contactLoss=t.contactTransition?model:0f};
    }
    private static float[] EnsemblePrediction(float[] input,NativeMovementWeights w){float[][] p={Dense(input,w.m3Head0,NativeMovementWeights.TargetSize,0,w.m3Bias0),Dense(input,w.m3Head1,NativeMovementWeights.TargetSize,0,w.m3Bias1),Dense(input,w.m3Head2,NativeMovementWeights.TargetSize,0,w.m3Bias2)};float[] mean=new float[NativeMovementWeights.TargetSize];for(int i=0;i<mean.Length;i++)mean[i]=(p[0][i]+p[1][i]+p[2][i])/3f;return mean;}
    private static float MeanSquared(float[] a,float[] b){float sum=0f;for(int i=0;i<Math.Min(a.Length,b.Length);i++){float e=a[i]-b[i];sum+=e*e;}return sum/Mathf.Max(1,Math.Min(a.Length,b.Length));}
    private void TrainPpo(List<NativeMovementTransition> batch,NativeMovementMetrics metrics)
    {
        float[] advantage=new float[batch.Count],returns=new float[batch.Count];var byController=batch.Select((t,i)=>(t,i)).GroupBy(x=>x.t.controllerId+":"+x.t.episode);foreach(var group in byController){float gae=0f;foreach(var item in group.OrderByDescending(x=>x.i)){var t=item.t;float next=t.terminal?0f:(t.nextObservation==null?0f:Value(t.nextObservation,state.weights));float delta=t.reward+Gamma*next-(t.decision?.value??0f);gae=delta+Gamma*GaeLambda*(t.terminal?0f:gae);advantage[item.i]=gae;returns[item.i]=gae+(t.decision?.value??0f);}}float mean=advantage.Average(),std=Mathf.Sqrt(advantage.Select(x=>(x-mean)*(x-mean)).Average()+1e-6f);for(int i=0;i<advantage.Length;i++)advantage[i]=(advantage[i]-mean)/std;
        for(int epoch=0;epoch<PpoEpochs;epoch++){float kl=0f;for(int offset=0;offset<batch.Count;offset+=MiniBatchSize){int end=Math.Min(batch.Count,offset+MiniBatchSize);var gradients=Zero(state.weights);for(int i=offset;i<end;i++){NativeMovementTransition t=batch[i];NativeGraphCache c=ForwardGraph(t.observation,state.weights);float[] newMean=PolicyMean(c,state.weights,t.observation.limbCount),sample=t.decision.sample;float logp=0f;for(int d=0;d<newMean.Length;d++)if(DimensionActive(d,t.decision.sampledRhythm,t.observation.limbCount)){float sigma=Mathf.Exp(Mathf.Clamp(state.weights.logStd[d],-2.3f,.4f));logp+=GaussianLogProbability(sample[d],newMean[d],sigma);}float ratio=Mathf.Exp(Mathf.Clamp(logp-t.decision.oldLogProbability,-10f,10f));bool clipped=(advantage[i]>=0f&&ratio>1f+PpoClip)||(advantage[i]<0f&&ratio<1f-PpoClip);float policyScale=clipped?0f:-advantage[i]*ratio;float[] meanGrad=new float[newMean.Length];for(int d=0;d<newMean.Length;d++)if(DimensionActive(d,t.decision.sampledRhythm,t.observation.limbCount)){float sigma=Mathf.Exp(Mathf.Clamp(state.weights.logStd[d],-2.3f,.4f)),variance=sigma*sigma;meanGrad[d]=policyScale*(sample[d]-newMean[d])/variance;gradients["logStd"][d]+=policyScale*((sample[d]-newMean[d])*(sample[d]-newMean[d])/variance-1f)-.001f;}if(Mathf.Abs(t.travelReward)>=.02f&&t.reward>t.decision.value)for(int d=0;d<newMean.Length;d++)if(DimensionActive(d,t.decision.sampledRhythm,t.observation.limbCount))meanGrad[d]+=ImitationCoefficient*(newMean[d]-sample[d]);float value=ValueFromCache(c,state.weights),ve=value-returns[i];BackpropPolicy(c,meanGrad,ve,state.weights,gradients);metrics.policyLoss+=PpoSurrogate(ratio,advantage[i]);metrics.valueLoss+=.5f*ve*ve;kl+=t.decision.oldLogProbability-logp;}
                Scale(gradients,1f/(end-offset));ApplyAdam(state.weights,gradients,state.optimizer,LearningRate,.5f);}metrics.approximateKl=kl/batch.Count;if(metrics.approximateKl>MaxKl)break;}
        TrainSelfImitation();state.policyUpdates++;published=state.weights.Clone();publishedOptimizer=NativeMovementLearningState.CloneOptimizer(state.optimizer,state.weights);metrics.policyUpdates=state.policyUpdates;metrics.policyLoss/=Mathf.Max(1,batch.Count);metrics.valueLoss/=Mathf.Max(1,batch.Count);
    }
    private void TrainSelfImitation(){if(state.imitation.Count==0)return;var gradients=Zero(state.weights);List<NativeMovementTransition> samples=state.imitation.Skip(Math.Max(0,state.imitation.Count-16)).ToList();foreach(var t in samples){NativeGraphCache c=ForwardGraph(t.observation,state.weights);float[] mean=PolicyMean(c,state.weights,t.observation.limbCount),target=t.decision.sample,gradient=new float[mean.Length];for(int i=0;i<mean.Length;i++)if(DimensionActive(i,t.decision.sampledRhythm,t.observation.limbCount))gradient[i]=ImitationCoefficient*(mean[i]-target[i]);BackpropPolicy(c,gradient,0f,state.weights,gradients);}Scale(gradients,1f/samples.Count);ApplyAdam(state.weights,gradients,state.optimizer,LearningRate,.5f);}
    private static bool DimensionActive(int d,bool slow,int limbs){if(d==0)return slow;int limb=(d-1)/NativeMovementWeights.PolicyLimbOutputs,channel=(d-1)%NativeMovementWeights.PolicyLimbOutputs;return limb<limbs&&(channel==3||slow);}
    private static void BackpropPolicy(NativeGraphCache c,float[] meanGrad,float valueGrad,NativeMovementWeights w,Dictionary<string,float[]> g){float[] pooledGrad=new float[NativeMovementWeights.Width];float[] contextGrad=DenseBackward(c.policyContext,new[]{meanGrad[0]},w.frequency,g["frequency"],null);Add(pooledGrad,contextGrad);contextGrad=DenseBackward(c.policyContext,new[]{valueGrad},w.value,g["value"],null);Add(pooledGrad,contextGrad);float[][] nodeGrad=Enumerable.Range(0,c.observation.limbCount).Select(_=>new float[NativeMovementWeights.Width]).ToArray();for(int l=0;l<c.observation.limbCount;l++){float[] og=new float[NativeMovementWeights.PolicyLimbOutputs];Array.Copy(meanGrad,1+l*NativeMovementWeights.PolicyLimbOutputs,og,0,og.Length);float[] ig=DenseBackward(Concat(c.state[3][l],c.global),og,w.limbPolicy,g["limbPolicy"],null);Add(nodeGrad[l],ig);}for(int l=0;l<nodeGrad.Length;l++)for(int h=0;h<NativeMovementWeights.Width;h++)nodeGrad[l][h]+=pooledGrad[h]/Mathf.Max(1,nodeGrad.Length);BackwardGraph(c,nodeGrad,w,g);}
    private static NativeGraphCache ForwardGraph(NativeMovementObservation o,NativeMovementWeights w){int n=Mathf.Clamp(o.limbCount,0,NativeCreatureModel.MaxLimbs);var c=new NativeGraphCache{observation=o,input=new float[n][],state=new float[4][][],parent=new int[n]};c.state[0]=new float[n][];NativeObservation current=o.history?.LastOrDefault(x=>x!=null);for(int l=0;l<n;l++){float[] x=new float[NativeMovementWeights.NodeInput];int at=0;for(int f=0;f<NativeMovementWeights.HistoryLength;f++){NativeObservation frame=o.history!=null&&f<o.history.Length?o.history[f]:null;for(int j=0;j<NativeCreatureModel.JointFeatureSize;j++)x[at++]=frame?.jointFeatures?[l*NativeCreatureModel.JointFeatureSize+j]??0f;}for(int j=0;j<NativeCreatureModel.PositionEncodingSize;j++)x[at++]=current?.positionEncodings?[l*NativeCreatureModel.PositionEncodingSize+j]??0f;int held=1+l*3;x[at++]=o.heldRhythm!=null&&held<o.heldRhythm.Length?o.heldRhythm[held]/8f:0f;x[at++]=o.heldRhythm!=null&&held+1<o.heldRhythm.Length?o.heldRhythm[held+1]/Mathf.PI:0f;x[at++]=o.heldRhythm!=null&&held+2<o.heldRhythm.Length?o.heldRhythm[held+2]/8f:0f;x[at]=current?.jointFeatures?[l*NativeCreatureModel.JointFeatureSize+18]??0f;c.input[l]=x;c.state[0][l]=Activate(Dense(x,w.nodeInput,NativeMovementWeights.Width,0,w.nodeBias));c.parent[l]=FindParent(current,l);}
        for(int round=1;round<=3;round++){c.state[round]=new float[n][];for(int l=0;l<n;l++){float[] z=Dense(c.state[round-1][l],w.messageSelf,NativeMovementWeights.Width,0,w.messageBias);int p=c.parent[l];if(p>=0)Add(z,Dense(c.state[round-1][p],w.messageParent,NativeMovementWeights.Width,0));int children=0;float[] child=new float[NativeMovementWeights.Width];for(int k=0;k<n;k++)if(c.parent[k]==l){Add(child,c.state[round-1][k]);children++;}if(children>0){for(int h=0;h<child.Length;h++)child[h]/=children;Add(z,Dense(child,w.messageChild,NativeMovementWeights.Width,0));}c.state[round][l]=Activate(z);}}
        c.pooled=new float[NativeMovementWeights.Width];for(int l=0;l<n;l++)Add(c.pooled,c.state[3][l]);if(n>0)for(int h=0;h<c.pooled.Length;h++)c.pooled[h]/=n;c.global=GlobalFeatures(o,current);c.policyContext=Concat(c.pooled,c.global);return c;}
    private static int FindParent(NativeObservation o,int limb){if(o?.parentSlots==null||limb>=o.parentSlots.Length)return -1;int innovation=o.parentSlots[limb];if(innovation<=0)return -1;for(int i=0;i<limb;i++)if(o.parentSlots[i]==innovation)return i;return innovation-1<limb?innovation-1:-1;}
    private static float[] GlobalFeatures(NativeMovementObservation o,NativeObservation current){float[] g=new float[NativeMovementWeights.GlobalInput];if(current?.torsoWithoutGoal!=null)Array.Copy(current.torsoWithoutGoal,2,g,0,Math.Min(16,current.torsoWithoutGoal.Length-2));g[16]=o.angularVelocity/720f;g[17]=o.gravityLocal.x;g[18]=o.gravityLocal.y;g[19]=o.command.x;g[20]=o.command.y;g[21]=o.oscillatorSin;g[22]=o.oscillatorCos;g[23]=o.rhythmTicksRemaining/RhythmActionTicks;g[24]=o.heldRhythm!=null&&o.heldRhythm.Length>0?o.heldRhythm[0]/3f:0f;return g;}
    private static float[] PolicyMean(NativeGraphCache c,NativeMovementWeights w,int limbs){float[] r=new float[1+NativeCreatureModel.MaxLimbs*NativeMovementWeights.PolicyLimbOutputs];r[0]=Dense(c.policyContext,w.frequency,1,0)[0];for(int l=0;l<limbs;l++){float[] x=Dense(Concat(c.state[3][l],c.global),w.limbPolicy,NativeMovementWeights.PolicyLimbOutputs,0);Array.Copy(x,0,r,1+l*4,4);}return r;}
    private static float Value(NativeMovementObservation o,NativeMovementWeights w)=>ValueFromCache(ForwardGraph(o,w),w);private static float ValueFromCache(NativeGraphCache c,NativeMovementWeights w)=>Dense(c.policyContext,w.value,1,0)[0];
    private static float PredictDisagreement(NativeGraphCache c,float[] actions,NativeMovementWeights w){float[] input=Concat(c.pooled,ActionsWithHorizon(actions,c.observation.limbCount,1));float[][] p={Dense(input,w.m3Head0,NativeMovementWeights.TargetSize,0,w.m3Bias0),Dense(input,w.m3Head1,NativeMovementWeights.TargetSize,0,w.m3Bias1),Dense(input,w.m3Head2,NativeMovementWeights.TargetSize,0,w.m3Bias2)};float sum=0f;for(int i=0;i<NativeMovementWeights.TargetSize;i++){float m=(p[0][i]+p[1][i]+p[2][i])/3f;sum+=(p[0][i]-m)*(p[0][i]-m)+(p[1][i]-m)*(p[1][i]-m)+(p[2][i]-m)*(p[2][i]-m);}return Mathf.Min(CuriosityCap,sum/(NativeMovementWeights.TargetSize*3f));}
    private static float[] PhysicalTarget(NativeMovementTransition t){float[] y=new float[NativeMovementWeights.TargetSize];y[0]=t.torsoDeltaX/BodyMorphologyRules.TorsoWidth;y[1]=t.torsoDeltaY/BodyMorphologyRules.TorsoHeight;y[2]=Mathf.Sin(t.headingDelta*Mathf.Deg2Rad);y[3]=Mathf.Cos(t.headingDelta*Mathf.Deg2Rad)-1f;y[4]=t.nextObservation?.history?.LastOrDefault(x=>x!=null)?.torsoWithoutGoal?[2]??0f;y[5]=t.angularVelocityDelta/720f;NativeObservation a=t.observation?.history?.LastOrDefault(x=>x!=null),b=t.nextObservation?.history?.LastOrDefault(x=>x!=null);for(int l=0;l<Mathf.Min(t.observation?.limbCount??0,NativeCreatureModel.MaxLimbs);l++){int o=6+l*10,j=l*NativeCreatureModel.JointFeatureSize;y[o]=(b?.jointFeatures?[j]??0f)-(a?.jointFeatures?[j]??0f);y[o+1]=(b?.jointFeatures?[j+1]??0f)-(a?.jointFeatures?[j+1]??0f);for(int k=0;k<4;k++)y[o+2+k]=(b?.jointFeatures?[j+9+k]??0f)-(a?.jointFeatures?[j+9+k]??0f);for(int k=0;k<3;k++)y[o+6+k]=b?.jointFeatures?[j+4+k]??0f;y[o+9]=(b?.jointFeatures?[j+21]??0f)*(y[o+6]>.5f?1f:0f);}return y;}
    private static float[] ActionsWithHorizon(float[] a,int limbs,int horizon){float[] r=new float[NativeCreatureModel.MaxLimbs+3];for(int i=0;i<Mathf.Min(limbs,a?.Length??0);i++)r[i]=a[i]/8f;r[NativeCreatureModel.MaxLimbs+(horizon>=10?2:horizon>=5?1:0)]=1f;return r;}
    private static void SampleInto(List<NativeMovementTransition> source,List<NativeMovementTransition> target,int count){if(source.Count==0)return;int start=Math.Max(0,source.Count-count);for(int i=start;i<source.Count;i++)target.Add(source[i]);}
    private static Dictionary<string,float[]> Zero(NativeMovementWeights w)=>w.Parameters().ToDictionary(p=>p.Key,p=>new float[p.Value.Length]);private static void Scale(Dictionary<string,float[]> g,float s){foreach(float[] a in g.Values)for(int i=0;i<a.Length;i++)a[i]*=s;}
    private static void ApplyAdam(NativeMovementWeights w,Dictionary<string,float[]> g,NativeOptimizerState optimizer,float rate,float maxNorm){float norm=Mathf.Sqrt(g.Values.Sum(a=>a.Sum(x=>x*x))),scale=norm>maxNorm?maxNorm/norm:1f;optimizer.step++;float c1=1f-Mathf.Pow(.9f,optimizer.step),c2=1f-Mathf.Pow(.999f,optimizer.step);foreach(var p in w.Parameters()){var s=optimizer.Get(p.Key,p.Value.Length);for(int i=0;i<p.Value.Length;i++){float x=g[p.Key][i]*scale;s.first[i]=.9f*s.first[i]+.1f*x;s.second[i]=.999f*s.second[i]+.001f*x*x;p.Value[i]-=rate*(s.first[i]/c1)/(Mathf.Sqrt(s.second[i]/c2)+1e-8f);}}if(!w.IsFinite())throw new InvalidOperationException("v26 learner produced non-finite weights");}
    private static void BackwardGraph(NativeGraphCache c,float[] pooledGradient,NativeMovementWeights w,Dictionary<string,float[]> g){int n=c.state[3].Length;float[][] grad=Enumerable.Range(0,n).Select(_=>(float[])pooledGradient.Clone()).ToArray();for(int l=0;l<n;l++)for(int h=0;h<NativeMovementWeights.Width;h++)grad[l][h]/=Mathf.Max(1,n);BackwardGraph(c,grad,w,g);}
    private static void BackwardGraph(NativeGraphCache c,float[][] grad,NativeMovementWeights w,Dictionary<string,float[]> g){int n=grad.Length,W=NativeMovementWeights.Width;for(int round=3;round>=1;round--){float[][] previous=Enumerable.Range(0,n).Select(_=>new float[W]).ToArray();for(int l=0;l<n;l++){float[] dz=new float[W];for(int h=0;h<W;h++)dz[h]=grad[l][h]*(1f-c.state[round][l][h]*c.state[round][l][h]);float[] self=DenseBackward(c.state[round-1][l],dz,w.messageSelf,g["messageSelf"],g["messageBias"]);Add(previous[l],self);int p=c.parent[l];if(p>=0)Add(previous[p],DenseBackward(c.state[round-1][p],dz,w.messageParent,g["messageParent"],null));int children=Enumerable.Range(0,n).Count(k=>c.parent[k]==l);if(children>0){float[] avg=new float[W];for(int k=0;k<n;k++)if(c.parent[k]==l)Add(avg,c.state[round-1][k]);for(int h=0;h<W;h++)avg[h]/=children;float[] cg=DenseBackward(avg,dz,w.messageChild,g["messageChild"],null);for(int k=0;k<n;k++)if(c.parent[k]==l)for(int h=0;h<W;h++)previous[k][h]+=cg[h]/children;}}grad=previous;}for(int l=0;l<n;l++){float[] dz=new float[W];for(int h=0;h<W;h++)dz[h]=grad[l][h]*(1f-c.state[0][l][h]*c.state[0][l][h]);DenseBackward(c.input[l],dz,w.nodeInput,g["nodeInput"],g["nodeBias"]);}}
    private static float[] DenseBackward(float[] input,float[] outputGradient,float[] weights,float[] weightGradient,float[] biasGradient){DenseBackward(input,outputGradient,weights,weightGradient,biasGradient,out float[] result);return result;}private static void DenseBackward(float[] input,float[] outputGradient,float[] weights,float[] weightGradient,float[] biasGradient,out float[] inputGradient){int outputs=outputGradient.Length;inputGradient=new float[input.Length];for(int i=0;i<input.Length;i++)for(int o=0;o<outputs;o++){int k=i*outputs+o;weightGradient[k]+=input[i]*outputGradient[o];inputGradient[i]+=weights[k]*outputGradient[o];}if(biasGradient!=null)for(int o=0;o<outputs;o++)biasGradient[o]+=outputGradient[o];}
    private static float[] Dense(float[] input,float[] weights,int outputs,int biasOffset,float[] bias=null){float[] r=new float[outputs];for(int i=0;i<input.Length;i++)for(int o=0;o<outputs;o++)r[o]+=input[i]*weights[i*outputs+o];if(bias!=null)for(int o=0;o<outputs;o++)r[o]+=bias[biasOffset+o];return r;}private static float[] Activate(float[] x){for(int i=0;i<x.Length;i++)x[i]=(float)Math.Tanh(x[i]);return x;}private static float[] Concat(float[] a,float[] b){float[] r=new float[a.Length+b.Length];Array.Copy(a,r,a.Length);Array.Copy(b,0,r,a.Length,b.Length);return r;}private static void Add(float[] target,float[] source){for(int i=0;i<Math.Min(target.Length,source.Length);i++)target[i]+=source[i];}private static float Dot(float[] a,float[] b){float r=0f;for(int i=0;i<Math.Min(a.Length,b.Length);i++)r+=a[i]*b[i];return r;}private static float Sigmoid(float x)=>1f/(1f+Mathf.Exp(-Mathf.Clamp(x,-20f,20f)));private static float Gaussian(ref NativeDeterministicRng r){float a=Mathf.Max(1e-7f,r.NextFloat()),b=r.NextFloat();return Mathf.Sqrt(-2f*Mathf.Log(a))*Mathf.Cos(2f*Mathf.PI*b);}
    public void Dispose(){stopping=true;signal.Set();if(worker.IsAlive)worker.Join(2000);signal.Dispose();}
}
