using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Newtonsoft.Json;
using UnityEngine;

[DefaultExecutionOrder(-80)]
[DisallowMultipleComponent]
public sealed class NativeEcosystemController : MonoBehaviour
{
    private const float MinimumSpawnSeparation=64f; public const float TemporaryGoalRewardEnergy=100f,TemporaryGoalReachRadius=1.25f; public const int InitialBodySpeciesCount=6; private const int CreatureLayerBase=8,CreatureLayerCount=10,NativeSpawnSlots=6,ValidationCapacity=64;
    public int populationTarget=6;
    [SerializeField] private bool enableM1=false;
    public int controlIntervalTicks=NativeCreatureModel.ActionTicks;
    public float evolutionIntervalSeconds=75f,checkpointIntervalSeconds=30f;
    public bool allowForcedEvolution=true,loadCheckpointOnStart=true;
    public int bodyMutationCooldownGenerations=12;
    public string checkpointFileName="native_ecosystem_v18.json";
    public string Status{get;private set;}="Starting native ecosystem";
    public int Tick{get;private set;} public int Generation{get;private set;} public int Population=>agents.Count; public int SpeciesCount=>agents.Where(a=>a.identity!=null).Select(a=>a.identity.speciesId).Distinct().Count();
    public float LastM3Loss{get;private set;} public float LastM3Mse{get;private set;} public float LastM3RelativeLoss{get;private set;} public float LastM3VelocityLoss{get;private set;} public float LastM3ContactLoss{get;private set;} public float LastM2Loss{get;private set;} public float LastM2GoalLoss{get;private set;} public float LastM2EnergyLoss{get;private set;}
    public int GoalTicksRemaining{get;private set;} public int SequenceStep{get;private set;} public int SharedM3Samples{get;private set;} public int SharedM3OptimizerSteps{get;private set;} public int SharedM3Updates=>SharedM3OptimizerSteps; public int LastM3BatchSize{get;private set;} public int TemporaryGoalRecenters{get;private set;} public float BiasStrength{get;private set;} public float ExplorationSigma{get;private set;}
    public float PlannerMilliseconds{get;private set;} public float M2TrainingMilliseconds{get;private set;} public float M3TrainingMilliseconds{get;private set;} public float CheckpointMilliseconds{get;private set;} public int M2TrainingUpdates{get;private set;} public float LastActionMagnitude{get;private set;}
    public float LeftProposalLoss{get;private set;}=float.PositiveInfinity; public float RightProposalLoss{get;private set;}=float.PositiveInfinity; public int LeftProposalSamples{get;private set;} public int RightProposalSamples{get;private set;} public string DirectionState{get;private set;}="neutral";
    public Vector2[] LastPredictedPositions{get;private set;}=new Vector2[5]; public Vector2[] LastActualPositions{get;private set;}=new Vector2[5]; public Vector2[] LastPredictedHeadings{get;private set;}=new Vector2[5]; public Vector2[] LastActualHeadings{get;private set;}=new Vector2[5];
    public float MeanM1EnergyFitness=>agents.Count==0?0f:agents.Average(a=>a.m1EnergyFitness); public float RenderRateHz{get;private set;} public string PhysicsMode=>Physics2D.simulationMode.ToString();
    public string CheckpointStatus{get;private set;}="Not saved"; public string LastCheckpointError{get;private set;}=""; public float SecondsUntilCheckpoint=>Mathf.Max(0f,nextCheckpoint-Time.time); public string LastCheckpointSavedAt{get;private set;}="Never";
    public int ActiveControlCount=>agents.Count(a=>a.sequenceActive); public int DeadCreatureCount=>agents.Count(a=>a.brain==null||a.brain.IsDead); public int SettlingCreatureCount=>agents.Count(a=>a.brain!=null&&!a.brain.IsDead&&!a.ReadyForLearning); public int MovingCreatureCount=>agents.Count(a=>a.isSustainedMoving);
    public float MeanRootSpeed=>agents.Where(a=>a.identity?.torso?.Rigidbody!=null&&a.brain!=null&&!a.brain.IsDead).Select(a=>a.identity.torso.Rigidbody.linearVelocity.magnitude).DefaultIfEmpty().Average(); public float MeanJointSpeed=>agents.Where(a=>a.brain!=null&&!a.brain.IsDead).Select(a=>a.brain.MeanJointSpeed).DefaultIfEmpty().Average();
    public int ControlFailures{get;private set;} public string LastControlError{get;private set;}=""; public int ImmediateReplacementCount{get;private set;} public int LastReplacementTick{get;private set;}=-1; public string ReplacementRetryState{get;private set;}="none"; public float PopulationTurns=>Generation/6f; public string ExperimentId{get;private set;}
    public bool M1Enabled=>enableM1; public string M1ActivationSource{get;private set;}="not initialized";
    public bool PopulationDynamicsEnabled{get;private set;}
    public bool PredatorKillsEnabled=>PopulationDynamicsEnabled;
    public bool InteractiveFeaturesEnabled=>PopulationDynamicsEnabled&&enableM1&&environmentSpawner!=null&&environmentSpawner.FeaturesEnabled;

    private sealed class NativeAgent
    {
        public CreatureIdentity identity; public CreatureBrain brain; public BodyGenomeDto body; public NativeCreatureModel model; public Limb[] limbs; public NativeGoalVisualizer goalVisualizer; public NativeEnergyBar energyBar;
        public float deathPenalty,m1EnergyFitness,previousEnergy; public bool deathRecorded,protectedOffspring,hasCompletedInitialSettlement,sequenceActive,isSustainedMoving; public int bodyAgeGenerations,reservedSlot,settledSupportTicks,nextFiniteCheckTick,sequenceStartTick,movingEvidenceTicks,stillEvidenceTicks,motionWindowTicks,temporaryGoalRewardBlock=int.MinValue; public Vector2 motionWindowStartPosition,sequenceStartPosition; public float sequenceStartRotation; public NativeObservation observation; public NativeActionSequence sequence; public readonly float[] actualPoses=new float[NativeCreatureModel.M3OutputSize]; public readonly float[] actualAuxiliary=new float[NativeCreatureModel.M3AuxiliaryOutputSize]; public readonly float[] globalInputs=new float[28]; public bool ReadyForLearning=>hasCompletedInitialSettlement;
    }
    private readonly List<NativeAgent> agents=new List<NativeAgent>(); private readonly Dictionary<NativeAgent,int> replacementRetries=new Dictionary<NativeAgent,int>(); private readonly List<NativeCompletedSequence> validation=new List<NativeCompletedSequence>(); private List<NativeBodySpecies> species=new List<NativeBodySpecies>();
    private NativeBrainWeights seedPolicy; private NativeDynamicsWeights sharedM3; private NativeOptimizerState m3Optimizer=new NativeOptimizerState(); private System.Random random; private float nextEvolution,nextCheckpoint,rateWindowStarted; private int framesAtRateWindow,controlStep,specialistSelectionCursor; private string checkpointPath; private Predator cachedPredator; private EnvironmentSpawner environmentSpawner;

    private void Awake()
    {
        enableM1=false;M1ActivationSource="locked at startup";Application.runInBackground=true;Physics2D.simulationMode=SimulationMode2D.FixedUpdate;populationTarget=Mathf.Max(6,Mathf.Clamp(populationTarget,1,10));controlIntervalTicks=NativeCreatureModel.ActionTicks;checkpointFileName="native_ecosystem_v18.json";random=new System.Random(1337);seedPolicy=NativeBrainWeights.Create(1337);sharedM3=NativeDynamicsWeights.Create(7331);ExperimentId="openloop-v18-"+DateTime.UtcNow.ToString("yyyyMMdd-HHmmss");
        string persistent=Application.persistentDataPath;for(int version=6;version<=17;version++)foreach(string suffix in new[]{"",".bak",".tmp"}){string old=Path.Combine(persistent,"native_ecosystem_v"+version+".json"+suffix);try{if(File.Exists(old))File.Delete(old);}catch(Exception e){Debug.LogError("Failed to delete abandoned checkpoint "+old+": "+e.Message);}}foreach(string oldTensor in Directory.GetFiles(persistent,"native_ecosystem_v17.*.bin*"))try{File.Delete(oldTensor);}catch(Exception e){Debug.LogError("Failed to delete abandoned tensor checkpoint "+oldTensor+": "+e.Message);}
        checkpointPath=Path.Combine(persistent,checkpointFileName);environmentSpawner=GetComponent<EnvironmentSpawner>();if(environmentSpawner!=null)environmentSpawner.LockFeaturesUntilExplicitEnable();if(loadCheckpointOnStart)TryLoad();
    }
    private void Start(){SeedPopulation();RebuildSpeciation();nextEvolution=Time.time+evolutionIntervalSeconds;nextCheckpoint=Time.time+checkpointIntervalSeconds;Status="Native open-loop feed-forward ecosystem running";}
    public void EnableInteractiveFeaturesFromUser(){if(PopulationDynamicsEnabled)return;if(environmentSpawner==null)environmentSpawner=FindAnyObjectByType<EnvironmentSpawner>();if(environmentSpawner!=null)environmentSpawner.EnableFeatures();PopulationDynamicsEnabled=true;foreach(NativeAgent a in agents)if(a.brain!=null)a.brain.DeathsEnabled=true;enableM1=true;M1ActivationSource="telemetry button at tick "+Tick;Status="Food, predators, M1, births, and deaths enabled";}
    private void Update(){if(rateWindowStarted<=0f){rateWindowStarted=Time.unscaledTime;framesAtRateWindow=Time.frameCount;return;}float elapsed=Time.unscaledTime-rateWindowStarted;if(elapsed>=.5f){RenderRateHz=(Time.frameCount-framesAtRateWindow)/elapsed;framesAtRateWindow=Time.frameCount;rateWindowStarted=Time.unscaledTime;}}

    private void FixedUpdate()
    {
        if(Physics2D.simulationMode!=SimulationMode2D.FixedUpdate)Physics2D.simulationMode=SimulationMode2D.FixedUpdate;Tick++;UpdateSettlingState();AdvanceOpenSequences();
        if(Tick%NativeCreatureModel.SequenceTicks==0){controlStep++;TrainCompletedSequences();PlanReadyAgents();}
        foreach(NativeAgent a in agents.ToArray()){if(a.brain==null||a.identity?.torso==null)continue;a.identity.torso.EnergyPenaltyScale=Generation<NativeCreatureModel.FixedGoalGenerations?.1f:1f;a.brain.FixedStep();}
        UpdateTemporaryGoalRewards();if(Tick%NativeEnergyBar.RefreshIntervalTicks==0)UpdateEnergyBarDisplays();UpdateMotionEvidence();if(Tick%50==0)UpdateGoalProgressDisplays();if(PopulationDynamicsEnabled){ReplaceDeadCreaturesImmediately();if(agents.Count>0&&agents.All(a=>a.brain==null||a.brain.IsDead))RecoverFromExtinction();if(allowForcedEvolution&&Time.time>=nextEvolution){nextEvolution+=evolutionIntervalSeconds;Evolve();}MaintainPopulationInvariant();}
    }

    private void AdvanceOpenSequences()
    {
        SequenceStep=0;
        foreach(NativeAgent a in agents)
        {
            if(!a.sequenceActive||a.brain==null||a.brain.IsDead||a.identity?.torso==null)continue;int elapsed=Tick-a.sequenceStartTick;if(elapsed<=0||elapsed%NativeCreatureModel.ActionTicks!=0)continue;int reached=elapsed/NativeCreatureModel.ActionTicks-1;if(reached<0||reached>=5)continue;
            Vector2 worldDelta=(Vector2)a.identity.torso.Rigidbody.position-a.sequenceStartPosition;Vector2 local=Quaternion.Euler(0f,0f,-a.sequenceStartRotation)*worldDelta;Vector2 heading=NativeCreatureModel.HeadingEncoding(a.identity.torso.Rigidbody.rotation-a.sequenceStartRotation);int pose=reached*NativeCreatureModel.PoseValueCount;a.actualPoses[pose]=local.x;a.actualPoses[pose+1]=local.y;a.actualPoses[pose+2]=heading.x;a.actualPoses[pose+3]=heading.y;int aux=reached*NativeCreatureModel.AuxiliaryValueCount;Vector2 velocity=Quaternion.Euler(0f,0f,-a.sequenceStartRotation)*a.identity.torso.Rigidbody.linearVelocity;a.actualAuxiliary[aux]=Mathf.Clamp(velocity.x/NativeCreatureModel.M3VelocityScale,-1f,1f);a.actualAuxiliary[aux+1]=Mathf.Clamp(velocity.y/NativeCreatureModel.M3VelocityScale,-1f,1f);int limbCount=Mathf.Max(1,a.limbs.Length);a.actualAuxiliary[aux+2]=a.limbs.Count(l=>l!=null&&l.TouchingEnvironment)/(float)limbCount;a.actualAuxiliary[aux+3]=a.limbs.Count(l=>l!=null&&l.TouchingSelf)/(float)limbCount;a.actualAuxiliary[aux+4]=a.limbs.Count(l=>l!=null&&l.TouchingOtherCreature)/(float)limbCount;LastActualPositions[reached]=local;LastActualHeadings[reached]=heading;a.model.RecordMeasuredProgress(worldDelta);SequenceStep=reached+1;
            int next=reached+1;if(next<5)ApplySequenceAction(a,next);else a.sequenceActive=false;
        }
    }

    private void TrainCompletedSequences()
    {
        NativeAgent[] completed=agents.Where(a=>a.observation!=null&&a.sequence!=null&&!a.sequenceActive&&a.brain!=null&&!a.brain.IsDead).OrderBy(a=>a.identity.creatureId,StringComparer.Ordinal).ToArray();LastM3BatchSize=completed.Length;if(completed.Length==0)return;long started=System.Diagnostics.Stopwatch.GetTimestamp();var samples=new List<NativeCompletedSequence>(completed.Length);foreach(NativeAgent a in completed){var sample=new NativeCompletedSequence{sampleId=a.identity.creatureId,observation=a.observation,actions=FlattenActions(a.sequence.actions),actualPoses=(float[])a.actualPoses.Clone(),actualAuxiliary=(float[])a.actualAuxiliary.Clone()};samples.Add(sample);validation.Add(sample);if(validation.Count>ValidationCapacity)validation.RemoveAt(0);a.observation=null;a.sequence=null;}NativeM3BatchMetrics metrics=NativeCreatureModel.TrainSharedM3Batch(samples,sharedM3,m3Optimizer);SharedM3Samples+=metrics.sampleCount;SharedM3OptimizerSteps=metrics.optimizerSteps;LastM3Loss=metrics.loss;LastM3Mse=metrics.poseMse;LastM3RelativeLoss=metrics.relativeLoss;LastM3VelocityLoss=metrics.velocityLoss;LastM3ContactLoss=metrics.contactLoss;M3TrainingMilliseconds=(float)((System.Diagnostics.Stopwatch.GetTimestamp()-started)*1000d/System.Diagnostics.Stopwatch.Frequency);
    }

    private void PlanReadyAgents()
    {
        long started=System.Diagnostics.Stopwatch.GetTimestamp();M2TrainingUpdates=0;
        foreach(NativeAgent a in agents)
        {
            if(a.brain==null||a.brain.IsDead||a.identity?.torso==null||!a.ReadyForLearning||a.sequenceActive)continue;
            try
            {
                if(Tick>=a.nextFiniteCheckTick&&!a.model.Weights.IsFinite()){a.model.RepairFrom(seedPolicy);ControlFailures++;LastControlError=a.identity.creatureId+": repaired non-finite weights";}a.nextFiniteCheckTick=Tick+375;
                Rigidbody2D body=a.identity.torso.Rigidbody;PrepareTemporaryGoalLocation(a,body);a.identity.torso.FillNativeGlobalInputs(a.globalInputs);var proprio=new NativeLocalProprioception{worldPosition=body.position,worldRotationDegrees=body.rotation,localLinearVelocity=Quaternion.Euler(0f,0f,-body.rotation)*body.linearVelocity};
                a.observation=a.model.Observe(a.globalInputs,a.limbs,Tick,proprio,enableM1);a.sequence=a.model.OptimizeAndPlan(a.observation,sharedM3,SharedM3Samples);a.sequenceStartTick=Tick;a.sequenceStartPosition=body.position;a.sequenceStartRotation=body.rotation;Array.Clear(a.actualPoses,0,a.actualPoses.Length);Array.Clear(a.actualAuxiliary,0,a.actualAuxiliary.Length);a.sequenceActive=true;ApplySequenceAction(a,0);M2TrainingUpdates++;
                LastM2Loss=a.model.LastM2Loss;LastM2GoalLoss=a.model.LastM2GoalLoss;LastM2EnergyLoss=a.model.LastM2EnergyLoss;GoalTicksRemaining=a.model.GoalTicksRemaining;BiasStrength=a.sequence.biasStrength;ExplorationSigma=a.sequence.explorationSigma;LeftProposalLoss=a.model.LeftProposalLoss;RightProposalLoss=a.model.RightProposalLoss;LeftProposalSamples=a.model.LeftLossSamples;RightProposalSamples=a.model.RightLossSamples;DirectionState=a.model.LatchedDirection<0?"left":a.model.LatchedDirection>0?"right":"neutral";for(int s=0;s<5;s++){LastPredictedPositions[s]=a.sequence.prediction.PositionAt(s);LastPredictedHeadings[s]=a.sequence.prediction.HeadingAt(s);}
            }catch(Exception e){HandleControlFailure(a,e);}
        }
        PlannerMilliseconds=(float)((System.Diagnostics.Stopwatch.GetTimestamp()-started)*1000d/System.Diagnostics.Stopwatch.Frequency);M2TrainingMilliseconds=PlannerMilliseconds;
    }

    private void ApplySequenceAction(NativeAgent a,int step)
    {
        float[] action=a.sequence.ActionAt(step);a.brain.ApplyNativeActions(action,a.sequence.goal,a.sequence.worldGoal,NativeCreatureModel.ActionTicks,Tick);float sum=0f;for(int i=0;i<a.sequence.limbCount;i++)sum+=Mathf.Abs(action[i]);LastActionMagnitude=a.sequence.limbCount==0?0f:sum/a.sequence.limbCount;
    }
    private static float[] FlattenActions(float[,] actions){float[] result=new float[NativeCreatureModel.PlanningHorizon*NativeCreatureModel.MaxLimbs];for(int s=0;s<NativeCreatureModel.PlanningHorizon;s++)for(int l=0;l<NativeCreatureModel.MaxLimbs;l++)result[s*NativeCreatureModel.MaxLimbs+l]=actions[s,l];return result;}

    private void PrepareTemporaryGoalLocation(NativeAgent a,Rigidbody2D torsoBody)
    {
        if(enableM1||a==null||torsoBody==null||NativeCreatureModel.CanPlaceFixedTrainingGoal(torsoBody.position,Tick))return;
        float destinationX=NativeSpawnPosition(a.reservedSlot).x,deltaX=destinationX-torsoBody.position.x;GameObject root=a.identity!=null&&a.identity.transform.parent!=null?a.identity.transform.parent.gameObject:a.identity?.gameObject;if(root==null)return;foreach(Rigidbody2D part in root.GetComponentsInChildren<Rigidbody2D>(true)){part.position+=Vector2.right*deltaX;part.linearVelocity=Vector2.zero;part.angularVelocity=0f;part.WakeUp();}Physics2D.SyncTransforms();a.model.RelatchFixedTrainingGoal();a.motionWindowStartPosition=torsoBody.position;a.motionWindowTicks=a.movingEvidenceTicks=a.stillEvidenceTicks=0;a.isSustainedMoving=false;TemporaryGoalRecenters++;Status="Temporary goal recentered creature away from world wall";
    }

    private void UpdateSettlingState(){foreach(NativeAgent a in agents){if(a.hasCompletedInitialSettlement)continue;if(a.brain==null||a.brain.IsDead||a.identity?.torso?.Rigidbody==null){a.settledSupportTicks=0;continue;}Rigidbody2D b=a.identity.torso.Rigidbody;bool supported=a.identity.torso.TouchingGround||a.brain.allLimbs.Any(l=>l!=null&&l.TouchingEnvironment),slow=b.linearVelocity.sqrMagnitude<=.01f&&Mathf.Abs(b.angularVelocity)<=5f;a.settledSupportTicks=supported&&slow?Mathf.Min(10,a.settledSupportTicks+1):0;if(a.settledSupportTicks>=10)a.hasCompletedInitialSettlement=true;}}
    private void UpdateGoalProgressDisplays(){foreach(NativeAgent a in agents)if(a.goalVisualizer!=null&&a.identity?.torso!=null&&a.ReadyForLearning)a.goalVisualizer.ReportMovement(a.identity.torso.transform.position);}
    public static bool IsTemporaryGoalReached(Vector2 position,Vector2 goal)=>(position-goal).sqrMagnitude<=TemporaryGoalReachRadius*TemporaryGoalReachRadius;
    private void UpdateTemporaryGoalRewards(){if(enableM1)return;int block=Mathf.Max(0,Tick)/NativeCreatureModel.GoalWindowTicks;foreach(NativeAgent a in agents){if(a.temporaryGoalRewardBlock==block||a.observation==null||a.identity?.torso==null||a.brain==null||a.brain.IsDead)continue;if(!IsTemporaryGoalReached(a.identity.torso.Rigidbody.position,a.model.CurrentWorldGoal))continue;a.identity.torso.AddEnergy(TemporaryGoalRewardEnergy);a.temporaryGoalRewardBlock=block;Status="Temporary goal reached: +"+TemporaryGoalRewardEnergy.ToString("F0")+" energy";}}
    private void UpdateEnergyBarDisplays(){foreach(NativeAgent a in agents)if(a.energyBar!=null&&a.identity?.torso!=null)a.energyBar.Refresh(Tick);}
    private void UpdateMotionEvidence(){foreach(NativeAgent a in agents){if(a.brain==null||a.brain.IsDead||a.identity?.torso?.Rigidbody==null){a.movingEvidenceTicks=a.stillEvidenceTicks=a.motionWindowTicks=0;a.isSustainedMoving=false;continue;}if(a.motionWindowTicks<=0)a.motionWindowStartPosition=a.identity.torso.Rigidbody.position;a.motionWindowTicks++;if(a.motionWindowTicks<10)continue;float speed=(a.identity.torso.Rigidbody.position-a.motionWindowStartPosition).magnitude/Mathf.Max(.0001f,a.motionWindowTicks*Time.fixedDeltaTime);a.motionWindowStartPosition=a.identity.torso.Rigidbody.position;a.motionWindowTicks=0;if(a.isSustainedMoving){a.stillEvidenceTicks=speed<=.025f?a.stillEvidenceTicks+1:0;if(a.stillEvidenceTicks>=2)a.isSustainedMoving=false;}else{a.movingEvidenceTicks=speed>=.08f?a.movingEvidenceTicks+1:0;if(a.movingEvidenceTicks>=2)a.isSustainedMoving=true;}}}
    private void LateUpdate(){if(PopulationDynamicsEnabled)MaintainPopulationInvariant();foreach(NativeAgent a in agents.ToArray()){if(a.identity?.torso==null||a.brain==null)continue;float energy=a.identity.torso.energy;a.m1EnergyFitness+=energy-a.previousEnergy;a.previousEnergy=energy;if(a.brain.IsDead&&!a.deathRecorded){RecordDeathPenalty(a);}}if(Time.time>=nextCheckpoint){nextCheckpoint+=checkpointIntervalSeconds;SaveCheckpoint();}}
    private void HandleControlFailure(NativeAgent a,Exception e){ControlFailures++;LastControlError=a.identity==null?e.Message:a.identity.creatureId+": "+e.Message;Debug.LogError("Native control failed for creature "+LastControlError+"\n"+e);if(a.brain!=null&&!a.brain.IsDead)a.brain.Kill("native_control_error");}
    private void SeedPopulation(){for(int i=agents.Count;i<Mathf.Clamp(populationTarget,1,10);i++)Spawn(CreateSeedBody(i),"body_species_"+(i%InitialBodySpeciesCount),"m1_seed_"+(i%InitialBodySpeciesCount),seedPolicy.Clone(),i);}
    private void MaintainPopulationInvariant(){if(!PopulationDynamicsEnabled)return;populationTarget=Mathf.Max(6,Mathf.Clamp(populationTarget,1,10));if(agents.Count<populationTarget)SeedPopulation();}
    private void ReplaceDeadCreaturesImmediately(){if(!PopulationDynamicsEnabled)return;bool changed=false;foreach(NativeAgent victim in agents.Where(a=>a.brain==null||a.brain.IsDead).ToArray()){if(!agents.Contains(victim))continue;RecordDeathPenalty(victim);try{NativeAgent parent=SelectLivingParent();if(parent==null)RespawnSameGenotype(victim,victim.reservedSlot);else ReplaceAgent(victim,parent,victim.reservedSlot);replacementRetries.Remove(victim);ReplacementRetryState="none";ImmediateReplacementCount++;LastReplacementTick=Tick;changed=true;}catch(Exception e){int retries=replacementRetries.TryGetValue(victim,out int prior)?prior:0;if(retries==0){replacementRetries[victim]=1;ReplacementRetryState="queued retry for slot "+victim.reservedSlot;Debug.LogError("Native replacement failed once; retry queued: "+e.Message);}else{replacementRetries.Remove(victim);ReplacementRetryState="retry failed for slot "+victim.reservedSlot;}}}if(changed)RebuildSpeciation();}
    private NativeAgent SelectLivingParent(){Dictionary<string,float> fitness=NativeNestedSpeciation.SharedFitness(species);NativeAgent[] eligible=agents.Where(a=>a.brain!=null&&!a.brain.IsDead&&NativeCreatureModel.IsFinite(a.model.BodyFitness)&&!a.protectedOffspring).ToArray();if(eligible.Length==0)return null;NativeAgent best=null;float quality=float.NegativeInfinity;for(int i=0;i<3;i++){NativeAgent c=eligible[random.Next(eligible.Length)];float q=fitness.TryGetValue(c.identity.creatureId,out float value)?value:0f;if(q>quality){best=c;quality=q;}}return best;}
    private void RespawnSameGenotype(NativeAgent victim,int slot){BodyGenomeDto body=JsonConvert.DeserializeObject<BodyGenomeDto>(JsonConvert.SerializeObject(victim.body));NativeBrainWeights weights=victim.model.Weights.Clone();Spawn(body,victim.identity.speciesId,victim.brain.M1SpeciesId,weights,slot,victim.bodyAgeGenerations);RemoveAgentObject(victim);}
    private void ReplaceAgent(NativeAgent victim,NativeAgent parent,int slot)
    {
        BodyGenomeDto child=JsonConvert.DeserializeObject<BodyGenomeDto>(JsonConvert.SerializeObject(parent.body));int age=parent.bodyAgeGenerations+1;bool changed=bodyMutationCooldownGenerations<=0||age>=bodyMutationCooldownGenerations;if(changed){MutateBody(child);age=0;}NativeAgent m1Parent=agents.Where(a=>a.brain!=null&&!a.brain.IsDead&&a.identity.speciesId==parent.identity.speciesId).OrderByDescending(a=>a.m1EnergyFitness).FirstOrDefault()??parent;NativeBrainWeights weights=parent.model.Weights.Clone();Array.Copy(m1Parent.model.Weights.m1Input,weights.m1Input,weights.m1Input.Length);Array.Copy(m1Parent.model.Weights.m1Residual,weights.m1Residual,weights.m1Residual.Length);Array.Copy(m1Parent.model.Weights.m1Output,weights.m1Output,weights.m1Output.Length);Array.Copy(m1Parent.model.Weights.m1Bias,weights.m1Bias,weights.m1Bias.Length);weights.MutateM2(random,parent.model.IsBidirectionallyVerified?.05f:.08f);if(enableM1)weights.MutateM1(random,.04f);Spawn(child,parent.identity.speciesId,parent.brain.M1SpeciesId,weights,slot,age);agents[agents.Count-1].protectedOffspring=changed;RemoveAgentObject(victim);Generation++;
    }
    private void RemoveAgentObject(NativeAgent victim){GameObject root=victim.identity!=null&&victim.identity.transform.parent!=null?victim.identity.transform.parent.gameObject:victim.identity?.gameObject;if(root!=null){root.SetActive(false);Destroy(root);}agents.Remove(victim);}
    private void RecordDeathPenalty(NativeAgent a){if(a==null||a.brain==null||a.deathRecorded)return;float penalty=a.brain.DeathReason=="predator"&&PredatorKillsEnabled?100f:25f;a.deathPenalty+=penalty;a.m1EnergyFitness-=penalty;a.deathRecorded=true;a.sequenceActive=false;a.observation=null;a.sequence=null;}
    private void RecoverFromExtinction(){if(!PopulationDynamicsEnabled)return;foreach(NativeAgent a in agents){GameObject root=a.identity!=null&&a.identity.transform.parent!=null?a.identity.transform.parent.gameObject:a.identity?.gameObject;if(root!=null){root.SetActive(false);Destroy(root);}}agents.Clear();SeedPopulation();RebuildSpeciation();Status="Native ecosystem recovered from extinction";}
    private void Evolve(){if(!PopulationDynamicsEnabled||agents.Count<2)return;NativeAgent parent=SelectLivingParent();if(parent==null)return;NativeAgent victim=agents.Where(a=>a!=parent&&!a.protectedOffspring).OrderByDescending(a=>a.model.BodyFitness).FirstOrDefault();if(victim==null)return;ReplaceAgent(victim,parent,victim.reservedSlot);MaintainPopulationInvariant();RebuildSpeciation();SaveCheckpoint();}

    private static BodyGenomeDto CreateSeedBody(int index)
    {
        var body=new BodyGenomeDto{genome_id=Guid.NewGuid().ToString("N"),limbs=new List<LimbGeneDto>()};int species=Mathf.Abs(index)%InitialBodySpeciesCount;
        if(species==0){body.limbs.Add(NewLimb(1,0,1));body.limbs.Add(NewLimb(2,0,5));body.limbs.Add(NewLimb(3,0,7));body.limbs.Add(NewLimb(4,2,3));body.limbs.Add(NewLimb(5,3,3));body.limbs.Add(NewLimb(6,0,0));}
        else if(species==1){body.limbs.Add(NewLimb(1,0,0));body.limbs.Add(NewLimb(2,0,4));body.limbs.Add(NewLimb(3,0,6));body.limbs.Add(NewLimb(4,1,3));body.limbs.Add(NewLimb(5,2,2));body.limbs.Add(NewLimb(6,3,3));}
        else if(species==2){body.limbs.Add(NewLimb(1,0,5));body.limbs.Add(NewLimb(2,0,7));body.limbs.Add(NewLimb(3,1,2));body.limbs.Add(NewLimb(4,1,3));body.limbs.Add(NewLimb(5,2,2));body.limbs.Add(NewLimb(6,2,3));}
        else if(species==3){int[] slots={0,1,4,5,6,7};for(int i=0;i<slots.Length;i++)body.limbs.Add(NewLimb(i+1,0,slots[i]));}
        else if(species==4){body.limbs.Add(NewLimb(1,0,4));body.limbs.Add(NewLimb(2,1,3));body.limbs.Add(NewLimb(3,2,3));body.limbs.Add(NewLimb(4,0,6));body.limbs.Add(NewLimb(5,4,2));body.limbs.Add(NewLimb(6,5,2));}
        else{body.limbs.Add(NewLimb(1,0,1));body.limbs.Add(NewLimb(2,1,2));body.limbs.Add(NewLimb(3,2,2));body.limbs.Add(NewLimb(4,0,7));body.limbs.Add(NewLimb(5,4,3));body.limbs.Add(NewLimb(6,5,3));}body.Validate();return body;
    }
    private static LimbGeneDto NewLimb(int id,int parent,int slot)=>new LimbGeneDto{innovation_id=id,parent_innovation_id=parent,attachment_slot=slot};
    private void Spawn(BodyGenomeDto body,string speciesId,string m1Species,NativeBrainWeights weights,int slot,int bodyAge=0)
    {
        body.Validate();Vector2 position=NativeSpawnPosition(slot);GameObject root=new GameObject("NativeCreature_"+body.genome_id.Substring(0,8));root.transform.position=position;CreatureIdentity identity=root.AddComponent<CreatureIdentity>();identity.creatureId=Guid.NewGuid().ToString("N");identity.speciesId=speciesId;GameObject torsoObject=new GameObject("Torso");torsoObject.transform.SetParent(root.transform);torsoObject.transform.position=position;torsoObject.AddComponent<Rigidbody2D>();torsoObject.AddComponent<SpriteRenderer>();torsoObject.AddComponent<BoxCollider2D>();Torso torso=torsoObject.AddComponent<Torso>();torso.InitFromGenome(identity,body);identity.torso=torso;identity.bodyGenomeJson=JsonConvert.SerializeObject(body);PlaceConstructedBodyOnGround(root);int layer=CreatureLayerBase+Mathf.Abs(slot)%CreatureLayerCount;SetLayerRecursively(root,layer);for(int other=CreatureLayerBase;other<CreatureLayerBase+CreatureLayerCount;other++)if(other!=layer)Physics2D.IgnoreLayerCollision(layer,other,true);Limb[] limbs=torso.GetAllLimbs().Where(l=>l!=null).Take(NativeCreatureModel.MaxLimbs).ToArray();CreatureBrain brain=torsoObject.AddComponent<CreatureBrain>();brain.Init(torso,limbs.ToList());brain.DeathsEnabled=PopulationDynamicsEnabled;brain.SetNativeMetadata(speciesId,m1Species);NativeGoalVisualizer visual=torsoObject.AddComponent<NativeGoalVisualizer>();visual.Initialize(torso,brain,Color.HSVToRGB(Mathf.Repeat(slot*.173f,1f),.8f,1f));NativeEnergyBar energyBar=torsoObject.AddComponent<NativeEnergyBar>();energyBar.Initialize(torso);var agent=new NativeAgent{identity=identity,brain=brain,limbs=limbs,goalVisualizer=visual,energyBar=energyBar,body=body,model=new NativeCreatureModel(weights,2003+slot),motionWindowStartPosition=torso.Rigidbody.position,previousEnergy=torso.energy,bodyAgeGenerations=Mathf.Max(0,bodyAge),reservedSlot=Mathf.Abs(slot)%NativeSpawnSlots};agents.Add(agent);
    }
    private static void PlaceConstructedBodyOnGround(GameObject root){Physics2D.SyncTransforms();Collider2D[] colliders=root.GetComponentsInChildren<Collider2D>();if(colliders.Length==0)return;float min=colliders.Min(c=>c.bounds.min.y);root.transform.position+=Vector3.up*(WorldLayout.GroundTop+.03f-min);Physics2D.SyncTransforms();}
    private static Vector2 NativeSpawnPosition(int slot)=>new Vector2(-160f+Mathf.Abs(slot)%NativeSpawnSlots*MinimumSpawnSeparation,-2f);
    private static void SetLayerRecursively(GameObject root,int layer){root.layer=layer;foreach(Transform child in root.transform)SetLayerRecursively(child.gameObject,layer);}
    private void MutateBody(BodyGenomeDto body){body.genome_id=Guid.NewGuid().ToString("N");List<LimbGeneDto> enabled=body.limbs.Where(l=>l.enabled).ToList();if(enabled.Count<NativeCreatureModel.MaxLimbs&&random.NextDouble()<.65){var sites=new List<Vector2Int>();AddFreeSites(body,0,BodyMorphologyRules.TorsoSlots,sites);foreach(LimbGeneDto parent in enabled)if(GeneDepth(body,parent.innovation_id)<NativeCreatureModel.MaxPathDepth)AddFreeSites(body,parent.innovation_id,BodyMorphologyRules.LimbSlots,sites);if(sites.Count>0){Vector2Int site=sites[random.Next(sites.Count)];body.limbs.Add(NewLimb(body.limbs.Count==0?1:body.limbs.Max(l=>l.innovation_id)+1,site.x,site.y));}}else if(enabled.Count>4&&random.NextDouble()<.35){LimbGeneDto removable=enabled.Where(l=>!body.limbs.Any(o=>o.enabled&&o.parent_innovation_id==l.innovation_id)).OrderBy(_=>random.Next()).FirstOrDefault();if(removable!=null)removable.enabled=false;}body.Validate();}
    private static void AddFreeSites(BodyGenomeDto body,int parent,IEnumerable<int> slots,List<Vector2Int> output){HashSet<int> used=body.limbs.Where(l=>l.enabled&&l.parent_innovation_id==parent).Select(l=>l.attachment_slot).ToHashSet();foreach(int slot in slots)if(!used.Contains(slot))output.Add(new Vector2Int(parent,slot));}
    private static int GeneDepth(BodyGenomeDto body,int id){int depth=0;while(id!=0){LimbGeneDto gene=body.limbs.FirstOrDefault(l=>l.enabled&&l.innovation_id==id);if(gene==null)return NativeCreatureModel.MaxPathDepth;id=gene.parent_innovation_id;depth++;}return depth;}
    private void RebuildSpeciation(){List<NativeCreatureControllerView> views=agents.Where(a=>a.identity!=null&&a.brain!=null).Select(a=>new NativeCreatureControllerView(a.identity.creatureId,a.identity.speciesId,a.brain.M1SpeciesId,a.body,a.model.Weights,a.model.BodyFitness)).ToList();species=NativeNestedSpeciation.Rebuild(views,species);Dictionary<string,NativeAgent> byId=agents.Where(a=>a.identity!=null).ToDictionary(a=>a.identity.creatureId);foreach(NativeBodySpecies body in species)foreach(NativeBrainSubSpecies sub in body.subSpecies)foreach(NativeCreatureControllerView member in sub.members)if(byId.TryGetValue(member.id,out NativeAgent a)){a.identity.speciesId=body.id;a.brain.SetNativeMetadata(body.id,sub.id);}}

    public void SaveCheckpoint()
    {
        long started=System.Diagnostics.Stopwatch.GetTimestamp();try{if(random==null)random=new System.Random(1337^Generation^controlStep);var checkpoint=new NativeEcosystemCheckpoint{tick=Tick,generation=Generation,controlStep=controlStep,specialistSelectionCursor=specialistSelectionCursor,sharedM3Samples=SharedM3Samples,sharedM3OptimizerSteps=SharedM3OptimizerSteps,experimentId=ExperimentId,randomState=random.Next(),nextEvolutionTicks=(long)(nextEvolution*1000f),sharedM3=sharedM3,m3Optimizer=m3Optimizer,validation=new List<NativeCompletedSequence>(validation)};foreach(NativeAgent a in agents)checkpoint.creatures.Add(new NativeCreatureCheckpoint{creatureId=a.identity.creatureId,speciesId=a.identity.speciesId,m1SpeciesId=a.brain.M1SpeciesId,bodyGenomeJson=JsonConvert.SerializeObject(a.body),brain=a.model.Capture(),bodyFitness=float.IsInfinity(a.model.BodyFitness)?float.MaxValue:a.model.BodyFitness,deathPenalty=a.deathPenalty,m1EnergyFitness=a.m1EnergyFitness,previousEnergy=a.previousEnergy,deathRecorded=a.deathRecorded,bodyAgeGenerations=a.bodyAgeGenerations,protectedOffspring=a.protectedOffspring,temporaryGoalRewardBlock=a.temporaryGoalRewardBlock});Directory.CreateDirectory(Path.GetDirectoryName(checkpointPath));checkpoint.tensorGeneration=DateTime.UtcNow.Ticks.ToString("x16");checkpoint.tensorFile="native_ecosystem_v18."+checkpoint.tensorGeneration+".bin";string tensorPath=Path.Combine(Path.GetDirectoryName(checkpointPath),checkpoint.tensorFile),tensorTemp=tensorPath+".tmp",manifestTemp=checkpointPath+".tmp",backup=checkpointPath+".bak";NativeTensorCheckpointStore.Write(tensorTemp,checkpoint);checkpoint.tensorSha256=NativeTensorCheckpointStore.Sha256(tensorTemp);File.Move(tensorTemp,tensorPath);WriteManifest(manifestTemp,checkpoint);var check=JsonConvert.DeserializeObject<NativeEcosystemCheckpoint>(File.ReadAllText(manifestTemp));if(check==null||check.schema!=18||!NativeEcosystemCheckpoint.IsCompatibleConfiguration(check.configuration)||check.tensorSha256!=NativeTensorCheckpointStore.Sha256(tensorPath))throw new InvalidDataException("Temporary v18 checkpoint failed validation");if(File.Exists(checkpointPath))File.Replace(manifestTemp,checkpointPath,backup,true);else File.Move(manifestTemp,checkpointPath);CleanupUnreferencedTensorGenerations();CheckpointStatus="Saved";LastCheckpointError="";LastCheckpointSavedAt=DateTime.Now.ToString("HH:mm:ss");}catch(Exception e){CheckpointStatus="Save failed";LastCheckpointError=e.Message;Debug.LogError("Native checkpoint save failed: "+e);}finally{CheckpointMilliseconds=(float)((System.Diagnostics.Stopwatch.GetTimestamp()-started)*1000d/System.Diagnostics.Stopwatch.Frequency);}
    }
    private void TryLoad()
    {
        if(!File.Exists(checkpointPath)&&!File.Exists(checkpointPath+".bak"))return;Exception primary=null;foreach(string candidate in new[]{checkpointPath,checkpointPath+".bak"}){if(!File.Exists(candidate))continue;try{LoadCheckpointCandidate(candidate);CheckpointStatus=candidate==checkpointPath?"Loaded":"Recovered backup";LastCheckpointSavedAt=CheckpointStatus;LastCheckpointError=primary?.Message??"";return;}catch(Exception e){if(primary==null)primary=e;else LastCheckpointError=primary.Message+" | backup: "+e.Message;}}CheckpointStatus="Rejected; fresh population";if(string.IsNullOrEmpty(LastCheckpointError))LastCheckpointError=primary?.Message??"No compatible v18 checkpoint";
    }
    private static void WriteManifest(string path,NativeEcosystemCheckpoint checkpoint){string json=JsonConvert.SerializeObject(checkpoint,Formatting.None);using(var stream=new FileStream(path,FileMode.Create,FileAccess.Write,FileShare.None))using(var writer=new StreamWriter(stream)){writer.Write(json);writer.Flush();stream.Flush(true);}}
    private void LoadCheckpointCandidate(string manifestPath){var c=JsonConvert.DeserializeObject<NativeEcosystemCheckpoint>(File.ReadAllText(manifestPath));if(c==null||c.schema!=18||!NativeEcosystemCheckpoint.IsCompatibleConfiguration(c.configuration))throw new InvalidDataException("Native checkpoint schema/configuration mismatch");NativeTensorCheckpointStore.ValidateFileName(c.tensorFile);string tensorPath=Path.Combine(Path.GetDirectoryName(checkpointPath),c.tensorFile);if(!File.Exists(tensorPath)||NativeTensorCheckpointStore.Sha256(tensorPath)!=c.tensorSha256)throw new InvalidDataException("Native checkpoint tensor checksum mismatch");NativeTensorCheckpointStore.Read(tensorPath,c);sharedM3=c.sharedM3;m3Optimizer=c.m3Optimizer??new NativeOptimizerState();SharedM3Samples=c.sharedM3Samples;SharedM3OptimizerSteps=c.sharedM3OptimizerSteps;ExperimentId=string.IsNullOrWhiteSpace(c.experimentId)?ExperimentId:c.experimentId;Tick=c.tick;Generation=c.generation;controlStep=c.controlStep;specialistSelectionCursor=c.specialistSelectionCursor;random=new System.Random(unchecked((int)c.randomState));validation.Clear();if(c.validation!=null)validation.AddRange(c.validation.TakeLast(ValidationCapacity));foreach(NativeCreatureCheckpoint saved in c.creatures.Take(Mathf.Clamp(populationTarget,1,10))){BodyGenomeDto body=JsonConvert.DeserializeObject<BodyGenomeDto>(saved.bodyGenomeJson);Spawn(body,saved.speciesId,saved.m1SpeciesId,saved.brain?.weights??seedPolicy.Clone(),agents.Count,saved.bodyAgeGenerations);NativeAgent a=agents[agents.Count-1];a.model.Restore(saved.brain);a.identity.creatureId=saved.creatureId;a.deathPenalty=saved.deathPenalty;a.m1EnergyFitness=saved.m1EnergyFitness;a.previousEnergy=saved.previousEnergy;a.deathRecorded=saved.deathRecorded;a.protectedOffspring=saved.protectedOffspring;a.temporaryGoalRewardBlock=saved.temporaryGoalRewardBlock;}}
    private void CleanupUnreferencedTensorGenerations(){string directory=Path.GetDirectoryName(checkpointPath);var keep=new HashSet<string>(StringComparer.OrdinalIgnoreCase);foreach(string manifest in new[]{checkpointPath,checkpointPath+".bak"})try{if(!File.Exists(manifest))continue;var c=JsonConvert.DeserializeObject<NativeEcosystemCheckpoint>(File.ReadAllText(manifest));if(c!=null&&!string.IsNullOrWhiteSpace(c.tensorFile))keep.Add(c.tensorFile);}catch{}foreach(string file in Directory.GetFiles(directory,"native_ecosystem_v18.*.bin")){string name=Path.GetFileName(file);if(!keep.Contains(name))try{File.Delete(file);}catch(Exception e){Debug.LogWarning("Could not clean unreferenced tensor generation "+name+": "+e.Message);}}}
    private void OnApplicationQuit()=>SaveCheckpoint(); private void OnDestroy(){if(Application.isPlaying)SaveCheckpoint();}
}

public enum NativeGoalMovement{Still,Toward,Away}
public sealed class NativeGoalVisualizer:MonoBehaviour
{
    public const float MovementThreshold=.05f,MaximumDisplayDistance=4f;private Torso torso;private CreatureBrain brain;private GameObject root;private Transform marker;private LineRenderer line;private TextMesh label,movement;private Material material;private Color color;private Vector2 goal,displayGoal,baseline;private bool hasGoal,hasBaseline;
    public void Initialize(Torso t,CreatureBrain b,Color c){torso=t;brain=b;color=c;Ensure();Refresh();}
    private void LateUpdate(){if(torso==null||brain==null)return;Ensure();Refresh();if(hasGoal&&root.activeSelf){UpdateDisplayCue();line.SetPosition(0,torso.transform.position);line.SetPosition(1,displayGoal);}}
    private void Ensure(){if(marker!=null)return;root=new GameObject("NativeGoalVisual");root.SetActive(false);GameObject m=new GameObject("NativeGoalMarker");m.transform.SetParent(root.transform,false);var sr=m.AddComponent<SpriteRenderer>();sr.sprite=BodyUtils.GetSquareSprite();sr.color=new Color(color.r,color.g,color.b,.72f);sr.sortingOrder=-10;m.transform.localScale=new Vector3(.22f,.22f,1f);marker=m.transform;GameObject l=new GameObject("NativeGoalLine");l.transform.SetParent(root.transform,false);line=l.AddComponent<LineRenderer>();line.positionCount=2;line.useWorldSpace=true;line.startWidth=.025f;line.endWidth=.012f;line.sortingOrder=-11;material=new Material(Shader.Find("Sprites/Default"));material.color=color;line.sharedMaterial=material;label=MakeText("NativeGoalCoordinates",-9);movement=MakeText("NativeGoalMovement",-8);movement.text="MEASURING";}
    private TextMesh MakeText(string n,int order){GameObject o=new GameObject(n);o.transform.SetParent(root.transform,false);TextMesh t=o.AddComponent<TextMesh>();t.anchor=TextAnchor.MiddleCenter;t.alignment=TextAlignment.Center;t.fontSize=48;t.characterSize=.08f;t.fontStyle=FontStyle.Bold;t.color=Color.white;t.GetComponent<MeshRenderer>().sortingOrder=order;return t;}
    private void Refresh(){if(!brain.HasWorldGoal){if(root.activeSelf)root.SetActive(false);return;}if(hasGoal&&(brain.CurrentWorldGoal-goal).sqrMagnitude<=1e-6f)return;goal=brain.CurrentWorldGoal;hasGoal=true;hasBaseline=false;root.SetActive(true);UpdateDisplayCue();}
    private void UpdateDisplayCue(){Vector2 origin=torso.transform.position;displayGoal=DisplayTarget(origin,goal);marker.position=goal;label.text=$"G ({goal.x:F2}, {goal.y:F2})";label.transform.position=goal+Vector2.up*.4f;movement.transform.position=goal+Vector2.up;}
    public void ReportMovement(Vector2 current){Ensure();Refresh();if(!brain.HasWorldGoal)return;if(!hasBaseline){baseline=current;hasBaseline=true;movement.text="MEASURING";movement.color=Color.white;return;}Vector2 toward=goal-baseline;float p=toward.sqrMagnitude<=1e-6f?0f:Vector2.Dot(current-baseline,toward.normalized);baseline=current;NativeGoalMovement s=ClassifyProgress(p);movement.text=s==NativeGoalMovement.Toward?$"TOWARD +{p:F2}":s==NativeGoalMovement.Away?$"AWAY {p:F2}":$"STILL {p:+0.00;-0.00;0.00}";movement.color=MovementColor(s);}
    public static NativeGoalMovement ClassifyProgress(float p)=>p>MovementThreshold?NativeGoalMovement.Toward:p<-MovementThreshold?NativeGoalMovement.Away:NativeGoalMovement.Still;
    public static Color MovementColor(NativeGoalMovement movement)=>movement==NativeGoalMovement.Toward?new Color(.2f,1f,.3f):movement==NativeGoalMovement.Away?new Color(1f,.22f,.22f):new Color(1f,.85f,.2f);
    public static Vector2 DisplayTarget(Vector2 origin,Vector2 actualGoal){Vector2 offset=actualGoal-origin;return offset.sqrMagnitude<=MaximumDisplayDistance*MaximumDisplayDistance?actualGoal:origin+offset.normalized*MaximumDisplayDistance;}
    private void OnDestroy(){if(material!=null){if(Application.isPlaying)Destroy(material);else DestroyImmediate(material);}if(root!=null){if(Application.isPlaying)Destroy(root);else DestroyImmediate(root);}}
}

public sealed class NativeEnergyBar:MonoBehaviour
{
    public const int RefreshIntervalTicks=50;private Torso torso;private GameObject root;private Transform fill;private SpriteRenderer fillRenderer;private float width;public int LastRefreshTick{get;private set;}=-1;
    public void Initialize(Torso value){torso=value;Ensure();Refresh();}
    public void Refresh(int tick){Refresh();LastRefreshTick=tick;}
    public void Refresh(){if(torso==null)return;Ensure();float fraction=EnergyFraction(torso.energy,torso.maxEnergy);float height=.12f;root.transform.position=(Vector2)torso.transform.position+Vector2.up*(Mathf.Max(.25f,torso.dimensions.y*.5f)+.38f);fill.localScale=new Vector3(width*fraction,height,1f);fill.localPosition=new Vector3(-width*.5f+width*fraction*.5f,0f,-.01f);fillRenderer.color=EnergyColor(fraction);}
    public static float EnergyFraction(float energy,float maximum)=>maximum<=0f?0f:Mathf.Clamp01(energy/maximum);
    public static Color EnergyColor(float fraction)=>Color.Lerp(new Color(1f,.2f,.2f),new Color(.2f,1f,.3f),Mathf.Clamp01(fraction));
    private void Ensure(){if(root!=null)return;width=Mathf.Max(.8f,torso.dimensions.x*1.8f);root=new GameObject("NativeEnergyBarVisual");GameObject foreground=new GameObject("Fill");foreground.transform.SetParent(root.transform,false);fill=foreground.transform;fillRenderer=foreground.AddComponent<SpriteRenderer>();fillRenderer.sprite=BodyUtils.GetSquareSprite();fillRenderer.sortingOrder=21;}
    private void OnDestroy(){if(root!=null){if(Application.isPlaying)Destroy(root);else DestroyImmediate(root);}}
}
