using System;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Newtonsoft.Json;
using UnityEngine;

[DefaultExecutionOrder(-80)]
[DisallowMultipleComponent]
public sealed class NativeEcosystemController : MonoBehaviour
{
    private const float MinimumSpawnSeparation=32f,TrainingLaneLength=24f,TrainingLaneHalfLength=12f,TrainingLaneThickness=1f,TrainingGoalRadius=.5f,TrainingTimeoutSeconds=60f; public const float TemporaryGoalRewardEnergy=100f,TemporaryGoalReachRadius=1.25f; public const int InitialBodySpeciesCount=6; private const int CreatureLayerBase=8,CreatureLayerCount=10,NativeSpawnSlots=10,ValidationCapacity=64;
    public int populationTarget=10;
    [SerializeField] private bool enableM1=false;
    public int controlIntervalTicks=NativeCreatureModel.ActionTicks;
    public float evolutionIntervalSeconds=75f,checkpointIntervalSeconds=30f;
    public bool allowForcedEvolution=true,loadCheckpointOnStart=true;
    public int bodyMutationCooldownGenerations=12;
    public string checkpointFileName="native_ecosystem_v21.json";
    public string Status{get;private set;}="Starting native ecosystem";
    public int Tick{get;private set;} public int Generation{get;private set;} public int Population=>agents.Count; public int SpeciesCount=>agents.Where(a=>a.identity!=null).Select(a=>a.identity.speciesId).Distinct().Count();
    public float LastM3Loss{get;private set;} public float LastM3Mse{get;private set;} public float LastM3RelativeLoss{get;private set;} public float LastM3VelocityLoss{get;private set;} public float LastM3ContactLoss{get;private set;} public float LastM2Loss{get;private set;} public float LastM2GoalLoss{get;private set;} public float LastM2EnergyLoss{get;private set;}
    public int GoalTicksRemaining{get;private set;} public int SequenceStep{get;private set;} public int SharedM3Samples{get;private set;} public int FreshSequenceSamples{get;private set;}public int SharedM3OptimizerSteps{get;private set;} public int SharedM3Updates=>SharedM3OptimizerSteps; public int LastM3BatchSize{get;private set;} public int TemporaryGoalRecenters{get;private set;} public float BiasStrength{get;private set;} public float ExplorationSigma{get;private set;} public int GoalSuccesses{get;private set;} public int GoalFailures{get;private set;} public string CurriculumTelemetry{get;private set;}="initializing";
    public float PlannerMilliseconds{get;private set;} public float M2TrainingMilliseconds{get;private set;} public float M3TrainingMilliseconds{get;private set;} public float CheckpointMilliseconds{get;private set;} public int M2TrainingUpdates{get;private set;} public float LastActionMagnitude{get;private set;}
    public float LeftProposalLoss{get;private set;}=float.PositiveInfinity; public float RightProposalLoss{get;private set;}=float.PositiveInfinity; public int LeftProposalSamples{get;private set;} public int RightProposalSamples{get;private set;} public string DirectionState{get;private set;}="neutral";
    public Vector2[] LastPredictedPositions{get;private set;}=new Vector2[5]; public Vector2[] LastActualPositions{get;private set;}=new Vector2[5]; public Vector2[] LastPredictedHeadings{get;private set;}=new Vector2[5]; public Vector2[] LastActualHeadings{get;private set;}=new Vector2[5];
    public float MeanM1EnergyFitness=>agents.Count==0?0f:agents.Average(a=>a.m1EnergyFitness); public float RenderRateHz{get;private set;} public string PhysicsMode=>Physics2D.simulationMode.ToString(); public float PhysicsRateHz=>1f/Time.fixedDeltaTime;
    public string CheckpointStatus{get;private set;}="Not saved"; public string LastCheckpointError{get;private set;}=""; public float SecondsUntilCheckpoint=>Mathf.Max(0f,nextCheckpoint-Time.time); public string LastCheckpointSavedAt{get;private set;}="Never";
    public int ActiveControlCount=>agents.Count(a=>a.sequenceActive); public int DeadCreatureCount=>agents.Count(a=>a.brain==null||a.brain.IsDead); public int SettlingCreatureCount=>agents.Count(a=>a.brain!=null&&!a.brain.IsDead&&!a.ReadyForLearning); public int MovingCreatureCount=>agents.Count(a=>a.isSustainedMoving);
    public float MeanRootSpeed=>agents.Where(a=>a.identity?.torso?.Rigidbody!=null&&a.brain!=null&&!a.brain.IsDead).Select(a=>a.identity.torso.Rigidbody.linearVelocity.magnitude).DefaultIfEmpty().Average(); public float MeanJointSpeed=>agents.Where(a=>a.brain!=null&&!a.brain.IsDead).Select(a=>a.brain.MeanJointSpeed).DefaultIfEmpty().Average();
    public int ControlFailures{get;private set;} public string LastControlError{get;private set;}=""; public int ImmediateReplacementCount{get;private set;} public int LastReplacementTick{get;private set;}=-1; public string ReplacementRetryState{get;private set;}="none"; public float PopulationTurns=>Generation/6f; public string ExperimentId{get;private set;}
    public bool M1Enabled=>enableM1; public string M1ActivationSource{get;private set;}="not initialized"; public bool LoadedFromCheckpoint{get;private set;}
    public bool PopulationDynamicsEnabled{get;private set;}
    public bool PredatorKillsEnabled=>PopulationDynamicsEnabled;
    public bool InteractiveFeaturesEnabled=>PopulationDynamicsEnabled&&enableM1&&environmentSpawner!=null&&environmentSpawner.FeaturesEnabled;
    public int ReplayCount=>learner?.ReplayCount??loadedReplay.Count;public int LearnerQueueDepth=>learner?.QueueDepth??0;public int LearnerQueueDrops=>learner?.Dropped??learnerQueueDrops;public bool LearnerBusy=>learner!=null&&learner.Busy;public bool M2WarmupComplete=>FreshSequenceSamples>=NativeContinualLearner.M3WarmupFreshSequences;public int SnapshotAgeTicks=>Mathf.Max(0,Tick-lastLearnerResultTick);public float FrameP95Milliseconds{get;private set;}public int PracticeCreatureCount=>agents.Count(a=>a.practiceActive);

    private sealed class NativeAgent
    {
        public CreatureIdentity identity; public CreatureBrain brain; public BodyGenomeDto body; public NativeCreatureModel model; public Limb[] limbs; public NativeGoalVisualizer goalVisualizer; public NativeEnergyBar energyBar;public RtNeatGoalGenome m1Genome;public RtNeatGoalPhenotype m1Phenotype;public string bodySignature;public bool practiceActive;public int practiceBlock=int.MinValue;public readonly float[] m1Output=new float[4],practiceOutput=new float[4];
        public float deathPenalty,m1EnergyFitness,previousEnergy; public bool deathRecorded,protectedOffspring,hasCompletedInitialSettlement,sequenceActive,isSustainedMoving; public int bodyAgeGenerations,reservedSlot,settledSupportTicks,nextFiniteCheckTick,sequenceStartTick,movingEvidenceTicks,stillEvidenceTicks,motionWindowTicks,temporaryGoalRewardBlock=int.MinValue,trialStage,trialStartedTick,trialEpisode,trialSettlingTicks; public Vector2 motionWindowStartPosition,sequenceStartPosition,trialStart,trialGoal,trialDirection,trialNormal; public float sequenceStartRotation,trialDistance; public NativeObservation observation; public NativeActionSequence sequence; public readonly float[] actualPoses=new float[NativeCreatureModel.M3OutputSize]; public readonly float[] actualAuxiliary=new float[NativeCreatureModel.M3AuxiliaryOutputSize]; public readonly float[] globalInputs=new float[28]; public NativeCurriculumState curriculum=new NativeCurriculumState(); public List<NativeBodyResetPose> resetPose=new List<NativeBodyResetPose>(); public GameObject lane; public bool ReadyForLearning=>hasCompletedInitialSettlement;
    }
    private sealed class NativeBodyResetPose { public Rigidbody2D body; public Vector2 localOffset; public float rotationOffset; }
    private readonly List<NativeAgent> agents=new List<NativeAgent>(); private readonly Dictionary<NativeAgent,int> replacementRetries=new Dictionary<NativeAgent,int>(); private readonly List<NativeCompletedSequence> validation=new List<NativeCompletedSequence>(); private List<NativeBodySpecies> species=new List<NativeBodySpecies>();
    private NativeBrainWeights seedPolicy; private NativeDynamicsWeights sharedM3; private NativeOptimizerState m3Optimizer=new NativeOptimizerState();private NativeSynapticIntelligence m3Protection=new NativeSynapticIntelligence();private NativeReplayBuffer loadedReplay=new NativeReplayBuffer();private NativeRtNeatGoalPolicy rtNeat=new NativeRtNeatGoalPolicy();private NativeContinualLearner learner;private readonly ConcurrentDictionary<string,NativeCreatureModel> modelsById=new ConcurrentDictionary<string,NativeCreatureModel>();private System.Random random; private float nextEvolution,nextCheckpoint,rateWindowStarted; private int framesAtRateWindow,controlStep,specialistSelectionCursor,m1ActivationTick,lastLearnerResultTick,learnerQueueDrops; private string checkpointPath; private Predator cachedPredator; private EnvironmentSpawner environmentSpawner;private Task saveTask;private readonly float[] frameTimes=new float[300];private int frameTimeCount,frameTimeCursor;private GameObject trainingLaneRoot,ecosystemGround;

    private void Awake()
    {
        enableM1=false;M1ActivationSource="locked at startup";Application.runInBackground=true;Time.fixedDeltaTime=.02f;Physics2D.simulationMode=SimulationMode2D.FixedUpdate;populationTarget=10;controlIntervalTicks=NativeCreatureModel.ActionTicks;checkpointFileName="native_ecosystem_v21.json";random=new System.Random(1337);seedPolicy=NativeBrainWeights.Create(1337);sharedM3=NativeDynamicsWeights.Create(7331);ExperimentId="curriculum-v21-"+DateTime.UtcNow.ToString("yyyyMMdd-HHmmss");
        string persistent=Application.persistentDataPath;checkpointPath=Path.Combine(persistent,checkpointFileName);environmentSpawner=GetComponent<EnvironmentSpawner>();if(environmentSpawner!=null)environmentSpawner.LockFeaturesUntilExplicitEnable();if(loadCheckpointOnStart)TryLoad();learner=new NativeContinualLearner(sharedM3,m3Optimizer,m3Protection,loadedReplay,id=>modelsById.TryGetValue(id,out NativeCreatureModel model)?model:null);
    }
    private void Start(){EnsureTrainingArena();SeedPopulation();RebuildSpeciation();nextEvolution=Time.time+evolutionIntervalSeconds;nextCheckpoint=Time.time+checkpointIntervalSeconds;Status="Native success-gated locomotion curriculum running";}
    public void EnableInteractiveFeaturesFromUser(){if(PopulationDynamicsEnabled)return;EndTrainingArena();if(environmentSpawner==null)environmentSpawner=FindAnyObjectByType<EnvironmentSpawner>();if(environmentSpawner!=null)environmentSpawner.EnableFeatures();Physics2D.SyncTransforms();foreach(NativeAgent a in agents){a.sequenceActive=false;a.observation=null;a.sequence=null;a.model.ClearCurriculumGoal();ResetToEcosystemSpawn(a);}PopulationDynamicsEnabled=true;foreach(NativeAgent a in agents)if(a.brain!=null)a.brain.DeathsEnabled=true;enableM1=true;m1ActivationTick=Tick;M1ActivationSource="telemetry button at tick "+Tick;Status="Food, predators, rtNEAT M1, births, and deaths enabled";}
    private void Update(){frameTimes[frameTimeCursor++%frameTimes.Length]=Time.unscaledDeltaTime*1000f;frameTimeCount=Mathf.Min(frameTimes.Length,frameTimeCount+1);if(rateWindowStarted<=0f){rateWindowStarted=Time.unscaledTime;framesAtRateWindow=Time.frameCount;return;}float elapsed=Time.unscaledTime-rateWindowStarted;if(elapsed>=.5f){RenderRateHz=(Time.frameCount-framesAtRateWindow)/elapsed;float[] ordered=new float[frameTimeCount];Array.Copy(frameTimes,ordered,frameTimeCount);Array.Sort(ordered);FrameP95Milliseconds=ordered[Mathf.Clamp(Mathf.CeilToInt(frameTimeCount*.95f)-1,0,frameTimeCount-1)];framesAtRateWindow=Time.frameCount;rateWindowStarted=Time.unscaledTime;}}

    private void FixedUpdate()
    {
        if(Physics2D.simulationMode!=SimulationMode2D.FixedUpdate)Physics2D.simulationMode=SimulationMode2D.FixedUpdate;Tick++;DrainLearnerResults();UpdateSettlingState();AdvanceOpenSequences();TrainCompletedSequences();PlanReadyAgents();
        foreach(NativeAgent a in agents.ToArray()){if(a.brain==null||a.identity?.torso==null)continue;a.identity.torso.EnergyPenaltyScale=Generation<NativeCreatureModel.FixedGoalGenerations?.1f:1f;a.brain.FixedStep();}
        if(enableM1)UpdateTemporaryGoalRewards();else UpdateCurriculumTrials();if(Tick%NativeEnergyBar.RefreshIntervalTicks==0)UpdateEnergyBarDisplays();UpdateMotionEvidence();if(Tick%50==0)UpdateGoalProgressDisplays();if(PopulationDynamicsEnabled){ReplaceDeadCreaturesImmediately();if(agents.Count>0&&agents.All(a=>a.brain==null||a.brain.IsDead))RecoverFromExtinction();if(allowForcedEvolution&&Time.time>=nextEvolution){nextEvolution+=evolutionIntervalSeconds;Evolve();}MaintainPopulationInvariant();}
    }

    private void AdvanceOpenSequences()
    {
        SequenceStep=0;
        foreach(NativeAgent a in agents)
        {
            if(!a.sequenceActive||a.brain==null||a.brain.IsDead||a.identity?.torso==null)continue;int elapsed=Tick-a.sequenceStartTick;if(elapsed<=0||elapsed%NativeCreatureModel.ActionTicks!=0)continue;int reached=elapsed/NativeCreatureModel.ActionTicks-1;if(reached<0||reached>=5)continue;
            Vector2 worldDelta=(Vector2)a.identity.torso.Rigidbody.position-a.sequenceStartPosition;Vector2 local=Quaternion.Euler(0f,0f,-a.sequenceStartRotation)*worldDelta;Vector2 heading=NativeCreatureModel.HeadingEncoding(a.identity.torso.Rigidbody.rotation-a.sequenceStartRotation);int pose=reached*NativeCreatureModel.PoseValueCount;a.actualPoses[pose]=local.x;a.actualPoses[pose+1]=local.y;a.actualPoses[pose+2]=heading.x;a.actualPoses[pose+3]=heading.y;int aux=reached*NativeCreatureModel.AuxiliaryValueCount;Vector2 velocity=Quaternion.Euler(0f,0f,-a.sequenceStartRotation)*a.identity.torso.Rigidbody.linearVelocity;a.actualAuxiliary[aux]=Mathf.Clamp(velocity.x/NativeCreatureModel.M3VelocityScale,-1f,1f);a.actualAuxiliary[aux+1]=Mathf.Clamp(velocity.y/NativeCreatureModel.M3VelocityScale,-1f,1f);int limbCount=Mathf.Max(1,a.limbs.Length);a.actualAuxiliary[aux+2]=a.limbs.Count(l=>l!=null&&l.TouchingEnvironment)/(float)limbCount;a.actualAuxiliary[aux+3]=a.limbs.Count(l=>l!=null&&l.TouchingSelf)/(float)limbCount;a.actualAuxiliary[aux+4]=a.limbs.Count(l=>l!=null&&l.TouchingOtherCreature)/(float)limbCount;LastActualPositions[reached]=local;LastActualHeadings[reached]=heading;a.model.RecordMeasuredProgress(worldDelta);SequenceStep=reached+1;
            int next=reached+1;if(next<5)ApplySequenceAction(a,next);else a.sequenceActive=false;
        }
    }

    private void TrainCompletedSequences()
    {
        NativeAgent[] completed=agents.Where(a=>a.observation!=null&&a.sequence!=null&&!a.sequenceActive&&a.observation.episode==a.trialEpisode&&a.brain!=null&&!a.brain.IsDead).OrderBy(a=>a.identity.creatureId,StringComparer.Ordinal).ToArray();LastM3BatchSize=completed.Length;if(completed.Length==0)return;foreach(NativeAgent a in completed){var sample=new NativeCompletedSequence{sampleId=a.identity.creatureId+":"+a.observation.tick,controllerId=a.identity.creatureId,bodySignature=a.bodySignature,observation=a.observation,actions=FlattenActions(a.sequence.actions),actualPoses=(float[])a.actualPoses.Clone(),actualAuxiliary=(float[])a.actualAuxiliary.Clone()};validation.Add(sample.Clone());if(validation.Count>ValidationCapacity)validation.RemoveAt(0);if(learner==null||!learner.Enqueue(sample)){learnerQueueDrops++;LastControlError="Continual learner queue full; fresh sequence dropped";}a.observation=null;a.sequence=null;}
    }

    private void PlanReadyAgents()
    {
        long started=System.Diagnostics.Stopwatch.GetTimestamp();M2TrainingUpdates=0;if(agents.Count==0)return;int count=agents.Count;
        for(int attempt=0;attempt<count;attempt++)
        {
            NativeAgent a=agents[specialistSelectionCursor++%count];
            if(a.brain==null||a.brain.IsDead||a.identity?.torso==null||!a.ReadyForLearning||a.sequenceActive||(!enableM1&&a.trialSettlingTicks<10))continue;
            try
            {
                if(Tick>=a.nextFiniteCheckTick&&!a.model.Weights.IsFinite()){a.model.RepairFrom(seedPolicy);ControlFailures++;LastControlError=a.identity.creatureId+": repaired non-finite weights";}a.nextFiniteCheckTick=Tick+375;
                Rigidbody2D body=a.identity.torso.Rigidbody;if(!enableM1&&a.curriculum.mode==NativeTrialMode.Settling)StartCurriculumTrial(a);a.identity.torso.FillNativeGlobalInputs(a.globalInputs);var proprio=new NativeLocalProprioception{worldPosition=body.position,worldRotationDegrees=body.rotation,localLinearVelocity=Quaternion.Euler(0f,0f,-body.rotation)*body.linearVelocity};PrepareM1Output(a);
                float[] terrain=SampleTerrain(body);a.observation=a.model.Observe(a.globalInputs,a.limbs,Tick,proprio,enableM1,a.m1Output,a.practiceActive,a.identity.creatureId,a.bodySignature,terrain);a.observation.episode=a.trialEpisode;sharedM3=learner?.SharedM3??sharedM3;float? bias=enableM1?null:a.curriculum.Assistance;bool evaluation=!enableM1&&(a.curriculum.mode==NativeTrialMode.Qualification||a.curriculum.mode==NativeTrialMode.Retention);float? noise=enableM1?null:(evaluation?0f:NativeCreatureModel.ExplorationSigma(FreshSequenceSamples));NativeBrainWeights weightsOverride=!enableM1&&a.curriculum.mode==NativeTrialMode.Qualification?a.curriculum.qualificationSnapshot:(!enableM1&&a.curriculum.mode==NativeTrialMode.Retention&&a.curriculum.retentionUsingSnapshot?a.curriculum.validatedSnapshot:null);a.sequence=a.model.Plan(a.observation,sharedM3,FreshSequenceSamples,bias,noise,weightsOverride);a.sequenceStartTick=Tick;a.sequenceStartPosition=body.position;a.sequenceStartRotation=body.rotation;Array.Clear(a.actualPoses,0,a.actualPoses.Length);Array.Clear(a.actualAuxiliary,0,a.actualAuxiliary.Length);a.sequenceActive=true;ApplySequenceAction(a,0);M2TrainingUpdates++;
                LastM2Loss=a.model.LastM2Loss;LastM2GoalLoss=a.model.LastM2GoalLoss;LastM2EnergyLoss=a.model.LastM2EnergyLoss;GoalTicksRemaining=a.model.GoalTicksRemaining;BiasStrength=a.sequence.biasStrength;ExplorationSigma=a.sequence.explorationSigma;LeftProposalLoss=a.model.LeftProposalLoss;RightProposalLoss=a.model.RightProposalLoss;LeftProposalSamples=a.model.LeftLossSamples;RightProposalSamples=a.model.RightLossSamples;DirectionState=a.model.LatchedDirection<0?"left":a.model.LatchedDirection>0?"right":"neutral";for(int s=0;s<5;s++){LastPredictedPositions[s]=a.sequence.prediction.PositionAt(s);LastPredictedHeadings[s]=a.sequence.prediction.HeadingAt(s);}
                break;
            }catch(Exception e){HandleControlFailure(a,e);break;}
        }
        PlannerMilliseconds=(float)((System.Diagnostics.Stopwatch.GetTimestamp()-started)*1000d/System.Diagnostics.Stopwatch.Frequency);
    }

    private void DrainLearnerResults(){while(learner!=null&&learner.TryResult(out NativeTrainingResult result)){lastLearnerResultTick=Tick;M2TrainingMilliseconds=result.milliseconds;if(!string.IsNullOrEmpty(result.error)){ControlFailures++;LastControlError=result.error;continue;}if(result.m2!=null){LastM2Loss=result.m2.loss;LastM2GoalLoss=result.m2.goalLoss;LastM2EnergyLoss=result.m2.energyLoss;}if(result.m3!=null){LastM3Loss=result.m3.loss;LastM3Mse=result.m3.poseMse;LastM3RelativeLoss=result.m3.relativeLoss;LastM3VelocityLoss=result.m3.velocityLoss;LastM3ContactLoss=result.m3.contactLoss;LastM3BatchSize=result.m3.sampleCount;SharedM3Samples+=result.m3.sampleCount;FreshSequenceSamples++;SharedM3OptimizerSteps=result.m3.optimizerSteps;M3TrainingMilliseconds=result.milliseconds;}}}

    private void PrepareM1Output(NativeAgent a)
    {
        if(!enableM1){a.practiceActive=false;Array.Clear(a.m1Output,0,a.m1Output.Length);return;}int phase=Mathf.Max(0,Tick-m1ActivationTick)%5000;int block=Mathf.Max(0,Tick-m1ActivationTick)/5000;a.practiceActive=phase>=4750;if(a.practiceActive){if(a.practiceBlock!=block){a.practiceBlock=block;float angle=(float)(random.NextDouble()*Math.PI*2d);float magnitude=.35f+.65f*(float)random.NextDouble();a.practiceOutput[0]=Mathf.Cos(angle)*magnitude;a.practiceOutput[1]=Mathf.Sin(angle)*magnitude;float heading=(float)(random.NextDouble()*Math.PI*2d);a.practiceOutput[2]=Mathf.Sin(heading);a.practiceOutput[3]=Mathf.Cos(heading);}Array.Copy(a.practiceOutput,a.m1Output,4);}else a.m1Phenotype.Evaluate(a.globalInputs,a.m1Output);
    }

    private void ApplySequenceAction(NativeAgent a,int step)
    {
        float[] action=a.sequence.ActionAt(step);a.brain.ApplyNativeActions(action,a.sequence.goal,a.sequence.worldGoal,NativeCreatureModel.ActionTicks,Tick);float sum=0f;for(int i=0;i<a.sequence.limbCount;i++)sum+=Mathf.Abs(action[i]);LastActionMagnitude=a.sequence.limbCount==0?0f:sum/a.sequence.limbCount;
    }
    private static float[] FlattenActions(float[,] actions){float[] result=new float[NativeCreatureModel.PlanningHorizon*NativeCreatureModel.MaxLimbs];for(int s=0;s<NativeCreatureModel.PlanningHorizon;s++)for(int l=0;l<NativeCreatureModel.MaxLimbs;l++)result[s*NativeCreatureModel.MaxLimbs+l]=actions[s,l];return result;}

    private void EnsureTrainingArena()
    {
        if(ecosystemGround==null)ecosystemGround=GameObject.Find("Ground");if(ecosystemGround!=null&&ecosystemGround.activeSelf)ecosystemGround.SetActive(false);if(trainingLaneRoot!=null){trainingLaneRoot.SetActive(true);return;}trainingLaneRoot=new GameObject("NativeTrainingLanes");
        for(int i=0;i<NativeSpawnSlots;i++){GameObject lane=new GameObject("NativeTrainingLane_"+i);lane.transform.SetParent(trainingLaneRoot.transform);lane.transform.position=LaneCenter(i);var renderer=lane.AddComponent<SpriteRenderer>();renderer.sprite=BodyUtils.GetSquareSprite();renderer.color=new Color(.28f,.22f,.16f);lane.transform.localScale=new Vector3(TrainingLaneLength,TrainingLaneThickness,1f);BoxCollider2D collider=lane.AddComponent<BoxCollider2D>();collider.size=Vector2.one;collider.sharedMaterial=NativePhysicsMaterials.Ground;lane.AddComponent<GroundSurface>();}
    }
    private void EndTrainingArena(){if(trainingLaneRoot!=null)trainingLaneRoot.SetActive(false);if(ecosystemGround==null)ecosystemGround=GameObject.Find("Ground");if(ecosystemGround!=null)ecosystemGround.SetActive(true);}
    private static Vector2 LaneCenter(int slot)=>new Vector2((Mathf.Abs(slot)%NativeSpawnSlots-(NativeSpawnSlots-1)*.5f)*MinimumSpawnSeparation,WorldLayout.GroundTop);
    private static Vector2 LaneTangent(float degrees)=>new Vector2(Mathf.Cos(degrees*Mathf.Deg2Rad),Mathf.Sin(degrees*Mathf.Deg2Rad));
    private static Vector2 LaneNormal(float degrees)=>new Vector2(-Mathf.Sin(degrees*Mathf.Deg2Rad),Mathf.Cos(degrees*Mathf.Deg2Rad));
    private void StartCurriculumTrial(NativeAgent a)
    {
        EnsureTrainingArena();if(a.curriculum==null)a.curriculum=new NativeCurriculumState();if(a.curriculum.mode==NativeTrialMode.Settling)NativeSuccessCurriculum.StartNextTrial(a.curriculum);NativeDeterministicRng trialRandom=new NativeDeterministicRng(a.curriculum.randomState==0?(ulong)(7101+a.reservedSlot):a.curriculum.randomState);int stage=NativeSuccessCurriculum.TrialStage(a.curriculum,ref trialRandom);a.curriculum.randomState=trialRandom.State;float perturb=a.curriculum.IsPractice?(trialRandom.NextFloat()*2f-1f):0f;float slope=NativeSuccessCurriculum.SlopeDegrees(stage)+perturb;float distance=NativeSuccessCurriculum.Distance(stage)*(a.curriculum.IsPractice ? (.9f+trialRandom.NextFloat()*.2f) : 1f);int direction=NativeSuccessCurriculum.Direction(stage);float signedSlope=direction>0?slope:-slope;Vector2 tangent=LaneTangent(signedSlope),normal=LaneNormal(signedSlope),heading=tangent*direction;GameObject lane=trainingLaneRoot.transform.GetChild(a.reservedSlot).gameObject;lane.SetActive(true);lane.transform.position=LaneCenter(a.reservedSlot);lane.transform.rotation=Quaternion.Euler(0f,0f,signedSlope);a.lane=lane;a.trialStage=stage;a.trialDistance=distance;a.trialDirection=heading;a.trialNormal=normal;a.trialStart=LaneCenter(a.reservedSlot)-heading*3f+normal*(TrainingLaneThickness*.5f+BodyClearance(a,normal,signedSlope));a.trialGoal=a.trialStart+heading*distance;a.trialStartedTick=Tick;a.trialEpisode++;ResetTrialBody(a,a.trialStart,signedSlope);a.model.SetCurriculumGoal(a.trialGoal,heading,Tick+Mathf.RoundToInt(TrainingTimeoutSeconds/Time.fixedDeltaTime));Status="Curriculum "+NativeSuccessCurriculum.Label(stage)+" "+a.curriculum.mode;
    }
    private void ResetTrialBody(NativeAgent a,Vector2 torsoPosition,float torsoRotation)
    {
        if(a.resetPose==null||a.resetPose.Count==0)CaptureResetPose(a);foreach(NativeBodyResetPose pose in a.resetPose){if(pose.body==null)continue;pose.body.position=torsoPosition+(Vector2)(Quaternion.Euler(0f,0f,torsoRotation)*pose.localOffset);pose.body.rotation=torsoRotation+pose.rotationOffset;pose.body.linearVelocity=Vector2.zero;pose.body.angularVelocity=0f;pose.body.Sleep();}a.brain.ExpireActions();Physics2D.SyncTransforms();foreach(NativeBodyResetPose pose in a.resetPose)pose.body?.WakeUp();a.sequenceActive=false;a.observation=null;a.sequence=null;a.trialSettlingTicks=0;a.motionWindowTicks=a.movingEvidenceTicks=a.stillEvidenceTicks=0;a.isSustainedMoving=false;
    }
    private static void CaptureResetPose(NativeAgent a)
    {
        Rigidbody2D torso=a.identity.torso.Rigidbody;GameObject root=a.identity.transform.parent?.gameObject??a.identity.gameObject;foreach(Rigidbody2D body in root.GetComponentsInChildren<Rigidbody2D>(true))a.resetPose.Add(new NativeBodyResetPose{body=body,localOffset=Quaternion.Euler(0f,0f,-torso.rotation)*(body.position-torso.position),rotationOffset=Mathf.DeltaAngle(torso.rotation,body.rotation)});
    }
    private static float BodyClearance(NativeAgent a,Vector2 normal,float rotation)
    {
        float minimum=0f;foreach(NativeBodyResetPose pose in a.resetPose){if(pose.body==null)continue;float radius=0f;foreach(Collider2D collider in pose.body.GetComponents<Collider2D>())radius=Mathf.Max(radius,collider.bounds.extents.magnitude);Vector2 offset=Quaternion.Euler(0f,0f,rotation)*pose.localOffset;minimum=Mathf.Min(minimum,Vector2.Dot(offset,normal)-radius);}return -minimum+.08f;
    }
    private void ResetToEcosystemSpawn(NativeAgent a){Vector2 target=NativeSpawnPosition(a.reservedSlot);ResetTrialBody(a,target,0f);}
    private float[] SampleTerrain(Rigidbody2D body)
    {
        float[] values=new float[12];Vector2 right=body.transform.right,origin=body.position;for(int i=0;i<3;i++){RaycastHit2D hit=Physics2D.Raycast(origin+right*(i-1),Vector2.down,8f);int o=i*4;if(hit.collider==null)continue;Vector2 local=Quaternion.Euler(0f,0f,-body.rotation)*hit.normal;values[o]=1f;values[o+1]=hit.distance/8f;values[o+2]=local.x;values[o+3]=local.y;}return values;
    }
    private void UpdateCurriculumTrials()
    {
        EnsureTrainingArena();int completed=0;var lines=new List<string>();foreach(NativeAgent a in agents)
        {
            if(a.brain==null||a.identity?.torso==null||a.curriculum==null)continue;if(a.curriculum.Complete)completed++;
            Rigidbody2D body=a.identity.torso.Rigidbody;Vector2 relative=body.position-a.trialStart;float progress=Vector2.Dot(relative,a.trialDirection);float lateral=Mathf.Abs(Vector2.Dot(relative,a.trialNormal));bool support=a.identity.torso.TouchingGround||a.limbs.Any(l=>l!=null&&l.TouchingEnvironment);
            if(a.trialSettlingTicks<10){a.trialSettlingTicks=support&&body.linearVelocity.sqrMagnitude<=.01f&&Mathf.Abs(body.angularVelocity)<=5f?a.trialSettlingTicks+1:0;lines.Add($"{a.reservedSlot}:{NativeSuccessCurriculum.Label(a.trialStage)} settling {a.trialSettlingTicks}/10");continue;}
            bool success=support&&progress>=a.trialDistance-.5f&&(body.position-a.trialGoal).sqrMagnitude<=TrainingGoalRadius*TrainingGoalRadius;bool failed=Tick-a.trialStartedTick>=Mathf.RoundToInt(TrainingTimeoutSeconds/Time.fixedDeltaTime)||Mathf.Abs(Vector2.Dot(relative,a.trialDirection))>TrainingLaneHalfLength||lateral>5f;
            if(success||failed)
            {
                NativeTrialMode prior=a.curriculum.mode;
                if(success){GoalSuccesses++;NativeSuccessCurriculum.RegisterSuccess(a.curriculum,a.model.Weights);if(prior==NativeTrialMode.Training&&a.curriculum.mode==NativeTrialMode.Qualification){a.curriculum.qualificationLearningState=a.model.Capture();a.curriculum.qualificationLearningState.weights=a.curriculum.qualificationSnapshot.Clone();}if(prior==NativeTrialMode.Qualification&&a.curriculum.mode!=NativeTrialMode.Qualification&&a.curriculum.validatedSnapshot!=null)a.curriculum.validatedLearningState=a.curriculum.qualificationLearningState?.Clone();Status="Goal success: "+NativeSuccessCurriculum.Label(a.trialStage);}
                else{GoalFailures++;NativeSuccessCurriculum.RegisterFailure(a.curriculum,a.model.Weights);Status="Goal retry: "+NativeSuccessCurriculum.Label(a.trialStage);}
                bool repeatRetention=prior==NativeTrialMode.Retention&&!success&&!a.curriculum.retentionUsingSnapshot&&a.curriculum.validatedSnapshot!=null;
                if(repeatRetention){a.curriculum.retentionUsingSnapshot=true;Status="Retention comparison: frozen snapshot";}
                else
                {
                    if(prior==NativeTrialMode.Retention&&!success&&a.curriculum.retentionUsingSnapshot&&a.curriculum.validatedLearningState!=null){a.model.Restore(a.curriculum.validatedLearningState.Clone());Status="Retention regression restored validated M2 state";}
                    a.curriculum.retentionUsingSnapshot=false;a.curriculum.retentionStage=-1;
                    if(a.curriculum.mode!=NativeTrialMode.Qualification)a.curriculum.mode=NativeTrialMode.Settling;
                }
                a.sequenceActive=false;a.observation=null;a.sequence=null;StartCurriculumTrial(a);
            }
            lines.Add($"{a.reservedSlot}:S{a.curriculum.stage+1} {NativeSuccessCurriculum.Label(a.trialStage)} {a.curriculum.mode} q{a.curriculum.qualificationSuccesses}/10 a{a.curriculum.qualificationAttempts}/12 s{a.curriculum.lifetimeSuccesses} p{a.curriculum.practiceSuccesses} f{a.curriculum.failures} b{a.curriculum.Assistance:F2} d{Mathf.Max(0,a.trialDistance-progress):F1}");
        }
        CurriculumTelemetry="Goals "+GoalSuccesses+"/"+GoalFailures+" complete "+completed+"/"+agents.Count+"\n"+string.Join(" | ",lines);
    }

    private void PrepareTemporaryGoalLocation(NativeAgent a,Rigidbody2D torsoBody)
    {
        if(enableM1||a==null||torsoBody==null||NativeCreatureModel.CanPlaceFixedTrainingGoal(torsoBody.position,Tick))return;
        float destinationX=NativeSpawnPosition(a.reservedSlot).x,deltaX=destinationX-torsoBody.position.x;GameObject root=a.identity!=null&&a.identity.transform.parent!=null?a.identity.transform.parent.gameObject:a.identity?.gameObject;if(root==null)return;foreach(Rigidbody2D part in root.GetComponentsInChildren<Rigidbody2D>(true)){part.position+=Vector2.right*deltaX;part.linearVelocity=Vector2.zero;part.angularVelocity=0f;part.WakeUp();}Physics2D.SyncTransforms();a.model.RelatchFixedTrainingGoal();a.motionWindowStartPosition=torsoBody.position;a.motionWindowTicks=a.movingEvidenceTicks=a.stillEvidenceTicks=0;a.isSustainedMoving=false;TemporaryGoalRecenters++;Status="Temporary goal recentered creature away from world wall";
    }

    private void UpdateSettlingState(){foreach(NativeAgent a in agents){if(a.hasCompletedInitialSettlement)continue;if(a.brain==null||a.brain.IsDead||a.identity?.torso?.Rigidbody==null){a.settledSupportTicks=0;continue;}Rigidbody2D b=a.identity.torso.Rigidbody;bool supported=a.identity.torso.TouchingGround||a.brain.allLimbs.Any(l=>l!=null&&l.TouchingEnvironment),slow=b.linearVelocity.sqrMagnitude<=.01f&&Mathf.Abs(b.angularVelocity)<=5f;a.settledSupportTicks=supported&&slow?Mathf.Min(10,a.settledSupportTicks+1):0;if(a.settledSupportTicks>=10||(supported&&Time.time-a.brain.BornTime>=2f))a.hasCompletedInitialSettlement=true;}}
    private void UpdateGoalProgressDisplays(){foreach(NativeAgent a in agents)if(a.goalVisualizer!=null&&a.identity?.torso!=null&&a.ReadyForLearning)a.goalVisualizer.ReportMovement(a.identity.torso.transform.position);}
    public static bool IsTemporaryGoalReached(Vector2 position,Vector2 goal)=>(position-goal).sqrMagnitude<=TemporaryGoalReachRadius*TemporaryGoalReachRadius;
    private void UpdateTemporaryGoalRewards(){if(enableM1)return;int block=Mathf.Max(0,Tick)/NativeCreatureModel.GoalWindowTicks;foreach(NativeAgent a in agents){if(a.temporaryGoalRewardBlock==block||a.observation==null||a.identity?.torso==null||a.brain==null||a.brain.IsDead)continue;if(!IsTemporaryGoalReached(a.identity.torso.Rigidbody.position,a.model.CurrentWorldGoal))continue;a.identity.torso.AddEnergy(TemporaryGoalRewardEnergy);a.temporaryGoalRewardBlock=block;Status="Temporary goal reached: +"+TemporaryGoalRewardEnergy.ToString("F0")+" energy";}}
    private void UpdateEnergyBarDisplays(){foreach(NativeAgent a in agents)if(a.energyBar!=null&&a.identity?.torso!=null)a.energyBar.Refresh(Tick);}
    private void UpdateMotionEvidence(){foreach(NativeAgent a in agents){if(a.brain==null||a.brain.IsDead||a.identity?.torso?.Rigidbody==null||!a.ReadyForLearning){a.movingEvidenceTicks=a.stillEvidenceTicks=a.motionWindowTicks=0;a.isSustainedMoving=false;continue;}if(a.motionWindowTicks<=0)a.motionWindowStartPosition=a.identity.torso.Rigidbody.position;a.motionWindowTicks++;if(a.motionWindowTicks<10)continue;float speed=(a.identity.torso.Rigidbody.position-a.motionWindowStartPosition).magnitude/Mathf.Max(.0001f,a.motionWindowTicks*Time.fixedDeltaTime);a.motionWindowStartPosition=a.identity.torso.Rigidbody.position;a.motionWindowTicks=0;if(a.isSustainedMoving){a.stillEvidenceTicks=speed<=.025f?a.stillEvidenceTicks+1:0;if(a.stillEvidenceTicks>=2)a.isSustainedMoving=false;}else{a.movingEvidenceTicks=speed>=.08f?a.movingEvidenceTicks+1:0;if(a.movingEvidenceTicks>=2)a.isSustainedMoving=true;}}}
    private void LateUpdate(){if(PopulationDynamicsEnabled)MaintainPopulationInvariant();foreach(NativeAgent a in agents.ToArray()){if(a.identity?.torso==null||a.brain==null)continue;float energy=a.identity.torso.energy;if(!a.practiceActive)a.m1EnergyFitness+=energy-a.previousEnergy;a.previousEnergy=energy;if(a.m1Genome!=null)a.m1Genome.fitness=a.m1EnergyFitness-a.deathPenalty;if(a.brain.IsDead&&!a.deathRecorded){RecordDeathPenalty(a);}}if(Time.time>=nextCheckpoint){nextCheckpoint+=checkpointIntervalSeconds;SaveCheckpoint();}}
    private void HandleControlFailure(NativeAgent a,Exception e){ControlFailures++;LastControlError=a.identity==null?e.Message:a.identity.creatureId+": "+e.Message;Debug.LogError("Native control failed for creature "+LastControlError+"\n"+e);if(a.brain!=null&&!a.brain.IsDead)a.brain.Kill("native_control_error");}
    private void SeedPopulation(){for(int i=agents.Count;i<Mathf.Clamp(populationTarget,1,10);i++)Spawn(CreateSeedBody(i),"body_species_"+(i%InitialBodySpeciesCount),"m1_seed_"+(i%InitialBodySpeciesCount),seedPolicy.Clone(),i,0,rtNeat.Seed());}
    private void MaintainPopulationInvariant(){if(!PopulationDynamicsEnabled)return;populationTarget=Mathf.Clamp(populationTarget,1,10);if(agents.Count<populationTarget)SeedPopulation();}
    private void ReplaceDeadCreaturesImmediately(){if(!PopulationDynamicsEnabled)return;bool changed=false;foreach(NativeAgent victim in agents.Where(a=>a.brain==null||a.brain.IsDead).ToArray()){if(!agents.Contains(victim))continue;RecordDeathPenalty(victim);try{NativeAgent parent=SelectLivingParent();if(parent==null)RespawnSameGenotype(victim,victim.reservedSlot);else ReplaceAgent(victim,parent,victim.reservedSlot);replacementRetries.Remove(victim);ReplacementRetryState="none";ImmediateReplacementCount++;LastReplacementTick=Tick;changed=true;}catch(Exception e){int retries=replacementRetries.TryGetValue(victim,out int prior)?prior:0;if(retries==0){replacementRetries[victim]=1;ReplacementRetryState="queued retry for slot "+victim.reservedSlot;Debug.LogError("Native replacement failed once; retry queued: "+e.Message);}else{replacementRetries.Remove(victim);ReplacementRetryState="retry failed for slot "+victim.reservedSlot;}}}if(changed)RebuildSpeciation();}
    private NativeAgent SelectLivingParent(){Dictionary<string,float> fitness=NativeNestedSpeciation.SharedFitness(species);NativeAgent[] eligible=agents.Where(a=>a.brain!=null&&!a.brain.IsDead&&NativeCreatureModel.IsFinite(a.model.BodyFitness)&&!a.protectedOffspring).ToArray();if(eligible.Length==0)return null;NativeAgent best=null;float quality=float.NegativeInfinity;for(int i=0;i<3;i++){NativeAgent c=eligible[random.Next(eligible.Length)];float q=fitness.TryGetValue(c.identity.creatureId,out float value)?value:0f;if(q>quality){best=c;quality=q;}}return best;}
    private void RespawnSameGenotype(NativeAgent victim,int slot){BodyGenomeDto body=JsonConvert.DeserializeObject<BodyGenomeDto>(JsonConvert.SerializeObject(victim.body));NativeCreatureSave save=victim.model.Capture();Spawn(body,victim.identity.speciesId,victim.brain.M1SpeciesId,save.weights,slot,victim.bodyAgeGenerations,victim.m1Genome.Copy(),save);RemoveAgentObject(victim);}
    private void ReplaceAgent(NativeAgent victim,NativeAgent parent,int slot)
    {
        BodyGenomeDto child=JsonConvert.DeserializeObject<BodyGenomeDto>(JsonConvert.SerializeObject(parent.body));int age=parent.bodyAgeGenerations+1;bool changed=bodyMutationCooldownGenerations<=0||age>=bodyMutationCooldownGenerations;if(changed){MutateBody(child);age=0;}NativeAgent m1Parent=agents.Where(a=>a.brain!=null&&!a.brain.IsDead&&a.identity.speciesId==parent.identity.speciesId).OrderByDescending(a=>a.m1EnergyFitness).FirstOrDefault()??parent;NativeAgent mate=agents.Where(a=>a!=m1Parent&&a.m1Genome!=null&&a.m1Genome.species==m1Parent.m1Genome.species).OrderByDescending(a=>a.m1EnergyFitness).FirstOrDefault()??m1Parent;RtNeatGoalGenome genome=enableM1?rtNeat.Breed(m1Parent.m1Genome,mate.m1Genome):m1Parent.m1Genome.Copy();NativeCreatureSave save=parent.model.Capture();Spawn(child,parent.identity.speciesId,"rtneat_"+genome.species,save.weights,slot,age,genome,save);agents[agents.Count-1].protectedOffspring=changed;RemoveAgentObject(victim);Generation++;
    }
    private void RemoveAgentObject(NativeAgent victim){if(victim.identity!=null)modelsById.TryRemove(victim.identity.creatureId,out _);GameObject root=victim.identity!=null&&victim.identity.transform.parent!=null?victim.identity.transform.parent.gameObject:victim.identity?.gameObject;if(root!=null){root.SetActive(false);Destroy(root);}agents.Remove(victim);}
    private void RecordDeathPenalty(NativeAgent a){if(a==null||a.brain==null||a.deathRecorded)return;float penalty=a.brain.DeathReason=="predator"&&PredatorKillsEnabled?100f:25f;a.deathPenalty+=penalty;a.m1EnergyFitness-=penalty;a.deathRecorded=true;a.sequenceActive=false;a.observation=null;a.sequence=null;}
    private void RecoverFromExtinction(){if(!PopulationDynamicsEnabled)return;foreach(NativeAgent a in agents){GameObject root=a.identity!=null&&a.identity.transform.parent!=null?a.identity.transform.parent.gameObject:a.identity?.gameObject;if(root!=null){root.SetActive(false);Destroy(root);}}agents.Clear();SeedPopulation();RebuildSpeciation();Status="Native ecosystem recovered from extinction";}
    private void Evolve(){if(!PopulationDynamicsEnabled||agents.Count<2)return;NativeAgent parent=SelectLivingParent();if(parent==null)return;NativeAgent victim=agents.Where(a=>a!=parent&&!a.protectedOffspring).OrderByDescending(a=>a.model.BodyFitness).FirstOrDefault();if(victim==null)return;ReplaceAgent(victim,parent,victim.reservedSlot);MaintainPopulationInvariant();RebuildSpeciation();SaveCheckpoint();}

    private static BodyGenomeDto CreateSeedBody(int index)
    {
        var body=new BodyGenomeDto{genome_id=Guid.NewGuid().ToString("N"),limbs=new List<LimbGeneDto>()};int species=Mathf.Abs(index)%InitialBodySpeciesCount;
        if(species==0){body.limbs.Add(NewLimb(1,0,1));body.limbs.Add(NewLimb(2,0,5));body.limbs.Add(NewLimb(3,0,7));body.limbs.Add(NewLimb(4,2,3));body.limbs.Add(NewLimb(5,3,3));body.limbs.Add(NewLimb(6,0,0));}
        else if(species==1){body.limbs.Add(NewLimb(1,0,0));body.limbs.Add(NewLimb(2,0,4));body.limbs.Add(NewLimb(3,0,6));body.limbs.Add(NewLimb(4,1,3));body.limbs.Add(NewLimb(5,2,2));body.limbs.Add(NewLimb(6,3,3));}
        else if(species==2){body.limbs.Add(NewLimb(1,0,5));body.limbs.Add(NewLimb(2,0,7));body.limbs.Add(NewLimb(3,1,2));body.limbs.Add(NewLimb(4,1,3));body.limbs.Add(NewLimb(5,2,2));body.limbs.Add(NewLimb(6,2,3));}
        else if(species==3){int[] slots={0,1,4,5,6,7};for(int i=0;i<slots.Length;i++)body.limbs.Add(NewLimb(i+1,0,slots[i]));}
        else if(species==4){body.limbs.Add(NewLimb(1,0,4));body.limbs.Add(NewLimb(2,1,3));body.limbs.Add(NewLimb(3,2,3));body.limbs.Add(NewLimb(4,0,6));body.limbs.Add(NewLimb(5,4,2));body.limbs.Add(NewLimb(6,5,2));}
        else{body.limbs.Add(NewLimb(1,0,1));body.limbs.Add(NewLimb(2,1,2));body.limbs.Add(NewLimb(3,2,2));body.limbs.Add(NewLimb(4,0,7));body.limbs.Add(NewLimb(5,4,3));body.limbs.Add(NewLimb(6,5,3));}body.Validate();return body;
    }
    private static LimbGeneDto NewLimb(int id,int parent,int slot)=>new LimbGeneDto{innovation_id=id,parent_innovation_id=parent,attachment_slot=slot};
    private void Spawn(BodyGenomeDto body,string speciesId,string m1Species,NativeBrainWeights weights,int slot,int bodyAge=0,RtNeatGoalGenome m1Genome=null,NativeCreatureSave brainSave=null)
    {
        body.Validate();Vector2 position=NativeSpawnPosition(slot);GameObject root=new GameObject("NativeCreature_"+body.genome_id.Substring(0,8));root.transform.position=position;CreatureIdentity identity=root.AddComponent<CreatureIdentity>();identity.creatureId=Guid.NewGuid().ToString("N");identity.speciesId=speciesId;GameObject torsoObject=new GameObject("Torso");torsoObject.transform.SetParent(root.transform);torsoObject.transform.position=position;torsoObject.AddComponent<Rigidbody2D>();torsoObject.AddComponent<SpriteRenderer>();torsoObject.AddComponent<BoxCollider2D>();Torso torso=torsoObject.AddComponent<Torso>();torso.InitFromGenome(identity,body);identity.torso=torso;identity.bodyGenomeJson=JsonConvert.SerializeObject(body);PlaceConstructedBodyOnGround(root);int layer=CreatureLayerBase+Mathf.Abs(slot)%CreatureLayerCount;SetLayerRecursively(root,layer);for(int other=CreatureLayerBase;other<CreatureLayerBase+CreatureLayerCount;other++)if(other!=layer)Physics2D.IgnoreLayerCollision(layer,other,true);Limb[] limbs=torso.GetAllLimbs().Where(l=>l!=null).Take(NativeCreatureModel.MaxLimbs).ToArray();CreatureBrain brain=torsoObject.AddComponent<CreatureBrain>();brain.Init(torso,limbs.ToList());brain.DeathsEnabled=PopulationDynamicsEnabled;brain.SetNativeMetadata(speciesId,m1Species);NativeGoalVisualizer visual=torsoObject.AddComponent<NativeGoalVisualizer>();visual.Initialize(torso,brain,Color.HSVToRGB(Mathf.Repeat(slot*.173f,1f),.8f,1f));NativeEnergyBar energyBar=torsoObject.AddComponent<NativeEnergyBar>();energyBar.Initialize(torso);var model=new NativeCreatureModel(weights,2003+slot);if(brainSave!=null)model.Restore(brainSave);m1Genome=m1Genome??rtNeat.Seed();var agent=new NativeAgent{identity=identity,brain=brain,limbs=limbs,goalVisualizer=visual,energyBar=energyBar,body=body,bodySignature=body.genome_id,model=model,m1Genome=m1Genome,m1Phenotype=new RtNeatGoalPhenotype(m1Genome),motionWindowStartPosition=torso.Rigidbody.position,previousEnergy=torso.energy,bodyAgeGenerations=Mathf.Max(0,bodyAge),reservedSlot=Mathf.Abs(slot)%NativeSpawnSlots};agents.Add(agent);modelsById[identity.creatureId]=model;CaptureResetPose(agent);if(!enableM1&&trainingLaneRoot!=null)StartCurriculumTrial(agent);
    }
    private static void PlaceConstructedBodyOnGround(GameObject root){Physics2D.SyncTransforms();Collider2D[] colliders=root.GetComponentsInChildren<Collider2D>();if(colliders.Length==0)return;float min=colliders.Min(c=>c.bounds.min.y);root.transform.position+=Vector3.up*(WorldLayout.GroundTop+.03f-min);Physics2D.SyncTransforms();}
    private static Vector2 NativeSpawnPosition(int slot)=>new Vector2(-160f+Mathf.Abs(slot)%NativeSpawnSlots*MinimumSpawnSeparation,-2f);
    private static void SetLayerRecursively(GameObject root,int layer){root.layer=layer;foreach(Transform child in root.transform)SetLayerRecursively(child.gameObject,layer);}
    private void MutateBody(BodyGenomeDto body){body.genome_id=Guid.NewGuid().ToString("N");List<LimbGeneDto> enabled=body.limbs.Where(l=>l.enabled).ToList();if(enabled.Count<NativeCreatureModel.MaxLimbs&&random.NextDouble()<.65){var sites=new List<Vector2Int>();AddFreeSites(body,0,BodyMorphologyRules.TorsoSlots,sites);foreach(LimbGeneDto parent in enabled)if(GeneDepth(body,parent.innovation_id)<NativeCreatureModel.MaxPathDepth)AddFreeSites(body,parent.innovation_id,BodyMorphologyRules.LimbSlots,sites);if(sites.Count>0){Vector2Int site=sites[random.Next(sites.Count)];body.limbs.Add(NewLimb(body.limbs.Count==0?1:body.limbs.Max(l=>l.innovation_id)+1,site.x,site.y));}}else if(enabled.Count>4&&random.NextDouble()<.35){LimbGeneDto removable=enabled.Where(l=>!body.limbs.Any(o=>o.enabled&&o.parent_innovation_id==l.innovation_id)).OrderBy(_=>random.Next()).FirstOrDefault();if(removable!=null)removable.enabled=false;}body.Validate();}
    private static void AddFreeSites(BodyGenomeDto body,int parent,IEnumerable<int> slots,List<Vector2Int> output){HashSet<int> used=body.limbs.Where(l=>l.enabled&&l.parent_innovation_id==parent).Select(l=>l.attachment_slot).ToHashSet();foreach(int slot in slots)if(!used.Contains(slot))output.Add(new Vector2Int(parent,slot));}
    private static int GeneDepth(BodyGenomeDto body,int id){int depth=0;while(id!=0){LimbGeneDto gene=body.limbs.FirstOrDefault(l=>l.enabled&&l.innovation_id==id);if(gene==null)return NativeCreatureModel.MaxPathDepth;id=gene.parent_innovation_id;depth++;}return depth;}
    private void RebuildSpeciation(){List<NativeCreatureControllerView> views=agents.Where(a=>a.identity!=null&&a.brain!=null).Select(a=>new NativeCreatureControllerView(a.identity.creatureId,a.identity.speciesId,a.brain.M1SpeciesId,a.body,a.model.Weights,a.model.BodyFitness)).ToList();species=NativeNestedSpeciation.Rebuild(views,species);Dictionary<string,NativeAgent> byId=agents.Where(a=>a.identity!=null).ToDictionary(a=>a.identity.creatureId);foreach(NativeBodySpecies body in species)foreach(NativeBrainSubSpecies sub in body.subSpecies)foreach(NativeCreatureControllerView member in sub.members)if(byId.TryGetValue(member.id,out NativeAgent a))a.identity.speciesId=body.id;NativeRtNeatGoalPolicy.Speciate(agents.Where(a=>a.m1Genome!=null).Select(a=>a.m1Genome).ToList());foreach(NativeAgent a in agents)if(a.brain!=null&&a.m1Genome!=null)a.brain.SetNativeMetadata(a.identity.speciesId,"rtneat_"+a.m1Genome.species);}

    public void SaveCheckpoint()
    {
        if(saveTask!=null&&!saveTask.IsCompleted)return;if(random==null)random=new System.Random(1337^Generation^controlStep);var checkpoint=new NativeEcosystemCheckpoint{tick=Tick,generation=Generation,controlStep=controlStep,specialistSelectionCursor=specialistSelectionCursor,sharedM3Samples=SharedM3Samples,freshSequenceSamples=FreshSequenceSamples,sharedM3OptimizerSteps=SharedM3OptimizerSteps,goalSuccesses=GoalSuccesses,goalFailures=GoalFailures,experimentId=ExperimentId,randomState=random.Next(),nextEvolutionTicks=(long)(nextEvolution*1000f),rtNeat=rtNeat,validation=validation.Select(s=>s.Clone()).ToList(),learnerQueueDrops=LearnerQueueDrops,capabilityValidated=agents.Count>0&&agents.All(a=>a.curriculum!=null&&a.curriculum.passedStages.Count>0)&&ControlFailures==0};foreach(NativeAgent a in agents)checkpoint.creatures.Add(new NativeCreatureCheckpoint{creatureId=a.identity.creatureId,speciesId=a.identity.speciesId,m1SpeciesId=a.brain.M1SpeciesId,bodyGenomeJson=JsonConvert.SerializeObject(a.body),brain=a.model.Capture(),m1Genome=a.m1Genome.Copy(),curriculum=a.curriculum?.Clone(),bodyFitness=float.IsInfinity(a.model.BodyFitness)?float.MaxValue:a.model.BodyFitness,deathPenalty=a.deathPenalty,m1EnergyFitness=a.m1EnergyFitness,previousEnergy=a.previousEnergy,deathRecorded=a.deathRecorded,bodyAgeGenerations=a.bodyAgeGenerations,protectedOffspring=a.protectedOffspring,temporaryGoalRewardBlock=a.temporaryGoalRewardBlock});string path=checkpointPath;CheckpointStatus="Snapshot queued";saveTask=Task.Run(()=>WriteCheckpointSnapshot(path,checkpoint));
    }
    private void TryLoad()
    {
        if(!File.Exists(checkpointPath)&&!File.Exists(checkpointPath+".bak")&&!File.Exists(checkpointPath+".stable"))return;Exception primary=null;foreach(string candidate in new[]{checkpointPath,checkpointPath+".bak",checkpointPath+".stable"}){if(!File.Exists(candidate))continue;try{LoadCheckpointCandidate(candidate);LoadedFromCheckpoint=true;CheckpointStatus=candidate==checkpointPath?"Loaded":candidate.EndsWith(".stable")?"Recovered validated capability":"Recovered backup";LastCheckpointSavedAt=CheckpointStatus;LastCheckpointError=primary?.Message??"";return;}catch(Exception e){if(primary==null)primary=e;else LastCheckpointError=(LastCheckpointError+" | "+e.Message).Trim();}}CheckpointStatus="Rejected; fresh population";if(string.IsNullOrEmpty(LastCheckpointError))LastCheckpointError=primary?.Message??"No compatible v21 checkpoint";
    }
    private static void WriteManifest(string path,NativeEcosystemCheckpoint checkpoint){string json=JsonConvert.SerializeObject(checkpoint,Formatting.None);using(var stream=new FileStream(path,FileMode.Create,FileAccess.Write,FileShare.None))using(var writer=new StreamWriter(stream)){writer.Write(json);writer.Flush();stream.Flush(true);}}
    private void WriteCheckpointSnapshot(string path,NativeEcosystemCheckpoint checkpoint){long started=System.Diagnostics.Stopwatch.GetTimestamp();try{NativeDynamicsWeights dynamics;NativeOptimizerState optimizer;NativeSynapticIntelligence protection;NativeReplayBuffer replay;if(learner!=null)learner.Capture(out dynamics,out optimizer,out protection,out replay);else{dynamics=sharedM3.Clone();optimizer=m3Optimizer.Clone();protection=m3Protection.Clone();replay=loadedReplay.Clone();}checkpoint.sharedM3=dynamics;checkpoint.m3Optimizer=optimizer;checkpoint.m3Protection=protection;checkpoint.replay=replay.samples;checkpoint.replayCount=replay.Count;checkpoint.replaySeen=replay.seen;checkpoint.replayRngState=replay.random.State;Directory.CreateDirectory(Path.GetDirectoryName(path));checkpoint.tensorGeneration=DateTime.UtcNow.Ticks.ToString("x16");checkpoint.tensorFile="native_ecosystem_v21."+checkpoint.tensorGeneration+".bin";string tensorPath=Path.Combine(Path.GetDirectoryName(path),checkpoint.tensorFile),tensorTemp=tensorPath+".tmp",manifestTemp=path+".tmp",backup=path+".bak";NativeTensorCheckpointStore.Write(tensorTemp,checkpoint);checkpoint.tensorSha256=NativeTensorCheckpointStore.Sha256(tensorTemp);File.Move(tensorTemp,tensorPath);WriteManifest(manifestTemp,checkpoint);var check=JsonConvert.DeserializeObject<NativeEcosystemCheckpoint>(File.ReadAllText(manifestTemp));if(check==null||check.schema!=21||!NativeEcosystemCheckpoint.IsCompatibleConfiguration(check.configuration)||check.tensorSha256!=NativeTensorCheckpointStore.Sha256(tensorPath))throw new InvalidDataException("Temporary v21 checkpoint failed validation");if(File.Exists(path))File.Replace(manifestTemp,path,backup,true);else File.Move(manifestTemp,path);if(checkpoint.capabilityValidated)File.Copy(path,path+".stable",true);CleanupUnreferencedTensorGenerations(path);CheckpointStatus=checkpoint.capabilityValidated?"Saved + validated fallback":"Saved";LastCheckpointError="";LastCheckpointSavedAt=DateTime.Now.ToString("HH:mm:ss");}catch(Exception e){CheckpointStatus="Save failed";LastCheckpointError=e.Message;}finally{CheckpointMilliseconds=(float)((System.Diagnostics.Stopwatch.GetTimestamp()-started)*1000d/System.Diagnostics.Stopwatch.Frequency);}}
    private void LoadCheckpointCandidate(string manifestPath){var c=JsonConvert.DeserializeObject<NativeEcosystemCheckpoint>(File.ReadAllText(manifestPath));if(c==null||c.schema!=21||!NativeEcosystemCheckpoint.IsCompatibleConfiguration(c.configuration))throw new InvalidDataException("Native checkpoint schema/configuration mismatch");NativeTensorCheckpointStore.ValidateFileName(c.tensorFile);string tensorPath=Path.Combine(Path.GetDirectoryName(checkpointPath),c.tensorFile);if(!File.Exists(tensorPath)||NativeTensorCheckpointStore.Sha256(tensorPath)!=c.tensorSha256)throw new InvalidDataException("Native checkpoint tensor checksum mismatch");NativeTensorCheckpointStore.Read(tensorPath,c);sharedM3=c.sharedM3;m3Optimizer=c.m3Optimizer??new NativeOptimizerState();m3Protection=c.m3Protection??new NativeSynapticIntelligence();loadedReplay=new NativeReplayBuffer{seen=c.replaySeen,random=new NativeDeterministicRng(c.replayRngState)};loadedReplay.samples=c.replay??new List<NativeCompletedSequence>();loadedReplay.RebuildIndex();rtNeat=c.rtNeat??new NativeRtNeatGoalPolicy();learnerQueueDrops=c.learnerQueueDrops;GoalSuccesses=c.goalSuccesses;GoalFailures=c.goalFailures;SharedM3Samples=c.sharedM3Samples;FreshSequenceSamples=c.freshSequenceSamples;SharedM3OptimizerSteps=c.sharedM3OptimizerSteps;ExperimentId=string.IsNullOrWhiteSpace(c.experimentId)?ExperimentId:c.experimentId;Tick=c.tick;Generation=c.generation;controlStep=c.controlStep;specialistSelectionCursor=c.specialistSelectionCursor;random=new System.Random(unchecked((int)c.randomState));validation.Clear();if(c.validation!=null)validation.AddRange(c.validation.TakeLast(ValidationCapacity));foreach(NativeCreatureCheckpoint saved in c.creatures.Take(Mathf.Clamp(populationTarget,1,10))){BodyGenomeDto body=JsonConvert.DeserializeObject<BodyGenomeDto>(saved.bodyGenomeJson);Spawn(body,saved.speciesId,saved.m1SpeciesId,saved.brain?.weights??seedPolicy.Clone(),agents.Count,saved.bodyAgeGenerations,saved.m1Genome??rtNeat.Seed(),saved.brain);NativeAgent a=agents[agents.Count-1];a.curriculum=saved.curriculum??new NativeCurriculumState();a.curriculum.passedStages=a.curriculum.passedStages??new List<int>();string generated=a.identity.creatureId;modelsById.TryRemove(generated,out _);a.identity.creatureId=saved.creatureId;modelsById[a.identity.creatureId]=a.model;a.deathPenalty=saved.deathPenalty;a.m1EnergyFitness=saved.m1EnergyFitness;a.previousEnergy=saved.previousEnergy;a.deathRecorded=saved.deathRecorded;a.protectedOffspring=saved.protectedOffspring;a.temporaryGoalRewardBlock=saved.temporaryGoalRewardBlock;if(!a.curriculum.Complete)StartCurriculumTrial(a);}}
    private static void CleanupUnreferencedTensorGenerations(string manifestPath){string directory=Path.GetDirectoryName(manifestPath);var keep=new HashSet<string>(StringComparer.OrdinalIgnoreCase);foreach(string manifest in new[]{manifestPath,manifestPath+".bak",manifestPath+".stable"})try{if(!File.Exists(manifest))continue;var c=JsonConvert.DeserializeObject<NativeEcosystemCheckpoint>(File.ReadAllText(manifest));if(c!=null&&!string.IsNullOrWhiteSpace(c.tensorFile))keep.Add(c.tensorFile);}catch{}foreach(string file in Directory.GetFiles(directory,"native_ecosystem_v21.*.bin")){string name=Path.GetFileName(file);if(!keep.Contains(name))try{File.Delete(file);}catch{}}}
    private void OnApplicationQuit()=>SaveCheckpoint(); private void OnDestroy(){if(Application.isPlaying){SaveCheckpoint();try{saveTask?.Wait(5000);}catch{}}learner?.Dispose();}
}

public enum NativeGoalMovement{Still,Toward,Away}
public sealed class NativeGoalVisualizer:MonoBehaviour
{
    public const float MovementThreshold=.05f,MaximumDisplayDistance=4f;private Torso torso;private CreatureBrain brain;private GameObject root;private Transform marker;private LineRenderer line;private TextMesh label,movement;private Material material;private Color color;private Vector2 goal,displayGoal,baseline;private bool hasGoal,hasBaseline;
    public void Initialize(Torso t,CreatureBrain b,Color c){torso=t;brain=b;color=c;Ensure();Refresh();}
    private void LateUpdate(){if(torso==null||brain==null)return;Ensure();Refresh();if(hasGoal&&root.activeSelf){UpdateDisplayCue();line.SetPosition(0,torso.transform.position);line.SetPosition(1,displayGoal);}}
    private void Ensure(){if(marker!=null)return;root=new GameObject("NativeGoalVisual");root.SetActive(false);GameObject m=new GameObject("NativeGoalMarker");m.transform.SetParent(root.transform,false);var sr=m.AddComponent<SpriteRenderer>();sr.sprite=BodyUtils.GetSquareSprite();sr.color=new Color(color.r,color.g,color.b,.72f);sr.sortingOrder=-10;m.transform.localScale=new Vector3(.22f,.22f,1f);marker=m.transform;GameObject l=new GameObject("NativeGoalLine");l.transform.SetParent(root.transform,false);line=l.AddComponent<LineRenderer>();line.positionCount=2;line.useWorldSpace=true;line.startWidth=.025f;line.endWidth=.012f;line.sortingOrder=-11;material=new Material(Shader.Find("Sprites/Default"));material.color=color;line.sharedMaterial=material;label=MakeText("NativeGoalCoordinates",-9);movement=MakeText("NativeGoalMovement",-8);movement.text="MEASURING";}
    private TextMesh MakeText(string n,int order){GameObject o=new GameObject(n);o.transform.SetParent(root.transform,false);TextMesh t=o.AddComponent<TextMesh>();t.anchor=TextAnchor.MiddleCenter;t.alignment=TextAlignment.Center;t.fontSize=48;t.characterSize=.08f;t.fontStyle=FontStyle.Bold;t.color=Color.white;t.GetComponent<MeshRenderer>().sortingOrder=order;return t;}
    private void Refresh(){if(!brain.HasWorldGoal){if(root.activeSelf)root.SetActive(false);return;}if(hasGoal&&(brain.CurrentWorldGoal-goal).sqrMagnitude<=1e-6f)return;goal=brain.CurrentWorldGoal;hasGoal=true;hasBaseline=false;root.SetActive(true);UpdateDisplayCue();}
    private void UpdateDisplayCue(){Vector2 origin=torso.transform.position;displayGoal=DisplayTarget(origin,goal);marker.position=goal;label.text=$"G ({goal.x:F2}, {goal.y:F2})";label.transform.position=goal+Vector2.up*.4f;movement.transform.position=goal+Vector2.up;}
    public void ReportMovement(Vector2 current){Ensure();Refresh();if(!brain.HasWorldGoal)return;if(!hasBaseline){baseline=current;hasBaseline=true;movement.text="MEASURING";movement.color=Color.white;return;}Vector2 toward=goal-baseline;float p=toward.sqrMagnitude<=1e-6f?0f:Vector2.Dot(current-baseline,toward.normalized);baseline=current;NativeGoalMovement s=ClassifyProgress(p);movement.text=s==NativeGoalMovement.Toward?$"TOWARD +{p:F2}":s==NativeGoalMovement.Away?$"AWAY {p:F2}":$"STILL {p:+0.00;-0.00;0.00}";movement.color=MovementColor(s);}
    public static NativeGoalMovement ClassifyProgress(float p)=>p>MovementThreshold?NativeGoalMovement.Toward:p<-MovementThreshold?NativeGoalMovement.Away:NativeGoalMovement.Still;
    public static Color MovementColor(NativeGoalMovement movement)=>movement==NativeGoalMovement.Toward?new Color(.2f,1f,.3f):movement==NativeGoalMovement.Away?new Color(1f,.22f,.22f):new Color(1f,.85f,.2f);
    public static Vector2 DisplayTarget(Vector2 origin,Vector2 actualGoal){Vector2 offset=actualGoal-origin;return offset.sqrMagnitude<=MaximumDisplayDistance*MaximumDisplayDistance?actualGoal:origin+offset.normalized*MaximumDisplayDistance;}
    private void OnDestroy(){if(material!=null){if(Application.isPlaying)Destroy(material);else DestroyImmediate(material);}if(root!=null){if(Application.isPlaying)Destroy(root);else DestroyImmediate(root);}}
}

public sealed class NativeEnergyBar:MonoBehaviour
{
    public const int RefreshIntervalTicks=50;private Torso torso;private GameObject root;private Transform fill;private SpriteRenderer fillRenderer;private float width;public int LastRefreshTick{get;private set;}=-1;
    public void Initialize(Torso value){torso=value;Ensure();Refresh();}
    public void Refresh(int tick){Refresh();LastRefreshTick=tick;}
    private void LateUpdate(){Refresh();}
    public void Refresh(){if(torso==null)return;Ensure();float fraction=EnergyFraction(torso.energy,torso.maxEnergy);float height=.12f;root.transform.position=(Vector2)torso.transform.position+Vector2.up*(Mathf.Max(.25f,torso.dimensions.y*.5f)+.38f);fill.localScale=new Vector3(width*fraction,height,1f);fill.localPosition=new Vector3(-width*.5f+width*fraction*.5f,0f,-.01f);fillRenderer.color=EnergyColor(fraction);}
    public static float EnergyFraction(float energy,float maximum)=>maximum<=0f?0f:Mathf.Clamp01(energy/maximum);
    public static Color EnergyColor(float fraction)=>Color.Lerp(new Color(1f,.2f,.2f),new Color(.2f,1f,.3f),Mathf.Clamp01(fraction));
    private void Ensure(){if(root!=null)return;width=Mathf.Max(.8f,torso.dimensions.x*1.8f);root=new GameObject("NativeEnergyBarVisual");GameObject background=new GameObject("Capacity");background.transform.SetParent(root.transform,false);background.transform.localScale=new Vector3(width,.12f,1f);var backgroundRenderer=background.AddComponent<SpriteRenderer>();backgroundRenderer.sprite=BodyUtils.GetSquareSprite();backgroundRenderer.color=new Color(.12f,.12f,.12f,.9f);backgroundRenderer.sortingOrder=20;GameObject foreground=new GameObject("Fill");foreground.transform.SetParent(root.transform,false);fill=foreground.transform;fillRenderer=foreground.AddComponent<SpriteRenderer>();fillRenderer.sprite=BodyUtils.GetSquareSprite();fillRenderer.sortingOrder=21;}
    private void OnDestroy(){if(root!=null){if(Application.isPlaying)Destroy(root);else DestroyImmediate(root);}}
}
