using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json;
using UnityEngine;

[Serializable]
public sealed class NativeBrainWeights
{
    public int version = 13;
    public float[] m1Input, m1Residual, m1Output, m1Bias;
    public float[] m2Context, m2Joint, m2Position, m2AttentionQuery, m2AttentionKey, m2AttentionValue, m2AttentionQuery2, m2AttentionKey2, m2AttentionValue2, m2Fusion, m2Residual, m2Deep1, m2Deep2, m2Deep3, m2Output, m2Bias;
    public float[] m3Context, m3Joint, m3Position, m3AttentionQuery, m3AttentionKey, m3AttentionValue, m3AttentionQuery2, m3AttentionKey2, m3AttentionValue2, m3Fusion, m3Residual, m3Deep1, m3Deep2, m3Deep3, m3Output, m3Bias;

    public static NativeBrainWeights Create(int seed)
    {
        var r = new System.Random(seed); int h = NativeCreatureModel.Hidden;
        return new NativeBrainWeights {
            m1Input = Xavier(r, NativeCreatureModel.M1InputSize, h), m1Residual = Xavier(r, h, h), m1Output = Xavier(r, h, 2), m1Bias = new float[h * 2 + 2],
            m2Context = Xavier(r, NativeCreatureModel.M2ContextSize, h), m2Joint = Xavier(r, NativeCreatureModel.JointFeatureSize, h), m2Position = Xavier(r, 2, h), m2AttentionQuery = Xavier(r, h, h), m2AttentionKey = Xavier(r, h, h), m2AttentionValue = Xavier(r, h, h), m2AttentionQuery2 = Xavier(r, h, h), m2AttentionKey2 = Xavier(r, h, h), m2AttentionValue2 = Xavier(r, h, h), m2Fusion = Xavier(r, h * 2, h), m2Residual = Xavier(r, h, h), m2Deep1 = Xavier(r, h, h), m2Deep2 = Xavier(r, h, h), m2Deep3 = Xavier(r, h, h), m2Output = Xavier(r, h, NativeCreatureModel.PlanningHorizon), m2Bias = new float[h * 7 + NativeCreatureModel.PlanningHorizon],
            m3Context = Xavier(r, NativeCreatureModel.M3ContextSize, h), m3Joint = Xavier(r, NativeCreatureModel.M3JointInputSize, h), m3Position = Xavier(r, 2, h), m3AttentionQuery = Xavier(r, h, h), m3AttentionKey = Xavier(r, h, h), m3AttentionValue = Xavier(r, h, h), m3AttentionQuery2 = Xavier(r, h, h), m3AttentionKey2 = Xavier(r, h, h), m3AttentionValue2 = Xavier(r, h, h), m3Fusion = Xavier(r, h * 2, h), m3Residual = Xavier(r, h, h), m3Deep1 = Xavier(r, h, h), m3Deep2 = Xavier(r, h, h), m3Deep3 = Xavier(r, h, h), m3Output = Xavier(r, h, NativeCreatureModel.M3OutputSize), m3Bias = new float[h * 7 + NativeCreatureModel.M3OutputSize]
        };
    }
    private static float[] Xavier(System.Random r, int input, int output) { float limit = Mathf.Sqrt(6f / (input + output)); float[] a = new float[input * output]; for (int i = 0; i < a.Length; i++) a[i] = ((float)r.NextDouble() * 2f - 1f) * limit; return a; }
    public NativeBrainWeights Clone() => JsonConvert.DeserializeObject<NativeBrainWeights>(JsonConvert.SerializeObject(this));
    public void CopyFrom(NativeBrainWeights source) { var copy = source.Clone(); foreach (var f in typeof(NativeBrainWeights).GetFields()) f.SetValue(this, f.GetValue(copy)); }
    public void CopyM3From(NativeBrainWeights source) { foreach (var pair in source.M3Parameters()) typeof(NativeBrainWeights).GetField("m3" + char.ToUpperInvariant(pair.Key[0]) + pair.Key.Substring(1)).SetValue(this, (float[])pair.Value.Clone()); }
    public void Mutate(System.Random r, float amount = .05f) { MutateM1(r, amount); MutateM2(r, amount); }
    public void MutateM1(System.Random r, float amount) { foreach (float[] a in new[] { m1Input, m1Residual, m1Output, m1Bias }) MutateArray(a, r, amount, .04f); }
    public void MutateM2(System.Random r, float amount, float hiddenProbability = .03f, float headProbability = .12f) { foreach (var p in M2Parameters()) MutateArray(p.Value, r, amount, p.Key == "output" ? headProbability : hiddenProbability); }
    private static void MutateArray(float[] a, System.Random r, float amount, float probability) { for (int i = 0; i < a.Length; i++) if (r.NextDouble() < probability) a[i] = Mathf.Clamp(a[i] + ((float)r.NextDouble() - .5f) * amount, -4f, 4f); }
    public bool IsFinite() => Arrays().All(a => a != null && a.All(NativeCreatureModel.IsFinite));
    public IEnumerable<float[]> ControllerArrays() { yield return m1Input; yield return m1Residual; yield return m1Output; yield return m1Bias; foreach (var p in M2Parameters()) yield return p.Value; }
    public IEnumerable<float[]> DynamicsArrays() => M3Parameters().Select(p => p.Value);
    public IEnumerable<float[]> Arrays() => ControllerArrays().Concat(DynamicsArrays());
    public IEnumerable<KeyValuePair<string,float[]>> M2Parameters() { yield return P("context",m2Context); yield return P("joint",m2Joint); yield return P("position",m2Position); yield return P("attentionQuery",m2AttentionQuery); yield return P("attentionKey",m2AttentionKey); yield return P("attentionValue",m2AttentionValue); yield return P("attentionQuery2",m2AttentionQuery2); yield return P("attentionKey2",m2AttentionKey2); yield return P("attentionValue2",m2AttentionValue2); yield return P("fusion",m2Fusion); yield return P("residual",m2Residual); yield return P("deep1",m2Deep1); yield return P("deep2",m2Deep2); yield return P("deep3",m2Deep3); yield return P("output",m2Output); yield return P("bias",m2Bias); }
    public IEnumerable<KeyValuePair<string,float[]>> M3Parameters() { yield return P("context",m3Context); yield return P("joint",m3Joint); yield return P("position",m3Position); yield return P("attentionQuery",m3AttentionQuery); yield return P("attentionKey",m3AttentionKey); yield return P("attentionValue",m3AttentionValue); yield return P("attentionQuery2",m3AttentionQuery2); yield return P("attentionKey2",m3AttentionKey2); yield return P("attentionValue2",m3AttentionValue2); yield return P("fusion",m3Fusion); yield return P("residual",m3Residual); yield return P("deep1",m3Deep1); yield return P("deep2",m3Deep2); yield return P("deep3",m3Deep3); yield return P("output",m3Output); yield return P("bias",m3Bias); }
    private static KeyValuePair<string,float[]> P(string n,float[] v) => new KeyValuePair<string,float[]>(n,v);
}

public sealed class NativeCreatureModel
{
    public const int Hidden=32, M2AttentionHeads=4, M3AttentionHeads=8, M2MlpHiddenLayers=5, M3MlpHiddenLayers=5, M2TransformerBlocks=2, M3TransformerBlocks=2, MaxLimbs=BodyMorphologyRules.MaxLimbs, MaxPathDepth=BodyMorphologyRules.MaxDepth, PlanningHorizon=5, ActionTicks=4, SequenceTicks=20, GoalWindowTicks=1320, M1GoalWindowTicks=20;
    public const int M1InputSize=28, M2ContextSize=8, M3ContextSize=6, JointFeatureSize=4, PositionEncodingSize=2, M3JointInputSize=9, M3OutputSize=10;
    public const float MaximumActionDegrees=8f, MinimumActionDegrees=.75f, GoalMagnitude=4f, CurriculumGoalMagnitude=12f, M2LearningRate=.0003f, M3LearningRate=.0003f, ActionEnergyWeight=.01f, AntiZeroWeight=4f, MotionThreshold=.01f;
    public const int ActionBiasEndTick=13333, ExplorationDecayUpdates=10000, MinimumM2FitnessSamples=50, M2FitnessWindow=250, FixedGoalGenerations=1500, StartupSafeguardGenerations=200;
    public const float ExplorationStartSigma=.5f, ExplorationFloorSigma=.05f;
    public static readonly float[] GoalStepWeights={1f,1f,2f,4f,8f};
    public readonly NativeBrainWeights Weights;
    public NativeOptimizerState M2Optimizer { get; private set; } = new NativeOptimizerState();
    public Vector2 CurrentGoal { get; private set; }
    public Vector2 CurrentWorldGoal { get; private set; }
    public int GoalTicksRemaining { get; private set; }
    public float LastM2Loss { get; private set; }=float.PositiveInfinity;
    public float LastM2GoalLoss { get; private set; }=float.PositiveInfinity;
    public float LastM2EnergyLoss { get; private set; }
    public float LastM3Loss { get; private set; }=float.PositiveInfinity;
    public float LastM3Mse { get; private set; }=float.PositiveInfinity;
    public float LastM3RelativeLoss { get; private set; }
    public NativePositionPrediction LastPrediction { get; private set; }
    public int LeftLossSamples=>leftLosses.Count; public int RightLossSamples=>rightLosses.Count; public int M2LossSamples=>LeftLossSamples+RightLossSamples;
    public float LeftProposalLoss=>Mean(leftLosses); public float RightProposalLoss=>Mean(rightLosses); public bool LeftTrialComplete=>LeftLossSamples>=MinimumM2FitnessSamples; public bool RightTrialComplete=>RightLossSamples>=MinimumM2FitnessSamples; public bool IsBidirectionallyVerified=>LeftTrialComplete&&RightTrialComplete;
    public float BodyFitness=>BidirectionalFitness(LeftProposalLoss,LeftLossSamples,LeftTrialComplete,RightProposalLoss,RightLossSamples,RightTrialComplete);
    public int LatchedDirection { get; private set; } public float LeftBestTrialProgress { get; private set; } public float RightBestTrialProgress { get; private set; }
    private readonly Queue<float> leftLosses=new Queue<float>(), rightLosses=new Queue<float>(); private NativeDeterministicRng exploration; private int fixedGoalBlock=int.MinValue; private bool hasGoal,m1GoalAnchorInitialized; private Vector2 m1GoalAnchor;
    public NativeCreatureModel(NativeBrainWeights weights,int seed=0){Weights=weights??NativeBrainWeights.Create(seed==0?Environment.TickCount:seed);exploration=new NativeDeterministicRng((ulong)(seed==0?Environment.TickCount:seed));}

    public NativeObservation Observe(float[] global,Limb[] limbs,int tick,NativeLocalProprioception proprio,bool enableM1)
    {
        if(enableM1){if(!m1GoalAnchorInitialized){m1GoalAnchor=proprio.worldPosition;m1GoalAnchorInitialized=true;}Vector2 offset=SoftBiasedGoal(RunM1(global))*GoalMagnitude;CurrentWorldGoal=new Vector2(Mathf.Clamp(m1GoalAnchor.x+offset.x,-WorldLayout.WorldHalfWidth+1f,WorldLayout.WorldHalfWidth-1f),m1GoalAnchor.y+offset.y);GoalTicksRemaining=SequenceTicks;hasGoal=true;}
        else{m1GoalAnchorInitialized=false;int block=Mathf.Max(0,tick)/GoalWindowTicks;if(!hasGoal||block!=fixedGoalBlock){CurrentWorldGoal=new Vector2(Mathf.Clamp(proprio.worldPosition.x+FixedTrainingGoal(tick).x,-WorldLayout.WorldHalfWidth+1f,WorldLayout.WorldHalfWidth-1f),FixedGoalWorldHeight);fixedGoalBlock=block;hasGoal=true;}GoalTicksRemaining=GoalWindowTicks-Mathf.Max(0,tick)%GoalWindowTicks;}
        Vector2 worldOffset=CurrentWorldGoal-proprio.worldPosition;CurrentGoal=proprio.WorldToTorsoVector(worldOffset);LatchedDirection=ClassifyWorldGoalDirection(worldOffset.x);int count=Mathf.Min(limbs?.Length??0,MaxLimbs);
        var o=new NativeObservation{torsoWithGoal=TorsoFeatures(proprio,CurrentGoal,true),torsoWithoutGoal=TorsoFeatures(proprio,Vector2.zero,false),jointFeatures=new float[MaxLimbs*JointFeatureSize],positionEncodings=new float[MaxLimbs*2],limbCount=count,goal=CurrentGoal,worldGoal=CurrentWorldGoal,startWorldPosition=proprio.worldPosition,startWorldRotationDegrees=proprio.worldRotationDegrees,tick=tick};
        for(int i=0;i<count;i++){Array.Copy(JointFeatures(limbs[i].JointAngle,limbs[i].JointSpeed),0,o.jointFeatures,i*4,4);Array.Copy(JointPositionEncoding(limbs[i].genePath,limbs[i].attachmentSlot),0,o.positionEncodings,i*2,2);}return o;
    }

    public NativeActionSequence OptimizeAndPlan(NativeObservation observation,NativeBrainWeights sharedM3,int sharedM3Updates)
    {
        var before=ForwardM2(observation,Weights);float bias=ActionBiasStrength(observation.tick);float[,] biased=ApplyActionBias(before.actions,observation,bias);var predicted=ForwardM3(observation,biased,sharedM3);float[] predictionGradient=new float[M3OutputSize];
        M2Loss(predicted.prediction,observation.goal,biased,observation.limbCount,predictionGradient,out _,out _);float[,] actionGradient=BackwardM3(predicted,predictionGradient,sharedM3,null);AddEnergyGradient(actionGradient,biased,observation.limbCount);for(int s=0;s<5;s++)for(int l=0;l<observation.limbCount;l++)actionGradient[s,l]*=1f-bias;
        var gradient=Zero(Weights.M2Parameters());BackwardM2(before,actionGradient,Weights,gradient);ApplyAdam(Weights.M2Parameters(),gradient,M2Optimizer,M2LearningRate);
        var after=ForwardM2(observation,Weights);float[,] executed=ApplyActionBias(after.actions,observation,bias);float sigma=ExplorationSigma(sharedM3Updates);for(int s=0;s<5;s++)for(int l=0;l<observation.limbCount;l++)executed[s,l]=Mathf.Clamp(executed[s,l]+Gaussian()*sigma,-8f,8f);
        var finalPrediction=ForwardM3(observation,executed,sharedM3);LastM2Loss=M2Loss(finalPrediction.prediction,observation.goal,executed,observation.limbCount,null,out float goalLoss,out float energyLoss);LastM2GoalLoss=goalLoss;LastM2EnergyLoss=energyLoss;LastPrediction=new NativePositionPrediction((float[])finalPrediction.prediction.Clone());RecordFitness(LastM2Loss);
        return new NativeActionSequence(executed,observation.limbCount,observation.goal,observation.worldGoal,LastPrediction,bias,sigma);
    }

    public float TrainSharedM3(NativeCompletedSequence sample,NativeBrainWeights sharedM3,NativeOptimizerState optimizer)
    {var cache=ForwardM3(sample.observation,sample.ActionMatrix(),sharedM3);float[] g=new float[10];float loss=M3Loss(cache.prediction,sample.actualPositions,g,out float mse,out float relative);var gradients=Zero(sharedM3.M3Parameters());BackwardM3(cache,g,sharedM3,gradients);ApplyAdam(sharedM3.M3Parameters(),gradients,optimizer,M3LearningRate);LastM3Loss=loss;LastM3Mse=mse;LastM3RelativeLoss=relative;return loss;}

    public static float[] PredictM3ForTesting(NativeObservation observation,float[,] actions,NativeBrainWeights weights)=>(float[])ForwardM3(observation,actions,weights).prediction.Clone();
    public static float[] M3GradientForTesting(NativeCompletedSequence sample,NativeBrainWeights weights,string parameterName){var cache=ForwardM3(sample.observation,sample.ActionMatrix(),weights);float[] outputGradient=new float[10];M3Loss(cache.prediction,sample.actualPositions,outputGradient,out _,out _);var gradients=Zero(weights.M3Parameters());BackwardM3(cache,outputGradient,weights,gradients);return gradients[parameterName];}
    public static float M3LossForTesting(NativeCompletedSequence sample,NativeBrainWeights weights){float[] prediction=ForwardM3(sample.observation,sample.ActionMatrix(),weights).prediction;return M3Loss(prediction,sample.actualPositions,null,out _,out _);}
    public static float[] M2GradientForTesting(NativeObservation observation,NativeBrainWeights m2,NativeBrainWeights m3,string parameterName){var cache=ForwardM2(observation,m2);float bias=ActionBiasStrength(observation.tick);float[,] actions=ApplyActionBias(cache.actions,observation,bias);var prediction=ForwardM3(observation,actions,m3);float[] pg=new float[10];M2Loss(prediction.prediction,observation.goal,actions,observation.limbCount,pg,out _,out _);float[,] ag=BackwardM3(prediction,pg,m3,null);AddEnergyGradient(ag,actions,observation.limbCount);for(int s=0;s<5;s++)for(int l=0;l<observation.limbCount;l++)ag[s,l]*=1f-bias;var gradients=Zero(m2.M2Parameters());BackwardM2(cache,ag,m2,gradients);return gradients[parameterName];}
    public static float M2LossForTesting(NativeObservation observation,NativeBrainWeights m2,NativeBrainWeights m3){var cache=ForwardM2(observation,m2);float[,] actions=ApplyActionBias(cache.actions,observation,ActionBiasStrength(observation.tick));var prediction=ForwardM3(observation,actions,m3);return M2Loss(prediction.prediction,observation.goal,actions,observation.limbCount,null,out _,out _);}

    public static float M3Loss(float[] predicted,float[] actual,float[] gradient,out float mse,out float relative)
    {mse=0f;relative=0f;if(gradient!=null)Array.Clear(gradient,0,gradient.Length);for(int i=0;i<10;i++){float e=predicted[i]-actual[i];mse+=e*e/10f;if(gradient!=null)gradient[i]+=e/5f;}for(int s=0;s<5;s++){float tx=actual[s*2],ty=actual[s*2+1],d=tx*tx+ty*ty;if(d<=MotionThreshold*MotionThreshold)continue;float x=predicted[s*2]-tx,y=predicted[s*2+1]-ty,den=d+MotionThreshold*MotionThreshold;relative+=AntiZeroWeight*(x*x+y*y)/(den*5f);if(gradient!=null){gradient[s*2]+=2f*AntiZeroWeight*x/(den*5f);gradient[s*2+1]+=2f*AntiZeroWeight*y/(den*5f);}}return mse+relative;}
    public static float M2GoalLoss(float[] predicted,Vector2 goal){float total=GoalStepWeights.Sum(),loss=0f;for(int s=0;s<5;s++){float x=predicted[s*2]-goal.x,y=predicted[s*2+1]-goal.y;loss+=GoalStepWeights[s]*(x*x+y*y)/total;}return loss;}
    private static float M2Loss(float[] predicted,Vector2 goal,float[,] actions,int activeLimbs,float[] gradient,out float goalLoss,out float energyLoss){float total=GoalStepWeights.Sum();goalLoss=0f;if(gradient!=null)Array.Clear(gradient,0,gradient.Length);for(int s=0;s<5;s++){float x=predicted[s*2]-goal.x,y=predicted[s*2+1]-goal.y,k=GoalStepWeights[s]/total;goalLoss+=k*(x*x+y*y);if(gradient!=null){gradient[s*2]=2f*k*x;gradient[s*2+1]=2f*k*y;}}int limbs=Mathf.Clamp(activeLimbs,0,actions.GetLength(1)),count=Mathf.Max(1,actions.GetLength(0)*limbs);energyLoss=0f;for(int s=0;s<actions.GetLength(0);s++)for(int l=0;l<limbs;l++){float n=actions[s,l]/8f;energyLoss+=ActionEnergyWeight*n*n/count;}return goalLoss+energyLoss;}
    private static void AddEnergyGradient(float[,] g,float[,] a,int activeLimbs){int limbs=Mathf.Clamp(activeLimbs,0,a.GetLength(1)),count=Mathf.Max(1,a.GetLength(0)*limbs);for(int s=0;s<a.GetLength(0);s++)for(int l=0;l<limbs;l++)g[s,l]+=2f*ActionEnergyWeight*a[s,l]/(64f*count);}

    public static float ActionBiasStrength(int tick){if(tick>=ActionBiasEndTick)return 0f;double p=Math.Max(0d,Math.Min(1d,tick/(double)ActionBiasEndTick));return Math.Max(1e-6f,(float)(.25d*(1d+Math.Cos(Math.PI*p))));}
    public static float ExplorationSigma(int updates){float p=Mathf.Clamp01(updates/(float)ExplorationDecayUpdates);return p>=1f?ExplorationFloorSigma:ExplorationStartSigma*Mathf.Pow(ExplorationFloorSigma/ExplorationStartSigma,p);}
    public static float BiasAction(float action,float strength,int parity,int step){if(strength<=0f)return Mathf.Clamp(action,-8f,8f);float sign=Mathf.Abs(action)>1e-7f?Mathf.Sign(action):(((parity+step)&1)==0?1f:-1f);return Mathf.Clamp(sign*Mathf.Lerp(Mathf.Abs(action),.75f,strength),-8f,8f);}
    private static float[,] ApplyActionBias(float[,] raw,NativeObservation o,float strength){var result=new float[5,MaxLimbs];for(int s=0;s<5;s++)for(int l=0;l<o.limbCount;l++){int parity=Mathf.RoundToInt((o.positionEncodings[l*2]+1f)*31f+(o.positionEncodings[l*2+1]+1f)*17f);result[s,l]=BiasAction(raw[s,l],strength,parity,s);}return result;}
    public static float[] JointFeatures(float angleDegrees,float speed){float a=angleDegrees*Mathf.Deg2Rad,w=Mathf.Clamp(speed/720f,-1f,1f);return new[]{Mathf.Sin(a),Mathf.Cos(a),w*Mathf.Cos(a),-w*Mathf.Sin(a)};}
    public static float[] JointPositionEncoding(int[] path,int slot){int hash=17;if(path!=null)foreach(int value in path)hash=unchecked(hash*31+value+1);hash=unchecked(hash*31+slot+1);float p=(hash&4095)*(2f*Mathf.PI/4096f);return new[]{Mathf.Sin(p),Mathf.Cos(p)};}
    public const float FixedGoalWorldHeight=WorldLayout.GroundTop+.5f;
    public static Vector2 FixedTrainingGoal(int tick)=>new Vector2(((Mathf.Max(0,tick)/GoalWindowTicks)&1)==0?CurriculumGoalMagnitude:-CurriculumGoalMagnitude,0f);
    public static int ClassifyWorldGoalDirection(float x)=>x<-.15f?-1:x>.15f?1:0;
    public static float BidirectionalFitness(float left,int ln,bool lc,float right,int rn,bool rc)=>ln<MinimumM2FitnessSamples||rn<MinimumM2FitnessSamples||!lc||!rc||!IsFinite(left)||!IsFinite(right)?float.PositiveInfinity:Mathf.Max(left,right);
    public static bool IsFinite(float value)=>!float.IsNaN(value)&&!float.IsInfinity(value);

    private void RecordFitness(float loss){if(!IsFinite(loss)||LatchedDirection==0)return;var q=LatchedDirection<0?leftLosses:rightLosses;q.Enqueue(loss);while(q.Count>M2FitnessWindow)q.Dequeue();}
    public void RecordMeasuredProgress(Vector2 d){if(LatchedDirection<0)LeftBestTrialProgress=Mathf.Max(LeftBestTrialProgress,-d.x);else if(LatchedDirection>0)RightBestTrialProgress=Mathf.Max(RightBestTrialProgress,d.x);}
    public void RepairFrom(NativeBrainWeights source){Weights.CopyFrom(source);M2Optimizer=new NativeOptimizerState();}
    public void CopyM3From(NativeBrainWeights source)=>Weights.CopyM3From(source);
    public NativeCreatureSave Capture()=>new NativeCreatureSave{weights=Weights,m2Optimizer=M2Optimizer,goalX=CurrentGoal.x,goalY=CurrentGoal.y,worldGoalX=CurrentWorldGoal.x,worldGoalY=CurrentWorldGoal.y,goalTicksRemaining=GoalTicksRemaining,fixedGoalBlock=fixedGoalBlock,m1AnchorX=m1GoalAnchor.x,m1AnchorY=m1GoalAnchor.y,m1AnchorInitialized=m1GoalAnchorInitialized,explorationState=exploration.State,leftLosses=leftLosses.ToList(),rightLosses=rightLosses.ToList(),leftBestProgress=LeftBestTrialProgress,rightBestProgress=RightBestTrialProgress};
    public void Restore(NativeCreatureSave save){if(save==null)return;M2Optimizer=save.m2Optimizer??new NativeOptimizerState();CurrentGoal=new Vector2(save.goalX,save.goalY);CurrentWorldGoal=new Vector2(save.worldGoalX,save.worldGoalY);GoalTicksRemaining=save.goalTicksRemaining;fixedGoalBlock=save.fixedGoalBlock;m1GoalAnchor=new Vector2(save.m1AnchorX,save.m1AnchorY);m1GoalAnchorInitialized=save.m1AnchorInitialized;hasGoal=true;exploration.State=save.explorationState;leftLosses.Clear();rightLosses.Clear();foreach(float v in (save.leftLosses??new List<float>()).TakeLast(M2FitnessWindow))leftLosses.Enqueue(v);foreach(float v in (save.rightLosses??new List<float>()).TakeLast(M2FitnessWindow))rightLosses.Enqueue(v);LeftBestTrialProgress=save.leftBestProgress;RightBestTrialProgress=save.rightBestProgress;}

    private Vector2 RunM1(float[] input){var a=ForwardDense(input,Weights.m1Input,Weights.m1Bias,0,M1InputSize,Hidden,true).output;var b=ForwardDense(a,Weights.m1Residual,Weights.m1Bias,Hidden,Hidden,Hidden,true).output;for(int i=0;i<Hidden;i++)a[i]=(float)Math.Tanh(a[i]+b[i]);var o=ForwardDense(a,Weights.m1Output,Weights.m1Bias,Hidden*2,Hidden,2,false).output;return new Vector2((float)Math.Tanh(o[0]),(float)Math.Tanh(o[1]));}
    private static Vector2 SoftBiasedGoal(Vector2 raw){float m=Mathf.Clamp01(raw.magnitude);Vector2 d=m>.0001f?raw/m:Vector2.right;return d*(.35f+.65f*m);}
    private static float[] TorsoFeatures(NativeLocalProprioception p,Vector2 goal,bool includeGoal){float a=p.worldRotationDegrees*Mathf.Deg2Rad;return includeGoal?new[]{p.worldPosition.x/WorldLayout.WorldHalfWidth,p.worldPosition.y/WorldLayout.SpawnRowSpacing,p.localLinearVelocity.x,p.localLinearVelocity.y,Mathf.Sin(a),Mathf.Cos(a),goal.x,goal.y}:new[]{p.worldPosition.x/WorldLayout.WorldHalfWidth,p.worldPosition.y/WorldLayout.SpawnRowSpacing,p.localLinearVelocity.x,p.localLinearVelocity.y,Mathf.Sin(a),Mathf.Cos(a)};}
    private float Gaussian(){float a=Mathf.Max(1e-7f,exploration.NextFloat()),b=exploration.NextFloat();return Mathf.Sqrt(-2f*Mathf.Log(a))*Mathf.Cos(2f*Mathf.PI*b);}
    private static float Mean(IEnumerable<float> values){int n=0;float sum=0f;foreach(float v in values){sum+=v;n++;}return n==0?float.PositiveInfinity:sum/n;}

    private static M2Cache ForwardM2(NativeObservation o,NativeBrainWeights w)
    {
        var c=new M2Cache{observation=o,context=ForwardDense(o.torsoWithGoal,w.m2Context,w.m2Bias,0,M2ContextSize,Hidden,true),limbs=new JointCache[o.limbCount],actions=new float[5,MaxLimbs]};float[][] tokens=new float[o.limbCount][];
        for(int l=0;l<o.limbCount;l++){c.limbs[l]=ForwardJoint(Slice(o.jointFeatures,l*4,4),Slice(o.positionEncodings,l*2,2),w.m2Joint,w.m2Position,w.m2Bias,Hidden);tokens[l]=c.limbs[l].output;}
        c.attention=ForwardAttention(tokens,w.m2AttentionQuery,w.m2AttentionKey,w.m2AttentionValue,M2AttentionHeads);c.attention2=ForwardAttention(c.attention.output,w.m2AttentionQuery2,w.m2AttentionKey2,w.m2AttentionValue2,M2AttentionHeads);c.heads=new HeadCache[o.limbCount];
        for(int l=0;l<o.limbCount;l++){c.heads[l]=ForwardHead(Concat(c.attention2.output[l],c.context.output),w.m2Fusion,w.m2Residual,new[]{w.m2Deep1,w.m2Deep2,w.m2Deep3},w.m2Output,w.m2Bias,5,8f);for(int s=0;s<5;s++)c.actions[s,l]=c.heads[l].output[s];}return c;
    }
    private static void BackwardM2(M2Cache c,float[,] actionGradient,NativeBrainWeights w,Dictionary<string,float[]> g)
    {
        float[][] attentionGradient=Enumerable.Range(0,c.observation.limbCount).Select(_=>new float[Hidden]).ToArray();float[] contextGradient=new float[Hidden];
        for(int l=0;l<c.observation.limbCount;l++){float[] og=new float[5];for(int s=0;s<5;s++)og[s]=actionGradient[s,l];float[] fg=BackwardHead(c.heads[l],og,w.m2Fusion,w.m2Residual,new[]{w.m2Deep1,w.m2Deep2,w.m2Deep3},w.m2Output,g["fusion"],g["residual"],new[]{g["deep1"],g["deep2"],g["deep3"]},g["output"],g["bias"]);Array.Copy(fg,attentionGradient[l],Hidden);for(int h=0;h<Hidden;h++)contextGradient[h]+=fg[Hidden+h];}
        float[][] firstBlockGradient=BackwardAttention(c.attention2,attentionGradient,w.m2AttentionQuery2,w.m2AttentionKey2,w.m2AttentionValue2,g["attentionQuery2"],g["attentionKey2"],g["attentionValue2"]);float[][] tg=BackwardAttention(c.attention,firstBlockGradient,w.m2AttentionQuery,w.m2AttentionKey,w.m2AttentionValue,g["attentionQuery"],g["attentionKey"],g["attentionValue"]);for(int l=0;l<c.observation.limbCount;l++)BackwardJoint(c.limbs[l],tg[l],w.m2Joint,w.m2Position,g["joint"],g["position"],g["bias"],Hidden);BackwardDense(c.context,contextGradient,w.m2Context,g["context"],g["bias"]);
    }
    private static M3Cache ForwardM3(NativeObservation o,float[,] actions,NativeBrainWeights w)
    {
        var c=new M3Cache{observation=o,actions=actions,context=ForwardDense(o.torsoWithoutGoal,w.m3Context,w.m3Bias,0,M3ContextSize,Hidden,true),limbs=new JointCache[o.limbCount]};float[][] tokens=new float[o.limbCount][];
        for(int l=0;l<o.limbCount;l++){float[] input=new float[9];Array.Copy(o.jointFeatures,l*4,input,0,4);for(int s=0;s<5;s++)input[4+s]=actions[s,l]/8f;c.limbs[l]=ForwardJoint(input,Slice(o.positionEncodings,l*2,2),w.m3Joint,w.m3Position,w.m3Bias,Hidden);tokens[l]=c.limbs[l].output;}
        c.attention=ForwardAttention(tokens,w.m3AttentionQuery,w.m3AttentionKey,w.m3AttentionValue,M3AttentionHeads);c.attention2=ForwardAttention(c.attention.output,w.m3AttentionQuery2,w.m3AttentionKey2,w.m3AttentionValue2,M3AttentionHeads);c.head=ForwardHead(Concat(MeanTokens(c.attention2.output),c.context.output),w.m3Fusion,w.m3Residual,new[]{w.m3Deep1,w.m3Deep2,w.m3Deep3},w.m3Output,w.m3Bias,10,1f);c.prediction=c.head.output;return c;
    }
    private static float[,] BackwardM3(M3Cache c,float[] outputGradient,NativeBrainWeights w,Dictionary<string,float[]> supplied)
    {
        var g=supplied??Zero(w.M3Parameters());float[] fg=BackwardHead(c.head,outputGradient,w.m3Fusion,w.m3Residual,new[]{w.m3Deep1,w.m3Deep2,w.m3Deep3},w.m3Output,g["fusion"],g["residual"],new[]{g["deep1"],g["deep2"],g["deep3"]},g["output"],g["bias"]);float[][] ag=Enumerable.Range(0,c.observation.limbCount).Select(_=>new float[Hidden]).ToArray();for(int l=0;l<c.observation.limbCount;l++)for(int h=0;h<Hidden;h++)ag[l][h]=fg[h]/Mathf.Max(1,c.observation.limbCount);
        float[][] firstBlockGradient=BackwardAttention(c.attention2,ag,w.m3AttentionQuery2,w.m3AttentionKey2,w.m3AttentionValue2,g["attentionQuery2"],g["attentionKey2"],g["attentionValue2"]);float[][] tg=BackwardAttention(c.attention,firstBlockGradient,w.m3AttentionQuery,w.m3AttentionKey,w.m3AttentionValue,g["attentionQuery"],g["attentionKey"],g["attentionValue"]);float[,] result=new float[5,MaxLimbs];for(int l=0;l<c.observation.limbCount;l++){float[] ig=BackwardJoint(c.limbs[l],tg[l],w.m3Joint,w.m3Position,g["joint"],g["position"],g["bias"],Hidden);for(int s=0;s<5;s++)result[s,l]=ig[4+s]/8f;}BackwardDense(c.context,Slice(fg,Hidden,Hidden),w.m3Context,g["context"],g["bias"]);return result;
    }

    private static JointCache ForwardJoint(float[] input,float[] position,float[] iw,float[] pw,float[] bias,int offset){var c=new JointCache{input=input,position=position,output=new float[Hidden]};for(int h=0;h<Hidden;h++){float v=bias[offset+h];for(int i=0;i<input.Length;i++)v+=input[i]*iw[i*Hidden+h];for(int i=0;i<2;i++)v+=position[i]*pw[i*Hidden+h];c.output[h]=(float)Math.Tanh(v);}return c;}
    private static float[] BackwardJoint(JointCache c,float[] og,float[] iw,float[] pw,float[] iwg,float[] pwg,float[] bg,int offset){float[] ig=new float[c.input.Length];for(int h=0;h<Hidden;h++){float g=og[h]*(1f-c.output[h]*c.output[h]);bg[offset+h]+=g;for(int i=0;i<c.input.Length;i++){iwg[i*Hidden+h]+=c.input[i]*g;ig[i]+=iw[i*Hidden+h]*g;}for(int i=0;i<2;i++)pwg[i*Hidden+h]+=c.position[i]*g;}return ig;}
    private static AttentionCache ForwardAttention(float[][] input,float[] qw,float[] kw,float[] vw,int heads)
    {
        int n=input.Length;var c=new AttentionCache{input=input,q=new float[n][],k=new float[n][],v=new float[n][],output=new float[n][],probability=new float[heads,n,n],heads=heads};for(int i=0;i<n;i++){c.q[i]=Linear(input[i],qw);c.k[i]=Linear(input[i],kw);c.v[i]=Linear(input[i],vw);c.output[i]=new float[Hidden];}
        for(int head=0;head<heads;head++){int start=AttentionHeadStart(head,heads),headWidth=AttentionHeadWidth(head,heads);float scale=1f/Mathf.Sqrt(headWidth);for(int i=0;i<n;i++){float max=float.NegativeInfinity,sum=0f;float[] scores=new float[n];for(int j=0;j<n;j++){float dot=0f;for(int h=0;h<headWidth;h++)dot+=c.q[i][start+h]*c.k[j][start+h];scores[j]=dot*scale;max=Mathf.Max(max,scores[j]);}for(int j=0;j<n;j++){c.probability[head,i,j]=Mathf.Exp(Mathf.Clamp(scores[j]-max,-20f,20f));sum+=c.probability[head,i,j];}for(int j=0;j<n;j++)c.probability[head,i,j]/=Mathf.Max(1e-8f,sum);for(int h=0;h<headWidth;h++){int index=start+h;float value=input[i][index];for(int j=0;j<n;j++)value+=c.probability[head,i,j]*c.v[j][index];c.output[i][index]=(float)Math.Tanh(value);}}}return c;
    }
    private static float[][] BackwardAttention(AttentionCache c,float[][] og,float[] qw,float[] kw,float[] vw,float[] qwg,float[] kwg,float[] vwg)
    {
        int n=c.input.Length;float[][] ig=Enumerable.Range(0,n).Select(_=>new float[Hidden]).ToArray(),qg=Enumerable.Range(0,n).Select(_=>new float[Hidden]).ToArray(),kg=Enumerable.Range(0,n).Select(_=>new float[Hidden]).ToArray(),vg=Enumerable.Range(0,n).Select(_=>new float[Hidden]).ToArray();float[,,] pg=new float[c.heads,n,n];
        for(int head=0;head<c.heads;head++){int start=AttentionHeadStart(head,c.heads),headWidth=AttentionHeadWidth(head,c.heads);for(int i=0;i<n;i++)for(int h=0;h<headWidth;h++){int index=start+h;float gradient=og[i][index]*(1f-c.output[i][index]*c.output[i][index]);ig[i][index]+=gradient;for(int j=0;j<n;j++){pg[head,i,j]+=gradient*c.v[j][index];vg[j][index]+=gradient*c.probability[head,i,j];}}}
        for(int head=0;head<c.heads;head++){int start=AttentionHeadStart(head,c.heads),headWidth=AttentionHeadWidth(head,c.heads);float scale=1f/Mathf.Sqrt(headWidth);for(int i=0;i<n;i++){float mean=0f;for(int j=0;j<n;j++)mean+=pg[head,i,j]*c.probability[head,i,j];for(int j=0;j<n;j++){float scoreGradient=c.probability[head,i,j]*(pg[head,i,j]-mean)*scale;for(int h=0;h<headWidth;h++){int index=start+h;qg[i][index]+=scoreGradient*c.k[j][index];kg[j][index]+=scoreGradient*c.q[i][index];}}}}
        for(int i=0;i<n;i++){BackwardLinear(c.input[i],qg[i],qw,qwg,ig[i]);BackwardLinear(c.input[i],kg[i],kw,kwg,ig[i]);BackwardLinear(c.input[i],vg[i],vw,vwg,ig[i]);}return ig;
    }
    private static HeadCache ForwardHead(float[] input,float[] fw,float[] rw,float[][] deep,float[] ow,float[] bias,int outputCount,float scale){var c=new HeadCache{fusion=ForwardDense(input,fw,bias,Hidden*2,Hidden*2,Hidden,true),outputScale=scale};c.residual=ForwardDense(c.fusion.output,rw,bias,Hidden*3,Hidden,Hidden,true);c.merged=new float[Hidden];for(int h=0;h<Hidden;h++)c.merged[h]=(float)Math.Tanh(c.fusion.output[h]+c.residual.output[h]);c.deepLayers=new DenseCache[deep.Length];float[] current=c.merged;for(int i=0;i<deep.Length;i++){c.deepLayers[i]=ForwardDense(current,deep[i],bias,Hidden*(4+i),Hidden,Hidden,true);current=c.deepLayers[i].output;}c.outputLayer=ForwardDense(current,ow,bias,Hidden*(4+deep.Length),Hidden,outputCount,false);c.output=new float[outputCount];for(int i=0;i<outputCount;i++)c.output[i]=(float)Math.Tanh(c.outputLayer.pre[i])*scale;return c;}
    private static float[] BackwardHead(HeadCache c,float[] og,float[] fw,float[] rw,float[][] deep,float[] ow,float[] fwg,float[] rwg,float[][] deepg,float[] owg,float[] bg){float[] pg=new float[og.Length];for(int i=0;i<og.Length;i++){float t=c.output[i]/c.outputScale;pg[i]=og[i]*c.outputScale*(1f-t*t);}float[] mg=BackwardDense(c.outputLayer,pg,ow,owg,bg);for(int i=c.deepLayers.Length-1;i>=0;i--)mg=BackwardDense(c.deepLayers[i],mg,deep[i],deepg[i],bg);float[] fg=new float[Hidden],rg=new float[Hidden];for(int h=0;h<Hidden;h++){float gradient=mg[h]*(1f-c.merged[h]*c.merged[h]);fg[h]=gradient;rg[h]=gradient;}float[] extra=BackwardDense(c.residual,rg,rw,rwg,bg);for(int h=0;h<Hidden;h++)fg[h]+=extra[h];return BackwardDense(c.fusion,fg,fw,fwg,bg);}
    private static DenseCache ForwardDense(float[] input,float[] weights,float[] bias,int offset,int inputCount,int outputCount,bool activate){var c=new DenseCache{input=input,pre=new float[outputCount],output=new float[outputCount],biasOffset=offset,activate=activate};for(int o=0;o<outputCount;o++){float v=bias[offset+o];for(int i=0;i<inputCount;i++)v+=input[i]*weights[i*outputCount+o];c.pre[o]=v;c.output[o]=activate?(float)Math.Tanh(v):v;}return c;}
    private static float[] BackwardDense(DenseCache c,float[] og,float[] weights,float[] wg,float[] bg){int outputs=og.Length;float[] ig=new float[c.input.Length];for(int o=0;o<outputs;o++){float g=og[o]*(c.activate?1f-c.output[o]*c.output[o]:1f);bg[c.biasOffset+o]+=g;for(int i=0;i<c.input.Length;i++){wg[i*outputs+o]+=c.input[i]*g;ig[i]+=weights[i*outputs+o]*g;}}return ig;}
    private static Dictionary<string,float[]> Zero(IEnumerable<KeyValuePair<string,float[]>> parameters){var g=new Dictionary<string,float[]>();foreach(var p in parameters)g[p.Key]=new float[p.Value.Length];return g;}
    private static void ApplyAdam(IEnumerable<KeyValuePair<string,float[]>> parameters,Dictionary<string,float[]> gradients,NativeOptimizerState optimizer,float learningRate){float norm2=gradients.Values.Sum(a=>a.Sum(v=>v*v)),clip=1f/Mathf.Max(1f,Mathf.Sqrt(norm2));optimizer.step++;foreach(var p in parameters){var slot=optimizer.Get(p.Key,p.Value.Length);float[] g=gradients[p.Key];for(int i=0;i<p.Value.Length;i++){float v=g[i]*clip;slot.first[i]=.9f*slot.first[i]+.1f*v;slot.second[i]=.999f*slot.second[i]+.001f*v*v;float mh=slot.first[i]/(1f-Mathf.Pow(.9f,optimizer.step)),vh=slot.second[i]/(1f-Mathf.Pow(.999f,optimizer.step));p.Value[i]-=learningRate*mh/(Mathf.Sqrt(vh)+1e-8f);}}}
    private static float[] Linear(float[] input,float[] weights){float[] o=new float[Hidden];for(int i=0;i<Hidden;i++)for(int h=0;h<Hidden;h++)o[h]+=input[i]*weights[i*Hidden+h];return o;}
    private static int AttentionHeadStart(int head,int heads)=>head*Hidden/heads;
    private static int AttentionHeadWidth(int head,int heads)=>(head+1)*Hidden/heads-AttentionHeadStart(head,heads);
    private static void BackwardLinear(float[] input,float[] og,float[] weights,float[] wg,float[] ig){for(int i=0;i<Hidden;i++)for(int h=0;h<Hidden;h++){wg[i*Hidden+h]+=input[i]*og[h];ig[i]+=weights[i*Hidden+h]*og[h];}}
    private static float Dot(float[] a,float[] b){float v=0f;for(int i=0;i<a.Length;i++)v+=a[i]*b[i];return v;}
    private static float[] Slice(float[] a,int start,int count){float[] r=new float[count];Array.Copy(a,start,r,0,count);return r;}
    private static float[] Concat(float[] a,float[] b){float[] r=new float[a.Length+b.Length];Array.Copy(a,r,a.Length);Array.Copy(b,0,r,a.Length,b.Length);return r;}
    private static float[] MeanTokens(float[][] tokens){float[] r=new float[Hidden];if(tokens.Length==0)return r;foreach(float[] t in tokens)for(int h=0;h<Hidden;h++)r[h]+=t[h]/tokens.Length;return r;}
}

[Serializable] public sealed class NativeOptimizerSlot{public string name;public float[] first,second;}
[Serializable] public sealed class NativeDeterministicRng{public ulong State;public NativeDeterministicRng(ulong seed){State=seed==0?1UL:seed;}public float NextFloat(){State^=State<<13;State^=State>>7;State^=State<<17;return (State&0xFFFFFF)/(float)0x1000000;}}
[Serializable] public sealed class NativeOptimizerState{public int step;public List<NativeOptimizerSlot> slots=new List<NativeOptimizerSlot>();public NativeOptimizerSlot Get(string name,int length){var s=slots.FirstOrDefault(v=>v.name==name);if(s==null){s=new NativeOptimizerSlot{name=name};slots.Add(s);}if(s.first==null||s.first.Length!=length)s.first=new float[length];if(s.second==null||s.second.Length!=length)s.second=new float[length];return s;}}
[Serializable] public sealed class NativeObservation
{
    public float[] torsoWithGoal,torsoWithoutGoal,jointFeatures,positionEncodings;
    public int limbCount,tick;
    public float goalX,goalY,worldGoalX,worldGoalY,startWorldX,startWorldY,startWorldRotationDegrees;
    [JsonIgnore] public Vector2 goal{get=>new Vector2(goalX,goalY);set{goalX=value.x;goalY=value.y;}}
    [JsonIgnore] public Vector2 worldGoal{get=>new Vector2(worldGoalX,worldGoalY);set{worldGoalX=value.x;worldGoalY=value.y;}}
    [JsonIgnore] public Vector2 startWorldPosition{get=>new Vector2(startWorldX,startWorldY);set{startWorldX=value.x;startWorldY=value.y;}}
}
public sealed class NativePositionPrediction{public readonly float[] positions;public NativePositionPrediction(float[] values){positions=values??new float[10];}public Vector2 At(int step)=>new Vector2(positions[step*2],positions[step*2+1]);}
public sealed class NativeActionSequence{public readonly float[,] actions;public readonly int limbCount;public readonly Vector2 goal,worldGoal;public readonly NativePositionPrediction prediction;public readonly float biasStrength,explorationSigma;public NativeActionSequence(float[,] a,int count,Vector2 g,Vector2 wg,NativePositionPrediction p,float b,float s){actions=a;limbCount=count;goal=g;worldGoal=wg;prediction=p;biasStrength=b;explorationSigma=s;}public float[] ActionAt(int step){float[] r=new float[NativeCreatureModel.MaxLimbs];for(int i=0;i<limbCount;i++)r[i]=actions[step,i];return r;}}
[Serializable] public sealed class NativeCompletedSequence{public NativeObservation observation;public float[] actions,actualPositions;public float[,] ActionMatrix(){var result=new float[NativeCreatureModel.PlanningHorizon,NativeCreatureModel.MaxLimbs];if(actions==null)return result;for(int s=0;s<NativeCreatureModel.PlanningHorizon;s++)for(int l=0;l<NativeCreatureModel.MaxLimbs;l++){int i=s*NativeCreatureModel.MaxLimbs+l;if(i<actions.Length)result[s,l]=actions[i];}return result;}}
public struct NativeLocalProprioception{public Vector2 worldPosition,localLinearVelocity;public float worldRotationDegrees;public Vector2 WorldToTorsoVector(Vector2 worldVector)=>Quaternion.Euler(0f,0f,-worldRotationDegrees)*worldVector;}
[Serializable] public sealed class NativeCreatureSave{public NativeBrainWeights weights;public NativeOptimizerState m2Optimizer;public float goalX,goalY,worldGoalX,worldGoalY,m1AnchorX,m1AnchorY;public int goalTicksRemaining,fixedGoalBlock;public bool m1AnchorInitialized;public ulong explorationState;public List<float> leftLosses,rightLosses;public float leftBestProgress,rightBestProgress;}
[Serializable] public sealed class NativeCreatureCheckpoint{public string creatureId,speciesId,m1SpeciesId,bodyGenomeJson;public NativeCreatureSave brain;public float bodyFitness,deathPenalty,m1EnergyFitness,previousEnergy;public bool deathRecorded,protectedOffspring;public int bodyAgeGenerations,temporaryGoalRewardBlock;}
[Serializable] public sealed class NativeEcosystemCheckpoint{public int schema=13;public const string ConfigurationFingerprint="native-v13-openloop-h5-a4-ff32-m2h4-t2-mlp5-m3h8-t2-mlp5-m1worldanchor-localpos-m2goal-m3direct10-antizero4-bias075t13333-temporarygoalreward";public string configuration=ConfigurationFingerprint;public int tick,generation,controlStep,specialistSelectionCursor,sharedM3Updates;public string experimentId;public long randomState,nextEvolutionTicks;public NativeBrainWeights sharedWeights;public NativeOptimizerState m3Optimizer;public List<NativeCompletedSequence> validation=new List<NativeCompletedSequence>();public List<NativeCreatureCheckpoint> creatures=new List<NativeCreatureCheckpoint>();public static bool IsCompatibleConfiguration(string value)=>value==ConfigurationFingerprint;}
internal sealed class DenseCache{public float[] input,pre,output;public int biasOffset;public bool activate;}
internal sealed class JointCache{public float[] input,position,output;}
internal sealed class AttentionCache{public float[][] input,q,k,v,output;public float[,,] probability;public int heads;}
internal sealed class HeadCache{public DenseCache fusion,residual,outputLayer;public DenseCache[] deepLayers;public float[] merged,output;public float outputScale;}
internal sealed class M2Cache{public NativeObservation observation;public DenseCache context;public JointCache[] limbs;public AttentionCache attention,attention2;public HeadCache[] heads;public float[,] actions;}
internal sealed class M3Cache{public NativeObservation observation;public float[,] actions;public DenseCache context;public JointCache[] limbs;public AttentionCache attention,attention2;public HeadCache head;public float[] prediction;}
