using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;

public static class NativeTensorCheckpointStore
{
    private const int Magic=0x4E543230;

    public static void Write(string path,NativeEcosystemCheckpoint checkpoint)
    {
        using(var stream=new FileStream(path,FileMode.Create,FileAccess.Write,FileShare.None))
        using(var writer=new BinaryWriter(stream,Encoding.UTF8,true))
        {
            writer.Write(Magic);writer.Write(26);writer.Write(NativeEcosystemCheckpoint.ConfigurationFingerprint);WriteShared(writer,checkpoint.sharedLearning);WriteMovement(writer,checkpoint.movementLearning);
            writer.Write(checkpoint.creatures.Count);
            foreach(NativeCreatureCheckpoint creature in checkpoint.creatures){writer.Write(creature.creatureId??string.Empty);WriteParameters(writer,PolicyParameters(creature.brain.weights));WriteOptimizer(writer,creature.brain.m2Optimizer,creature.brain.weights.M2Parameters());WriteProtection(writer,creature.brain.m2Protection,creature.brain.weights.M2Parameters());WriteOptionalM2State(writer,creature.curriculum?.qualificationLearningState,creature.curriculum?.qualificationSnapshot);WriteOptionalM2State(writer,creature.curriculum?.validatedLearningState,creature.curriculum?.validatedSnapshot);NativeM3LearningState m3=creature.m3??new NativeM3LearningState{dynamics=NativeDynamicsWeights.Create(7331)};WriteParameters(writer,m3.dynamics.Parameters());WriteOptimizer(writer,m3.optimizer,m3.dynamics.Parameters());WriteProtection(writer,m3.protection,m3.dynamics.Parameters());writer.Write(m3.freshSequences);writer.Write(m3.optimizerSteps);writer.Write(m3.lastResultTick);WriteReplay(writer,m3.replay.samples);WriteReplay(writer,m3.validation);}
            writer.Flush();stream.Flush(true);
        }
    }

    public static void Read(string path,NativeEcosystemCheckpoint checkpoint)
    {
        using(var stream=new FileStream(path,FileMode.Open,FileAccess.Read,FileShare.Read))
        using(var reader=new BinaryReader(stream,Encoding.UTF8,true))
        {
            if(reader.ReadInt32()!=Magic||reader.ReadInt32()!=26||reader.ReadString()!=NativeEcosystemCheckpoint.ConfigurationFingerprint)throw new InvalidDataException("v26 tensor header mismatch");checkpoint.sharedLearning=ReadShared(reader);checkpoint.movementLearning=ReadMovement(reader);
            int count=reader.ReadInt32();if(count!=checkpoint.creatures.Count)throw new InvalidDataException("v26 tensor creature count mismatch");
            var byId=checkpoint.creatures.ToDictionary(c=>c.creatureId??string.Empty,StringComparer.Ordinal);
            for(int i=0;i<count;i++){string id=reader.ReadString();if(!byId.TryGetValue(id,out NativeCreatureCheckpoint creature))throw new InvalidDataException("v26 tensor creature identity mismatch");creature.brain=creature.brain??new NativeCreatureSave();creature.brain.weights=NativeBrainWeights.Create(1800+i);ReadParameters(reader,PolicyParameters(creature.brain.weights));creature.brain.m2Optimizer=creature.brain.m2Optimizer??new NativeOptimizerState();ReadOptimizer(reader,creature.brain.m2Optimizer,creature.brain.weights.M2Parameters());creature.brain.m2Protection=creature.brain.m2Protection??new NativeSynapticIntelligence();ReadProtection(reader,creature.brain.m2Protection,creature.brain.weights.M2Parameters());creature.curriculum=creature.curriculum??new NativeCurriculumState();creature.curriculum.qualificationLearningState=ReadOptionalM2State(reader,creature.curriculum.qualificationLearningState,1900+i,out NativeBrainWeights qualification);creature.curriculum.qualificationSnapshot=qualification;creature.curriculum.validatedLearningState=ReadOptionalM2State(reader,creature.curriculum.validatedLearningState,2000+i,out NativeBrainWeights validated);creature.curriculum.validatedSnapshot=validated;creature.m3=new NativeM3LearningState{dynamics=NativeDynamicsWeights.Create(7331+i),optimizer=new NativeOptimizerState(),protection=new NativeSynapticIntelligence()};ReadParameters(reader,creature.m3.dynamics.Parameters());ReadOptimizer(reader,creature.m3.optimizer,creature.m3.dynamics.Parameters());ReadProtection(reader,creature.m3.protection,creature.m3.dynamics.Parameters());creature.m3.freshSequences=reader.ReadInt32();creature.m3.optimizerSteps=reader.ReadInt32();creature.m3.lastResultTick=reader.ReadInt32();creature.m3.replay.samples=ReadReplay(reader);creature.m3.replay.RebuildIndex();creature.m3.validation=ReadReplay(reader);}
            if(stream.Position!=stream.Length)throw new InvalidDataException("v26 tensor file has trailing bytes");
        }
    }

    public static string Sha256(string path){using(var sha=SHA256.Create())using(var stream=File.OpenRead(path)){byte[] hash=sha.ComputeHash(stream);return string.Concat(hash.Select(b=>b.ToString("x2")));}}
    public static void ValidateFileName(string fileName){if(string.IsNullOrWhiteSpace(fileName)||Path.GetFileName(fileName)!=fileName||!fileName.StartsWith("native_ecosystem_v26.",StringComparison.Ordinal)||!fileName.EndsWith(".bin",StringComparison.Ordinal))throw new InvalidDataException("Unsafe v26 tensor filename");}

    private static void WriteShared(BinaryWriter writer,NativeSharedLearningState value)
    {
        value=value??new NativeSharedLearningState{m2=NativeBrainWeights.Create(7331),m3=new NativeM3LearningState{dynamics=NativeDynamicsWeights.Create(7332)}};WriteParameters(writer,value.m2.M2Parameters());WriteOptimizer(writer,value.m2Optimizer,value.m2.M2Parameters());WriteProtection(writer,value.m2Protection,value.m2.M2Parameters());WriteParameters(writer,value.m3.dynamics.Parameters());WriteOptimizer(writer,value.m3.optimizer,value.m3.dynamics.Parameters());WriteProtection(writer,value.m3.protection,value.m3.dynamics.Parameters());writer.Write(value.m3.freshSequences);writer.Write(value.m3.optimizerSteps);writer.Write(value.m3.lastResultTick);writer.Write(value.modelVersion);WriteReplay(writer,value.m3.replay.samples);WriteReplay(writer,value.m3.usefulReplay.samples);WriteReplay(writer,value.m3.validation);
    }
    private static NativeSharedLearningState ReadShared(BinaryReader reader)
    {
        var value=new NativeSharedLearningState{m2=NativeBrainWeights.Create(7331),m3=new NativeM3LearningState{dynamics=NativeDynamicsWeights.Create(7332)}};ReadParameters(reader,value.m2.M2Parameters());ReadOptimizer(reader,value.m2Optimizer,value.m2.M2Parameters());ReadProtection(reader,value.m2Protection,value.m2.M2Parameters());ReadParameters(reader,value.m3.dynamics.Parameters());ReadOptimizer(reader,value.m3.optimizer,value.m3.dynamics.Parameters());ReadProtection(reader,value.m3.protection,value.m3.dynamics.Parameters());value.m3.freshSequences=reader.ReadInt32();value.m3.optimizerSteps=reader.ReadInt32();value.m3.lastResultTick=reader.ReadInt32();value.modelVersion=reader.ReadInt32();value.m3.replay.samples=ReadReplay(reader);value.m3.replay.RebuildIndex();value.m3.usefulReplay.samples=ReadReplay(reader);value.m3.usefulReplay.RebuildIndex();value.m3.validation=ReadReplay(reader);return value;
    }

    private static void WriteMovement(BinaryWriter writer,NativeMovementLearningState value)
    {
        value=value??new NativeMovementLearningState{weights=NativeMovementWeights.Create(26001)};WriteParameters(writer,value.weights.Parameters());WriteOptimizer(writer,value.optimizer,value.weights.Parameters());writer.Write(value.qualifiedWeights!=null);if(value.qualifiedWeights!=null){WriteParameters(writer,value.qualifiedWeights.Parameters());WriteOptimizer(writer,value.qualifiedOptimizer??new NativeOptimizerState(),value.qualifiedWeights.Parameters());}writer.Write(value.modelVersion);writer.Write(value.policyUpdates);writer.Write(value.m3Updates);writer.Write(value.freshTransitions);writer.Write(value.randomState);writer.Write(value.curiosityReady);writer.Write(value.simpleBodyQualified);WriteMovementReplay(writer,value.recent);WriteMovementReplay(writer,value.progress);WriteMovementReplay(writer,value.contact);WriteMovementReplay(writer,value.imitation);WriteMovementReplay(writer,value.validation);
    }
    private static NativeMovementLearningState ReadMovement(BinaryReader reader)
    {
        var value=new NativeMovementLearningState{weights=NativeMovementWeights.Create(26001)};ReadParameters(reader,value.weights.Parameters());ReadOptimizer(reader,value.optimizer,value.weights.Parameters());if(reader.ReadBoolean()){value.qualifiedWeights=NativeMovementWeights.Create(26002);ReadParameters(reader,value.qualifiedWeights.Parameters());value.qualifiedOptimizer=new NativeOptimizerState();ReadOptimizer(reader,value.qualifiedOptimizer,value.qualifiedWeights.Parameters());}value.modelVersion=reader.ReadInt32();value.policyUpdates=reader.ReadInt32();value.m3Updates=reader.ReadInt32();value.freshTransitions=reader.ReadInt32();value.randomState=reader.ReadUInt64();value.curiosityReady=reader.ReadBoolean();value.simpleBodyQualified=reader.ReadBoolean();value.recent=ReadMovementReplay(reader,4096);value.progress=ReadMovementReplay(reader,1024);value.contact=ReadMovementReplay(reader,1024);value.imitation=ReadMovementReplay(reader,1024);value.validation=ReadMovementReplay(reader,256);return value;
    }
    private static void WriteMovementReplay(BinaryWriter writer,List<NativeMovementTransition> transitions){transitions=transitions??new List<NativeMovementTransition>();writer.Write(transitions.Count);foreach(var t in transitions){writer.Write(t.sampleId??string.Empty);writer.Write(t.controllerId??string.Empty);writer.Write(t.bodySignature??string.Empty);WriteMovementObservation(writer,t.observation);WriteMovementObservation(writer,t.nextObservation);WriteDecision(writer,t.decision);WriteArray(writer,t.measuredJointMovement??new float[NativeCreatureModel.MaxLimbs]);foreach(float v in new[]{t.reward,t.travelReward,t.effortPenalty,t.curiosityReward,t.torsoDeltaX,t.torsoDeltaY,t.headingDelta,t.angularVelocityDelta})writer.Write(v);writer.Write(t.terminal);writer.Write(t.contactTransition);writer.Write(t.evaluation);writer.Write(t.episode);writer.Write(t.horizonSteps);}}
    private static List<NativeMovementTransition> ReadMovementReplay(BinaryReader reader,int capacity){int count=reader.ReadInt32();if(count<0||count>capacity)throw new InvalidDataException("v26 movement replay capacity invalid");var list=new List<NativeMovementTransition>(count);for(int i=0;i<count;i++){var t=new NativeMovementTransition{sampleId=reader.ReadString(),controllerId=reader.ReadString(),bodySignature=reader.ReadString(),observation=ReadMovementObservation(reader),nextObservation=ReadMovementObservation(reader),decision=ReadDecision(reader),measuredJointMovement=ReadArray(reader,NativeCreatureModel.MaxLimbs)};t.reward=reader.ReadSingle();t.travelReward=reader.ReadSingle();t.effortPenalty=reader.ReadSingle();t.curiosityReward=reader.ReadSingle();t.torsoDeltaX=reader.ReadSingle();t.torsoDeltaY=reader.ReadSingle();t.headingDelta=reader.ReadSingle();t.angularVelocityDelta=reader.ReadSingle();t.terminal=reader.ReadBoolean();t.contactTransition=reader.ReadBoolean();t.evaluation=reader.ReadBoolean();t.episode=reader.ReadInt32();t.horizonSteps=reader.ReadInt32();list.Add(t);}return list;}
    private static void WriteMovementObservation(BinaryWriter writer,NativeMovementObservation o){if(o==null)throw new InvalidDataException("Cannot persist null v26 observation");writer.Write(o.history?.Length??0);foreach(NativeObservation frame in o.history??Array.Empty<NativeObservation>()){WriteObservation(writer,frame);WriteArray(writer,frame.limbMask??new float[NativeCreatureModel.MaxLimbs]);WriteIntArray(writer,frame.parentSlots??new int[NativeCreatureModel.MaxLimbs]);}foreach(float v in new[]{o.oscillatorSin,o.oscillatorCos,o.angularVelocity,o.rhythmTicksRemaining,o.command.x,o.command.y,o.gravityLocal.x,o.gravityLocal.y})writer.Write(v);WriteArray(writer,o.heldRhythm);writer.Write(o.limbCount);writer.Write(o.episode);writer.Write(o.tick);writer.Write(o.controllerId??string.Empty);writer.Write(o.bodySignature??string.Empty);}
    private static NativeMovementObservation ReadMovementObservation(BinaryReader reader){int count=reader.ReadInt32();if(count!=NativeMovementWeights.HistoryLength)throw new InvalidDataException("v26 observation history shape mismatch");var o=new NativeMovementObservation{history=new NativeObservation[count]};for(int i=0;i<count;i++){o.history[i]=ReadObservation(reader);o.history[i].limbMask=ReadArray(reader,NativeCreatureModel.MaxLimbs);o.history[i].parentSlots=ReadIntArray(reader,NativeCreatureModel.MaxLimbs);}o.oscillatorSin=reader.ReadSingle();o.oscillatorCos=reader.ReadSingle();o.angularVelocity=reader.ReadSingle();o.rhythmTicksRemaining=reader.ReadSingle();o.command=new UnityEngine.Vector2(reader.ReadSingle(),reader.ReadSingle());o.gravityLocal=new UnityEngine.Vector2(reader.ReadSingle(),reader.ReadSingle());o.heldRhythm=ReadArray(reader,1+NativeCreatureModel.MaxLimbs*3);o.limbCount=reader.ReadInt32();o.episode=reader.ReadInt32();o.tick=reader.ReadInt32();o.controllerId=reader.ReadString();o.bodySignature=reader.ReadString();return o;}
    private static void WriteDecision(BinaryWriter writer,NativePolicyDecision d){if(d==null)throw new InvalidDataException("Cannot persist null v26 decision");WriteArray(writer,d.mean);WriteArray(writer,d.sample);WriteArray(writer,d.requested);WriteArray(writer,d.executed);WriteArray(writer,d.heldRhythm);foreach(float v in new[]{d.oldLogProbability,d.value,d.frequency,d.phase,d.curiosity})writer.Write(v);writer.Write(d.sampledRhythm);writer.Write(d.modelVersion);}
    private static NativePolicyDecision ReadDecision(BinaryReader reader){var d=new NativePolicyDecision{mean=ReadArray(reader,1+NativeCreatureModel.MaxLimbs*NativeMovementWeights.PolicyLimbOutputs),sample=ReadArray(reader,1+NativeCreatureModel.MaxLimbs*NativeMovementWeights.PolicyLimbOutputs),requested=ReadArray(reader,NativeCreatureModel.MaxLimbs),executed=ReadArray(reader,NativeCreatureModel.MaxLimbs),heldRhythm=ReadArray(reader,1+NativeCreatureModel.MaxLimbs*3)};d.oldLogProbability=reader.ReadSingle();d.value=reader.ReadSingle();d.frequency=reader.ReadSingle();d.phase=reader.ReadSingle();d.curiosity=reader.ReadSingle();d.sampledRhythm=reader.ReadBoolean();d.modelVersion=reader.ReadInt32();return d;}
    private static void WriteIntArray(BinaryWriter writer,int[] values){writer.Write(values.Length);foreach(int value in values)writer.Write(value);}private static int[] ReadIntArray(BinaryReader reader,int expected){int count=reader.ReadInt32();if(count!=expected)throw new InvalidDataException("v26 integer tensor shape mismatch");int[] result=new int[count];for(int i=0;i<count;i++)result[i]=reader.ReadInt32();return result;}

    private static IEnumerable<KeyValuePair<string,float[]>> PolicyParameters(NativeBrainWeights weights)
    {
        yield return P("m1Input",weights.m1Input);yield return P("m1Residual",weights.m1Residual);yield return P("m1Output",weights.m1Output);yield return P("m1Bias",weights.m1Bias);
        foreach(var parameter in weights.M2Parameters())yield return P("m2."+parameter.Key,parameter.Value);
    }
    private static KeyValuePair<string,float[]> P(string name,float[] value)=>new KeyValuePair<string,float[]>(name,value);
    private static void WriteOptionalM2State(BinaryWriter writer,NativeCreatureSave state,NativeBrainWeights fallback){NativeBrainWeights weights=state?.weights??fallback;writer.Write(weights!=null);if(weights==null)return;WriteParameters(writer,weights.M2Parameters());WriteOptimizer(writer,state?.m2Optimizer,weights.M2Parameters());WriteProtection(writer,state?.m2Protection,weights.M2Parameters());}
    private static NativeCreatureSave ReadOptionalM2State(BinaryReader reader,NativeCreatureSave state,int seed,out NativeBrainWeights snapshot){if(!reader.ReadBoolean()){snapshot=null;return null;}state=state??new NativeCreatureSave();state.weights=NativeBrainWeights.Create(seed);ReadParameters(reader,state.weights.M2Parameters());state.m2Optimizer=state.m2Optimizer??new NativeOptimizerState();ReadOptimizer(reader,state.m2Optimizer,state.weights.M2Parameters());state.m2Protection=state.m2Protection??new NativeSynapticIntelligence();ReadProtection(reader,state.m2Protection,state.weights.M2Parameters());snapshot=state.weights.Clone();return state;}
    private static void WriteParameters(BinaryWriter writer,IEnumerable<KeyValuePair<string,float[]>> source){var parameters=source.ToList();writer.Write(parameters.Count);foreach(var parameter in parameters){writer.Write(parameter.Key);writer.Write(parameter.Value.Length);foreach(float value in parameter.Value)writer.Write(value);}}
    private static void ReadParameters(BinaryReader reader,IEnumerable<KeyValuePair<string,float[]>> source){var expected=source.ToDictionary(p=>p.Key,p=>p.Value,StringComparer.Ordinal);int count=reader.ReadInt32();if(count!=expected.Count)throw new InvalidDataException("v26 tensor parameter count mismatch");for(int p=0;p<count;p++){string name=reader.ReadString();int length=reader.ReadInt32();if(!expected.TryGetValue(name,out float[] values)||values.Length!=length)throw new InvalidDataException("v26 tensor shape mismatch: "+name);for(int i=0;i<length;i++)values[i]=reader.ReadSingle();}}
    private static void WriteOptimizer(BinaryWriter writer,NativeOptimizerState optimizer,IEnumerable<KeyValuePair<string,float[]>> parameters){optimizer=optimizer??new NativeOptimizerState();writer.Write(optimizer.step);var list=parameters.ToList();writer.Write(list.Count);foreach(var parameter in list){NativeOptimizerSlot slot=optimizer.Get(parameter.Key,parameter.Value.Length);writer.Write(parameter.Key);writer.Write(parameter.Value.Length);foreach(float value in slot.first)writer.Write(value);foreach(float value in slot.second)writer.Write(value);}}
    private static void ReadOptimizer(BinaryReader reader,NativeOptimizerState optimizer,IEnumerable<KeyValuePair<string,float[]>> parameters){optimizer.step=reader.ReadInt32();var expected=parameters.ToDictionary(p=>p.Key,p=>p.Value.Length,StringComparer.Ordinal);int count=reader.ReadInt32();if(count!=expected.Count)throw new InvalidDataException("v26 optimizer slot count mismatch");optimizer.slots=new List<NativeOptimizerSlot>();for(int p=0;p<count;p++){string name=reader.ReadString();int length=reader.ReadInt32();if(!expected.TryGetValue(name,out int expectedLength)||length!=expectedLength)throw new InvalidDataException("v26 optimizer shape mismatch: "+name);NativeOptimizerSlot slot=optimizer.Get(name,length);for(int i=0;i<length;i++)slot.first[i]=reader.ReadSingle();for(int i=0;i<length;i++)slot.second[i]=reader.ReadSingle();}}
    private static void WriteProtection(BinaryWriter writer,NativeSynapticIntelligence protection,IEnumerable<KeyValuePair<string,float[]>> parameters){protection=protection??new NativeSynapticIntelligence();var list=parameters.ToList();writer.Write(list.Count);foreach(var parameter in list){NativeSynapticSlot slot=protection.Get(parameter.Key,parameter.Value.Length,parameter.Value);writer.Write(parameter.Key);writer.Write(parameter.Value.Length);WriteArray(writer,slot.importance);WriteArray(writer,slot.reference);WriteArray(writer,slot.path);}}
    private static void ReadProtection(BinaryReader reader,NativeSynapticIntelligence protection,IEnumerable<KeyValuePair<string,float[]>> parameters){var expected=parameters.ToDictionary(p=>p.Key,p=>p.Value,StringComparer.Ordinal);int count=reader.ReadInt32();if(count!=expected.Count)throw new InvalidDataException("v26 protection slot count mismatch");protection.slots=new List<NativeSynapticSlot>();for(int p=0;p<count;p++){string name=reader.ReadString();int length=reader.ReadInt32();if(!expected.TryGetValue(name,out float[] parameter)||parameter.Length!=length)throw new InvalidDataException("v26 protection shape mismatch: "+name);NativeSynapticSlot slot=protection.Get(name,length,parameter);ReadArray(reader,slot.importance);ReadArray(reader,slot.reference);ReadArray(reader,slot.path);}}
    private static void WriteReplay(BinaryWriter writer,List<NativeCompletedSequence> samples){samples=samples??new List<NativeCompletedSequence>();writer.Write(samples.Count);foreach(var sample in samples){writer.Write(sample.sampleId??string.Empty);writer.Write(sample.bodySignature??string.Empty);writer.Write(sample.controllerId??string.Empty);WriteObservation(writer,sample.observation);WriteArray(writer,sample.actions);WriteArray(writer,sample.executedActions??sample.actions);WriteArray(writer,sample.actualPoses);WriteArray(writer,sample.actualAuxiliary);writer.Write(sample.rhythmFrequency);writer.Write(sample.rhythmPhase);writer.Write(sample.retryCount);writer.Write(sample.modelVersion);}}
    private static List<NativeCompletedSequence> ReadReplay(BinaryReader reader){int count=reader.ReadInt32();if(count<0||count>NativeReplayBuffer.Capacity)throw new InvalidDataException("v25 replay capacity invalid");var result=new List<NativeCompletedSequence>(count);for(int i=0;i<count;i++)result.Add(new NativeCompletedSequence{sampleId=reader.ReadString(),bodySignature=reader.ReadString(),controllerId=reader.ReadString(),observation=ReadObservation(reader),actions=ReadArray(reader,NativeCreatureModel.PlanningHorizon*NativeCreatureModel.MaxLimbs),executedActions=ReadArray(reader,NativeCreatureModel.PlanningHorizon*NativeCreatureModel.MaxLimbs),actualPoses=ReadArray(reader,NativeCreatureModel.M3OutputSize),actualAuxiliary=ReadArray(reader,NativeCreatureModel.M3AuxiliaryOutputSize),rhythmFrequency=reader.ReadSingle(),rhythmPhase=reader.ReadSingle(),retryCount=reader.ReadInt32(),modelVersion=reader.ReadInt32()});return result;}
    private static void WriteObservation(BinaryWriter writer,NativeObservation o){if(o==null)throw new InvalidDataException("Cannot persist null replay observation");writer.Write(o.limbCount);writer.Write(o.tick);writer.Write(o.episode);writer.Write(o.controllerId??string.Empty);writer.Write(o.bodySignature??string.Empty);writer.Write(o.practice);foreach(float value in new[]{o.goalX,o.goalY,o.goalHeadingSin,o.goalHeadingCos,o.worldGoalX,o.worldGoalY,o.worldGoalHeadingSin,o.worldGoalHeadingCos,o.startWorldX,o.startWorldY,o.startWorldRotationDegrees})writer.Write(value);WriteArray(writer,o.torsoWithGoal);WriteArray(writer,o.torsoWithoutGoal);WriteArray(writer,o.jointFeatures);WriteArray(writer,o.positionEncodings);}
    private static NativeObservation ReadObservation(BinaryReader reader){var o=new NativeObservation{limbCount=reader.ReadInt32(),tick=reader.ReadInt32(),episode=reader.ReadInt32(),controllerId=reader.ReadString(),bodySignature=reader.ReadString(),practice=reader.ReadBoolean()};o.goalX=reader.ReadSingle();o.goalY=reader.ReadSingle();o.goalHeadingSin=reader.ReadSingle();o.goalHeadingCos=reader.ReadSingle();o.worldGoalX=reader.ReadSingle();o.worldGoalY=reader.ReadSingle();o.worldGoalHeadingSin=reader.ReadSingle();o.worldGoalHeadingCos=reader.ReadSingle();o.startWorldX=reader.ReadSingle();o.startWorldY=reader.ReadSingle();o.startWorldRotationDegrees=reader.ReadSingle();o.torsoWithGoal=ReadArray(reader,NativeCreatureModel.M2ContextSize);o.torsoWithoutGoal=ReadArray(reader,NativeCreatureModel.M3ContextSize);o.jointFeatures=ReadArray(reader,NativeCreatureModel.MaxLimbs*NativeCreatureModel.JointFeatureSize);o.positionEncodings=ReadArray(reader,NativeCreatureModel.MaxLimbs*NativeCreatureModel.PositionEncodingSize);return o;}
    private static void WriteArray(BinaryWriter writer,float[] values){if(values==null)throw new InvalidDataException("Cannot persist null tensor");writer.Write(values.Length);foreach(float value in values){if(!NativeCreatureModel.IsFinite(value))throw new InvalidDataException("Cannot persist non-finite tensor");writer.Write(value);}}
    private static float[] ReadArray(BinaryReader reader,int expected){int length=reader.ReadInt32();if(length!=expected)throw new InvalidDataException("v26 replay tensor shape mismatch");var values=new float[length];for(int i=0;i<length;i++)values[i]=reader.ReadSingle();return values;}
    private static void ReadArray(BinaryReader reader,float[] target){int length=reader.ReadInt32();if(target==null||length!=target.Length)throw new InvalidDataException("v26 state tensor shape mismatch");for(int i=0;i<length;i++)target[i]=reader.ReadSingle();}
}
