using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json;
using UnityEngine;

[Serializable]
public sealed class NativeBrainWeights
{
    public int version = 18;
    [JsonIgnore] public float[] m1Input, m1Residual, m1Output, m1Bias;
    [JsonIgnore] public float[] m2Context, m2Joint, m2Position, m2AttentionQuery, m2AttentionKey, m2AttentionValue, m2AttentionQuery2, m2AttentionKey2, m2AttentionValue2, m2Fusion, m2Residual, m2Deep1, m2Deep2, m2Deep3, m2Deep4, m2Deep5, m2Deep6, m2Deep7, m2Deep8, m2Output, m2StepEmbedding, m2Norm, m2Bias;

    public static NativeBrainWeights Create(int seed)
    {
        var r = new System.Random(seed); int m1 = NativeCreatureModel.M1Width, h = NativeCreatureModel.M2Width;
        return new NativeBrainWeights {
            m1Input = Xavier(r, NativeCreatureModel.M1InputSize, m1), m1Residual = Xavier(r, m1, m1), m1Output = Xavier(r, m1, 4), m1Bias = new float[m1 * 2 + 4],
            m2Context = Xavier(r, NativeCreatureModel.M2ContextSize, h), m2Joint = Xavier(r, NativeCreatureModel.JointFeatureSize, h), m2Position = Xavier(r, NativeCreatureModel.PositionEncodingSize, h), m2AttentionQuery = Xavier(r, h, h), m2AttentionKey = Xavier(r, h, h), m2AttentionValue = Xavier(r, h, h), m2AttentionQuery2 = Xavier(r, h, h), m2AttentionKey2 = Xavier(r, h, h), m2AttentionValue2 = Xavier(r, h, h), m2Fusion = Xavier(r, h * 2, h), m2Residual = Xavier(r, h, h), m2Deep1 = Xavier(r, h, h), m2Deep2 = Xavier(r, h, h), m2Deep3 = Xavier(r, h, h), m2Deep4 = Xavier(r, h, h), m2Deep5 = Xavier(r, h, h), m2Deep6 = Xavier(r, h, h), m2Deep7 = Xavier(r, h, h), m2Deep8 = Xavier(r, h, h), m2Output = Xavier(r, h, 1), m2StepEmbedding = Xavier(r, NativeCreatureModel.PlanningHorizon, h), m2Norm = Ones(h * 11), m2Bias = new float[h * 12 + 1]
        };
    }
    private static float[] Xavier(System.Random r, int input, int output) { float limit = Mathf.Sqrt(6f / (input + output)); float[] a = new float[input * output]; for (int i = 0; i < a.Length; i++) a[i] = ((float)r.NextDouble() * 2f - 1f) * limit; return a; }
    internal static float[] XavierForDynamics(System.Random r,int input,int output)=>Xavier(r,input,output);
    internal static float[] Ones(int length){float[] a=new float[length];for(int i=0;i<length;i++)a[i]=1f;return a;}
    public NativeBrainWeights Clone(){var copy=new NativeBrainWeights{version=version};foreach(var f in typeof(NativeBrainWeights).GetFields().Where(f=>f.FieldType==typeof(float[]))){float[] value=(float[])f.GetValue(this);f.SetValue(copy,value==null?null:(float[])value.Clone());}return copy;}
    public void CopyFrom(NativeBrainWeights source) { var copy = source.Clone(); foreach (var f in typeof(NativeBrainWeights).GetFields()) f.SetValue(this, f.GetValue(copy)); }
    public void Mutate(System.Random r, float amount = .05f) { MutateM1(r, amount); MutateM2(r, amount); }
    public void MutateM1(System.Random r, float amount) { foreach (float[] a in new[] { m1Input, m1Residual, m1Output, m1Bias }) MutateArray(a, r, amount, .04f); }
    public void MutateM2(System.Random r, float amount, float hiddenProbability = .03f, float headProbability = .12f) { float scale=NativeCreatureModel.M2MutationScale;foreach (var p in M2Parameters()) MutateArray(p.Value, r, amount*scale, (p.Key == "output" ? headProbability : hiddenProbability)*scale); }
    private static void MutateArray(float[] a, System.Random r, float amount, float probability) { for (int i = 0; i < a.Length; i++) if (r.NextDouble() < probability) a[i] = Mathf.Clamp(a[i] + ((float)r.NextDouble() - .5f) * amount, -4f, 4f); }
    public bool IsFinite() => ControllerArrays().All(a => a != null && a.All(NativeCreatureModel.IsFinite));
    public IEnumerable<float[]> ControllerArrays() { yield return m1Input; yield return m1Residual; yield return m1Output; yield return m1Bias; foreach (var p in M2Parameters()) yield return p.Value; }
    public IEnumerable<KeyValuePair<string,float[]>> M2Parameters() { yield return P("context",m2Context); yield return P("joint",m2Joint); yield return P("position",m2Position); yield return P("attentionQuery",m2AttentionQuery); yield return P("attentionKey",m2AttentionKey); yield return P("attentionValue",m2AttentionValue); yield return P("attentionQuery2",m2AttentionQuery2); yield return P("attentionKey2",m2AttentionKey2); yield return P("attentionValue2",m2AttentionValue2); yield return P("fusion",m2Fusion); yield return P("residual",m2Residual); yield return P("deep1",m2Deep1); yield return P("deep2",m2Deep2); yield return P("deep3",m2Deep3); yield return P("deep4",m2Deep4); yield return P("deep5",m2Deep5); yield return P("deep6",m2Deep6); yield return P("deep7",m2Deep7); yield return P("deep8",m2Deep8); yield return P("output",m2Output); yield return P("stepEmbedding",m2StepEmbedding); yield return P("norm",m2Norm); yield return P("bias",m2Bias); }
    private static KeyValuePair<string,float[]> P(string n,float[] v) => new KeyValuePair<string,float[]>(n,v);
}

[Serializable]
public sealed class NativeDynamicsWeights
{
    public int version=18;
    [JsonIgnore] public float[] context,joint,position,attentionQuery,attentionKey,attentionValue,horizonQueries,crossQuery,crossKey,crossValue,fusion,residual,deep1,deep2,deep3,deep4,deep5,deep6,output,norm,bias;
    public static NativeDynamicsWeights Create(int seed){var r=new System.Random(seed);int h=NativeCreatureModel.M3Width;return new NativeDynamicsWeights{context=NativeBrainWeights.XavierForDynamics(r,NativeCreatureModel.M3ContextSize,h),joint=NativeBrainWeights.XavierForDynamics(r,NativeCreatureModel.M3JointInputSize,h),position=NativeBrainWeights.XavierForDynamics(r,NativeCreatureModel.PositionEncodingSize,h),attentionQuery=NativeBrainWeights.XavierForDynamics(r,h,h),attentionKey=NativeBrainWeights.XavierForDynamics(r,h,h),attentionValue=NativeBrainWeights.XavierForDynamics(r,h,h),horizonQueries=NativeBrainWeights.XavierForDynamics(r,NativeCreatureModel.PlanningHorizon,h),crossQuery=NativeBrainWeights.XavierForDynamics(r,h,h),crossKey=NativeBrainWeights.XavierForDynamics(r,h,h),crossValue=NativeBrainWeights.XavierForDynamics(r,h,h),fusion=NativeBrainWeights.XavierForDynamics(r,h*2,h),residual=NativeBrainWeights.XavierForDynamics(r,h,h),deep1=NativeBrainWeights.XavierForDynamics(r,h,h),deep2=NativeBrainWeights.XavierForDynamics(r,h,h),deep3=NativeBrainWeights.XavierForDynamics(r,h,h),deep4=NativeBrainWeights.XavierForDynamics(r,h,h),deep5=NativeBrainWeights.XavierForDynamics(r,h,h),deep6=NativeBrainWeights.XavierForDynamics(r,h,h),output=NativeBrainWeights.XavierForDynamics(r,h,NativeCreatureModel.M3ValuesPerHorizon),norm=NativeBrainWeights.Ones(h*10),bias=new float[h*10+NativeCreatureModel.M3ValuesPerHorizon]};}
    public NativeDynamicsWeights Clone(){var copy=new NativeDynamicsWeights{version=version};foreach(var f in typeof(NativeDynamicsWeights).GetFields().Where(f=>f.FieldType==typeof(float[]))){float[] value=(float[])f.GetValue(this);f.SetValue(copy,value==null?null:(float[])value.Clone());}return copy;}
    public bool IsFinite()=>Parameters().All(p=>p.Value!=null&&p.Value.All(NativeCreatureModel.IsFinite));
    public IEnumerable<KeyValuePair<string,float[]>> Parameters(){yield return P("context",context);yield return P("joint",joint);yield return P("position",position);yield return P("attentionQuery",attentionQuery);yield return P("attentionKey",attentionKey);yield return P("attentionValue",attentionValue);yield return P("horizonQueries",horizonQueries);yield return P("crossQuery",crossQuery);yield return P("crossKey",crossKey);yield return P("crossValue",crossValue);yield return P("fusion",fusion);yield return P("residual",residual);yield return P("deep1",deep1);yield return P("deep2",deep2);yield return P("deep3",deep3);yield return P("deep4",deep4);yield return P("deep5",deep5);yield return P("deep6",deep6);yield return P("output",output);yield return P("norm",norm);yield return P("bias",bias);}private static KeyValuePair<string,float[]> P(string n,float[] v)=>new KeyValuePair<string,float[]>(n,v);
}

public sealed class NativeCreatureModel
{
    public const int M1Width=32,M2Width=36,M3Width=36,Hidden=M2Width,M2AttentionHeads=4,M3AttentionHeads=4,M2MlpHiddenLayers=8,M3MlpHiddenLayers=6,M2TransformerBlocks=2,M3TransformerBlocks=2,MaxLimbs=BodyMorphologyRules.MaxLimbs,MaxPathDepth=BodyMorphologyRules.MaxDepth,PlanningHorizon=7,ActionTicks=5,SequenceTicks=35,GoalWindowTicks=1000,M1GoalWindowTicks=35;
    public const int M1InputSize=28,M2ContextSize=22,M3ContextSize=18,JointFeatureSize=22,PositionEncodingSize=24,M3JointInputSize=JointFeatureSize+PlanningHorizon,PoseValueCount=6,EndpointValueCount=2,ContactValueCount=3,AuxiliaryValueCount=MaxLimbs*(EndpointValueCount+ContactValueCount),M3ValuesPerHorizon=PoseValueCount+AuxiliaryValueCount,M3OutputSize=PlanningHorizon*PoseValueCount,M3AuxiliaryOutputSize=PlanningHorizon*AuxiliaryValueCount,M3EndpointOutputSize=PlanningHorizon*MaxLimbs*EndpointValueCount,M3ContactOutputSize=PlanningHorizon*MaxLimbs*ContactValueCount;
    public const float MaximumActionDegrees=8f,MinimumActionDegrees=.75f,ScaffoldActionDegrees=5f,GoalMagnitude=4f,CurriculumGoalMagnitude=12f,M2PlanningGoalDisplacement=.25f,M2LearningRate=.0003f,M3LearningRate=.0003f,ActionEnergyWeight=.01f,AntiZeroWeight=4f,MotionThreshold=.01f,M2HeadingLossWeight=.25f,M3HeadingLossWeight=4f,M3VelocityLossWeight=.1f,M3ContactLossWeight=.25f,RmsNormEpsilon=1e-5f,M3VelocityScale=10f;
    public const int ScaffoldPeriodTicks=100;
    public const int ActionBiasEndTick=16667, ExplorationDecayUpdates=10000, MinimumM2FitnessSamples=50, M2FitnessWindow=250, FixedGoalGenerations=1500, StartupSafeguardGenerations=200;
    public const float ExplorationStartSigma=.5f, ExplorationFloorSigma=.05f;
    public const float AssistedBiasStrength=1.5f;
    public static readonly float[] GoalStepWeights={1f,1f,2f,4f,8f,12f,16f};
    public const int V16M2ParameterCount=13189,M2ParameterCount=15457;
    public const float M2MutationScale=1f;
    public NativeBrainWeights Weights { get; private set; }
    public NativeOptimizerState M2Optimizer { get; private set; } = new NativeOptimizerState();
    public NativeSynapticIntelligence M2Protection { get; private set; } = new NativeSynapticIntelligence();
    private readonly object trainingStateLock=new object();
    public Vector2 CurrentGoal { get; private set; }
    public Vector2 CurrentWorldGoal { get; private set; }
    public Vector2 CurrentGoalHeading { get; private set; }=Vector2.up;
    public Vector2 CurrentWorldGoalHeading { get; private set; }=Vector2.up;
    public int GoalTicksRemaining { get; private set; }
    public float LastM2Loss { get; private set; }=float.PositiveInfinity;
    public float LastM2GoalLoss { get; private set; }=float.PositiveInfinity;
    public float LastM2EnergyLoss { get; private set; }
    public float LastM3Loss { get; private set; }=float.PositiveInfinity;
    public float LastM3Mse { get; private set; }=float.PositiveInfinity;
    public float LastM3RelativeLoss { get; private set; }
    public NativePosePrediction LastPrediction { get; private set; }
    public int LeftLossSamples=>leftLosses.Count; public int RightLossSamples=>rightLosses.Count; public int M2LossSamples=>LeftLossSamples+RightLossSamples;
    public float LeftProposalLoss=>Mean(leftLosses); public float RightProposalLoss=>Mean(rightLosses); public bool LeftTrialComplete=>LeftLossSamples>=MinimumM2FitnessSamples; public bool RightTrialComplete=>RightLossSamples>=MinimumM2FitnessSamples; public bool IsBidirectionallyVerified=>LeftTrialComplete&&RightTrialComplete;
    public float BodyFitness=>BidirectionalFitness(LeftProposalLoss,LeftLossSamples,LeftTrialComplete,RightProposalLoss,RightLossSamples,RightTrialComplete);
    public bool HasBidirectionalMovementEvidence=>LeftBestTrialProgress>=1f&&RightBestTrialProgress>=1f;
    public int LatchedDirection { get; private set; } public float LeftBestTrialProgress { get; private set; } public float RightBestTrialProgress { get; private set; }
    private readonly Queue<float> leftLosses=new Queue<float>(), rightLosses=new Queue<float>(); private NativeDeterministicRng exploration; private int fixedGoalBlock=int.MinValue; private bool hasGoal,m1GoalAnchorInitialized,externalTrainingGoal; private Vector2 m1GoalAnchor,fixedGoalWorldHeading=Vector2.up,externalWorldGoal,externalWorldHeading=Vector2.up; private int externalGoalTicks; private float oscillatorPhase;
    public NativeCreatureModel(NativeBrainWeights weights,int seed=0){Weights=weights??NativeBrainWeights.Create(seed==0?Environment.TickCount:seed);exploration=new NativeDeterministicRng((ulong)(seed==0?Environment.TickCount:seed));}

    public NativeObservation Observe(float[] global,Limb[] limbs,int tick,NativeLocalProprioception proprio,bool enableM1,float[] m1Output=null,bool practice=false,string controllerId=null,string bodySignature=null,float[] terrain=null)
    {
        if(enableM1){m1GoalAnchor=proprio.worldPosition;m1GoalAnchorInitialized=true;GoalFromOutput(m1Output,global,out Vector2 offset,out Vector2 heading);Vector2 biased=SoftBiasedGoal(offset);CurrentWorldGoal=new Vector2(Mathf.Clamp(m1GoalAnchor.x+biased.x*GoalMagnitude,-WorldLayout.GoalHalfWidth,WorldLayout.GoalHalfWidth),m1GoalAnchor.y+biased.y*GoalMagnitude);CurrentWorldGoalHeading=heading;GoalTicksRemaining=SequenceTicks;hasGoal=true;}
        else if(externalTrainingGoal){m1GoalAnchorInitialized=false;CurrentWorldGoal=externalWorldGoal;CurrentWorldGoalHeading=externalWorldHeading;GoalTicksRemaining=Mathf.Max(0,externalGoalTicks-tick);hasGoal=true;}
        else{m1GoalAnchorInitialized=false;int block=Mathf.Max(0,tick)/GoalWindowTicks;if(!hasGoal||block!=fixedGoalBlock){CurrentWorldGoal=new Vector2(Mathf.Clamp(proprio.worldPosition.x+FixedTrainingGoal(tick).x,-WorldLayout.GoalHalfWidth,WorldLayout.GoalHalfWidth),FixedGoalWorldHeight);fixedGoalWorldHeading=HeadingTowards(CurrentWorldGoal-proprio.worldPosition,proprio.worldRotationDegrees);fixedGoalBlock=block;hasGoal=true;}CurrentWorldGoalHeading=fixedGoalWorldHeading;GoalTicksRemaining=GoalWindowTicks-Mathf.Max(0,tick)%GoalWindowTicks;}
        Vector2 worldOffset=CurrentWorldGoal-proprio.worldPosition;CurrentGoal=proprio.WorldToTorsoVector(worldOffset);CurrentGoalHeading=RelativeHeading(CurrentWorldGoalHeading,proprio.worldRotationDegrees);LatchedDirection=ClassifyWorldGoalDirection(worldOffset.x);int count=Mathf.Min(limbs?.Length??0,MaxLimbs);
        var o=new NativeObservation{torsoWithGoal=TorsoFeatures(proprio,CurrentGoal,CurrentGoalHeading,true,terrain),torsoWithoutGoal=TorsoFeatures(proprio,Vector2.zero,Vector2.zero,false,terrain),jointFeatures=new float[MaxLimbs*JointFeatureSize],positionEncodings=new float[MaxLimbs*PositionEncodingSize],limbMask=new float[MaxLimbs],parentSlots=new int[MaxLimbs],limbCount=count,goal=CurrentGoal,goalHeading=CurrentGoalHeading,worldGoal=CurrentWorldGoal,worldGoalHeading=CurrentWorldGoalHeading,startWorldPosition=proprio.worldPosition,startWorldRotationDegrees=proprio.worldRotationDegrees,tick=tick,practice=practice,controllerId=controllerId,bodySignature=bodySignature};
        for(int i=0;i<count;i++){Limb limb=limbs[i];o.limbMask[i]=1f;o.parentSlots[i]=limb.parentInnovationId;Vector2 baseLocal=proprio.WorldToTorsoVector(limb.BaseWorldPosition-proprio.worldPosition), tipLocal=proprio.WorldToTorsoVector(limb.DistalWorldPosition-proprio.worldPosition), tipVelocity=proprio.WorldToTorsoVector(limb.LocalEndpointVelocity);Array.Copy(JointFeatures(limb,baseLocal,tipLocal,tipVelocity),0,o.jointFeatures,i*JointFeatureSize,JointFeatureSize);Array.Copy(JointPositionEncoding(limb.genePath,limb.attachmentSlot,baseLocal),0,o.positionEncodings,i*PositionEncodingSize,PositionEncodingSize);}return o;
    }

    public void SetCurriculumGoal(Vector2 worldGoal,Vector2 heading,int deadlineTick){externalTrainingGoal=true;externalWorldGoal=worldGoal;externalWorldHeading=NormalizeHeading(heading,Vector2.up);externalGoalTicks=deadlineTick;hasGoal=true;}
    public void ResetOscillatorPhase(){oscillatorPhase=0f;}
    public void ClearCurriculumGoal(){externalTrainingGoal=false;fixedGoalBlock=int.MinValue;hasGoal=false;}
    public NativeActionSequence Plan(NativeObservation observation,NativeDynamicsWeights sharedM3,int sharedM3Samples,float? biasOverride=null,float? explorationOverride=null,NativeBrainWeights weightsOverride=null)
    {
        NativeBrainWeights snapshot=weightsOverride??Weights;var after=ForwardM2(observation,snapshot);float bias=biasOverride??EffectiveActionBias(observation.tick),sigma=explorationOverride??EffectiveExplorationSigma(sharedM3Samples);float[,] modifiers=(float[,])after.actions.Clone();for(int s=0;s<PlanningHorizon;s++)for(int l=0;l<observation.limbCount;l++)modifiers[s,l]=Mathf.Clamp(modifiers[s,l]+Gaussian()*sigma,-MaximumActionDegrees,MaximumActionDegrees);float frequency,phase;float[,] decoderGradient;float[,] executed=DecodeRhythmicActions(modifiers,observation,bias,out frequency,out phase,out decoderGradient);var prediction=ForwardM3(observation,executed,sharedM3);float[] poseGradient=new float[M3OutputSize];float initial=M2Loss(prediction.prediction,observation.goal,observation.goalHeading,executed,observation.limbCount,poseGradient,out float goalLoss,out float energyLoss),best=initial;int retries=0;float[,] bestModifiers=modifiers,bestActions=executed;M3Cache bestPrediction=prediction;
        if(best>2f){for(int retry=0;retry<2;retry++){float[,] actionGradient=BackwardM3(bestPrediction,poseGradient,null,sharedM3,null);AddEnergyGradient(actionGradient,bestActions,observation.limbCount);float step=retry==0?.10f:.05f;float[,] candidate=(float[,])bestModifiers.Clone();for(int s=0;s<PlanningHorizon;s++)for(int l=0;l<observation.limbCount;l++)candidate[s,l]=Mathf.Clamp(candidate[s,l]-step*actionGradient[s,l]*decoderGradient[s,l],-MaximumActionDegrees,MaximumActionDegrees);float candidateFrequency,candidatePhase;float[,] candidateDecoderGradient;float[,] candidateActions=DecodeRhythmicActions(candidate,observation,bias,out candidateFrequency,out candidatePhase,out candidateDecoderGradient);var candidatePrediction=ForwardM3(observation,candidateActions,sharedM3);float[] candidateGradient=new float[M3OutputSize];float candidateLoss=M2Loss(candidatePrediction.prediction,observation.goal,observation.goalHeading,candidateActions,observation.limbCount,candidateGradient,out _,out _);retries++;if(IsFinite(candidateLoss)&&candidateLoss<best){best=candidateLoss;bestModifiers=candidate;bestActions=candidateActions;bestPrediction=candidatePrediction;poseGradient=candidateGradient;decoderGradient=candidateDecoderGradient;frequency=candidateFrequency;phase=candidatePhase;}if(best<=2f)break;}}
        oscillatorPhase=Mathf.Repeat(phase+frequency*2f*Mathf.PI*(SequenceTicks*.02f),2f*Mathf.PI);LastM2Loss=best;LastM2GoalLoss=goalLoss;LastM2EnergyLoss=energyLoss;LastPrediction=new NativePosePrediction((float[])bestPrediction.prediction.Clone());RecordFitness(LastM2Loss);
        return new NativeActionSequence(bestActions,observation.limbCount,observation.goal,observation.goalHeading,observation.worldGoal,observation.worldGoalHeading,LastPrediction,bias,sigma,frequency,phase,retries,initial,best);
    }

    public NativeActionSequence OptimizeAndPlan(NativeObservation observation,NativeDynamicsWeights sharedM3,int sharedM3Samples)
    {TrainM2Batch(new[]{observation},sharedM3,observation.tick);return Plan(observation,sharedM3,sharedM3Samples);}

    public NativeM2BatchMetrics TrainM2Batch(IReadOnlyList<NativeObservation> source,NativeDynamicsWeights sharedM3,int currentTick)
    {
        var samples=(source??Array.Empty<NativeObservation>()).Where(s=>s!=null).ToList();var metrics=new NativeM2BatchMetrics{sampleCount=samples.Count};if(samples.Count==0)return metrics;NativeBrainWeights next;NativeOptimizerState optimizer;NativeSynapticIntelligence protection;lock(trainingStateLock){next=Weights.Clone();optimizer=M2Optimizer.Clone();protection=M2Protection.Clone();}var gradient=Zero(next.M2Parameters());float bias=EffectiveActionBias(currentTick);
        foreach(NativeObservation observation in samples){var cache=ForwardM2(observation,next);float frequency,phase;float[,] decoderGradient;float[,] actions=DecodeRhythmicActions(cache.actions,observation,bias,out frequency,out phase,out decoderGradient);var predicted=ForwardM3(observation,actions,sharedM3);float[] pg=new float[M3OutputSize];float loss=M2Loss(predicted.prediction,observation.goal,observation.goalHeading,actions,observation.limbCount,pg,out float goalLoss,out float energyLoss);float[,] ag=BackwardM3(predicted,pg,null,sharedM3,null);AddEnergyGradient(ag,actions,observation.limbCount);for(int s=0;s<PlanningHorizon;s++)for(int l=0;l<observation.limbCount;l++)ag[s,l]*=decoderGradient[s,l];BackwardM2(cache,ag,next,gradient);metrics.loss+=loss;metrics.goalLoss+=goalLoss;metrics.energyLoss+=energyLoss;}
        foreach(float[] values in gradient.Values)for(int i=0;i<values.Length;i++)values[i]/=samples.Count;ApplyAdam(next.M2Parameters(),gradient,optimizer,M2LearningRate,protection);if(!next.IsFinite()||!protection.IsFinite())throw new InvalidOperationException("M2 update produced non-finite state");lock(trainingStateLock){Weights=next;M2Optimizer=optimizer;M2Protection=protection;}metrics.loss/=samples.Count;metrics.goalLoss/=samples.Count;metrics.energyLoss/=samples.Count;metrics.optimizerSteps=optimizer.step;return metrics;
    }

    public static NativeM3BatchMetrics TrainSharedM3Batch(IReadOnlyList<NativeCompletedSequence> source,NativeDynamicsWeights weights,NativeOptimizerState optimizer,NativeSynapticIntelligence protection=null)
    {var samples=(source??Array.Empty<NativeCompletedSequence>()).Where(s=>s?.observation!=null).OrderBy(s=>s.sampleId??string.Empty,StringComparer.Ordinal).ThenBy(s=>s.observation.tick).ToList();var metrics=new NativeM3BatchMetrics{sampleCount=samples.Count};if(samples.Count==0)return metrics;var gradients=Zero(weights.Parameters());foreach(var sample in samples){var cache=ForwardM3(sample.observation,sample.ActionMatrix(),weights);float[] pg=new float[M3OutputSize],ag=new float[M3AuxiliaryOutputSize];float pose=M3Loss(cache.prediction,sample.actualPoses,pg,out float mse,out float relative),aux=M3AuxiliaryLoss(cache.auxiliary,sample.actualAuxiliary,ag,sample.observation.limbCount,out float endpoint,out float contact);BackwardM3(cache,pg,ag,weights,gradients);metrics.loss+=pose+aux;metrics.poseMse+=mse;metrics.relativeLoss+=relative;metrics.velocityLoss+=endpoint;metrics.contactLoss+=contact;}foreach(float[] values in gradients.Values)for(int i=0;i<values.Length;i++)values[i]/=samples.Count;ApplyAdam(weights.Parameters(),gradients,optimizer,M3LearningRate,protection);metrics.loss/=samples.Count;metrics.poseMse/=samples.Count;metrics.relativeLoss/=samples.Count;metrics.velocityLoss/=samples.Count;metrics.contactLoss/=samples.Count;metrics.optimizerSteps=optimizer.step;return metrics;}

    public static float[] PredictM3ForTesting(NativeObservation observation,float[,] actions,NativeDynamicsWeights weights)=>(float[])ForwardM3(observation,actions,weights).prediction.Clone();
    public static float[] PredictM3AuxiliaryForTesting(NativeObservation observation,float[,] actions,NativeDynamicsWeights weights)=>(float[])ForwardM3(observation,actions,weights).auxiliary.Clone();
    public static float[] M3GradientForTesting(NativeCompletedSequence sample,NativeDynamicsWeights weights,string parameterName){var cache=ForwardM3(sample.observation,sample.ActionMatrix(),weights);float[] pg=new float[M3OutputSize],ag=new float[M3AuxiliaryOutputSize];M3Loss(cache.prediction,sample.actualPoses,pg,out _,out _);M3AuxiliaryLoss(cache.auxiliary,sample.actualAuxiliary,ag,out _,out _);var gradients=Zero(weights.Parameters());BackwardM3(cache,pg,ag,weights,gradients);return gradients[parameterName];}
    public static float M3LossForTesting(NativeCompletedSequence sample,NativeDynamicsWeights weights){var cache=ForwardM3(sample.observation,sample.ActionMatrix(),weights);return M3Loss(cache.prediction,sample.actualPoses,null,out _,out _)+M3AuxiliaryLoss(cache.auxiliary,sample.actualAuxiliary,null,out _,out _);}
    public static float[] M2GradientForTesting(NativeObservation observation,NativeBrainWeights m2,NativeDynamicsWeights m3,string parameterName){var cache=ForwardM2(observation,m2);float frequency,phase;float[,] dg;float[,] actions=DecodeRhythmicActionsForTesting(cache.actions,observation,ActionBiasStrength(observation.tick),out frequency,out phase,out dg);var prediction=ForwardM3(observation,actions,m3);float[] pg=new float[M3OutputSize];M2Loss(prediction.prediction,observation.goal,observation.goalHeading,actions,observation.limbCount,pg,out _,out _);float[,] ag=BackwardM3(prediction,pg,null,m3,null);AddEnergyGradient(ag,actions,observation.limbCount);for(int s=0;s<PlanningHorizon;s++)for(int l=0;l<observation.limbCount;l++)ag[s,l]*=dg[s,l];var gradients=Zero(m2.M2Parameters());BackwardM2(cache,ag,m2,gradients);return gradients[parameterName];}
    public static float M2LossForTesting(NativeObservation observation,NativeBrainWeights m2,NativeDynamicsWeights m3){var cache=ForwardM2(observation,m2);float frequency,phase;float[,] dg;float[,] actions=DecodeRhythmicActionsForTesting(cache.actions,observation,ActionBiasStrength(observation.tick),out frequency,out phase,out dg);var prediction=ForwardM3(observation,actions,m3);return M2Loss(prediction.prediction,observation.goal,observation.goalHeading,actions,observation.limbCount,null,out _,out _);}
    public static NativeM3Evaluation EvaluateM3(IReadOnlyList<NativeCompletedSequence> samples,NativeDynamicsWeights weights,int updates)
    {var result=new NativeM3Evaluation{modelUpdates=updates};if(samples==null||samples.Count==0)return result;float pos=0f,orientation=0f,endpoint=0f,brier=0f,sensitivity=0f;int poses=0,endpoints=0,contacts=0;foreach(var sample in samples.Take(64)){if(sample?.observation==null)continue;var prediction=ForwardM3(sample.observation,sample.ActionMatrix(),weights);for(int s=0;s<PlanningHorizon;s++){int p=s*PoseValueCount;float dx=prediction.prediction[p]-sample.actualPoses[p],dy=prediction.prediction[p+1]-sample.actualPoses[p+1];pos+=dx*dx+dy*dy;float dot=Mathf.Clamp(prediction.prediction[p+2]*sample.actualPoses[p+2]+prediction.prediction[p+3]*sample.actualPoses[p+3],-1f,1f);orientation+=Mathf.Acos(dot)*Mathf.Rad2Deg;poses++;int a=s*AuxiliaryValueCount;for(int l=0;l<sample.observation.limbCount;l++){int e=a+l*EndpointValueCount;float ex=prediction.auxiliary[e]-sample.actualAuxiliary[e],ey=prediction.auxiliary[e+1]-sample.actualAuxiliary[e+1];endpoint+=ex*ex+ey*ey;endpoints++;int c=a+MaxLimbs*EndpointValueCount+l*ContactValueCount;for(int k=0;k<ContactValueCount;k++){float d=prediction.auxiliary[c+k]-sample.actualAuxiliary[c+k];brier+=d*d;contacts++;}}}float[,] shuffled=sample.ActionMatrix();if(sample.observation.limbCount>1)for(int s=0;s<PlanningHorizon;s++){float t=shuffled[s,0];shuffled[s,0]=shuffled[s,1];shuffled[s,1]=t;}sensitivity+=SumAbsDifference(ForwardM3(sample.observation,sample.ActionMatrix(),weights).prediction,ForwardM3(sample.observation,shuffled,weights).prediction);result.sampleCount++;}result.torsoPositionRmse=Mathf.Sqrt(pos/Mathf.Max(1,poses*2));result.orientationDegrees=orientation/Mathf.Max(1,poses);result.endpointRmse=Mathf.Sqrt(endpoint/Mathf.Max(1,endpoints*2));result.contactBrier=brier/Mathf.Max(1,contacts);result.actionSensitivity=sensitivity/Mathf.Max(1,result.sampleCount);return result;}

    public static float M3Loss(float[] predicted,float[] actual,float[] gradient,out float mse,out float relative)
    {mse=0f;relative=0f;actual=actual??new float[M3OutputSize];if(gradient!=null)Array.Clear(gradient,0,gradient.Length);for(int s=0;s<PlanningHorizon;s++){int i=s*PoseValueCount;for(int c=0;c<2;c++){float e=(predicted[i+c]-actual[i+c])/.25f;mse+=e*e/(PlanningHorizon*2f);if(gradient!=null)gradient[i+c]+=e/(.25f*PlanningHorizon);}for(int c=2;c<4;c++){float e=predicted[i+c]-actual[i+c];mse+=M3HeadingLossWeight*e*e/(PlanningHorizon*2f);if(gradient!=null)gradient[i+c]+=M3HeadingLossWeight*e/PlanningHorizon;}for(int c=4;c<6;c++){float e=predicted[i+c]-actual[i+c];mse+=M3VelocityLossWeight*e*e/(PlanningHorizon*2f);if(gradient!=null)gradient[i+c]+=M3VelocityLossWeight*e/PlanningHorizon;}float dx=predicted[i]-actual[i],dy=predicted[i+1]-actual[i+1];relative+=Mathf.Sqrt(dx*dx+dy*dy)/PlanningHorizon;}return mse;}
    public static float M3AuxiliaryLoss(float[] predicted,float[] actual,float[] gradient,out float velocityLoss,out float contactLoss)=>M3AuxiliaryLoss(predicted,actual,gradient,MaxLimbs,out velocityLoss,out contactLoss);
    public static float M3AuxiliaryLoss(float[] predicted,float[] actual,float[] gradient,int activeLimbs,out float endpointLoss,out float contactLoss){endpointLoss=0f;contactLoss=0f;actual=actual??new float[M3AuxiliaryOutputSize];if(gradient!=null)Array.Clear(gradient,0,gradient.Length);int limbs=Mathf.Clamp(activeLimbs,0,MaxLimbs);if(limbs==0)return 0f;for(int s=0;s<PlanningHorizon;s++){int i=s*AuxiliaryValueCount;for(int l=0;l<limbs;l++){int endpoint=i+l*EndpointValueCount;for(int c=0;c<EndpointValueCount;c++){float e=(predicted[endpoint+c]-actual[endpoint+c])/BodyMorphologyRules.TorsoWidth;endpointLoss+=e*e/(PlanningHorizon*limbs*EndpointValueCount);if(gradient!=null)gradient[endpoint+c]+=e/(BodyMorphologyRules.TorsoWidth*PlanningHorizon*limbs);}int contact=i+MaxLimbs*EndpointValueCount+l*ContactValueCount;for(int c=0;c<ContactValueCount;c++){float p=Mathf.Clamp(predicted[contact+c],1e-5f,1f-1e-5f),target=Mathf.Clamp01(actual[contact+c]);contactLoss-=M3ContactLossWeight*(target*Mathf.Log(p)+(1f-target)*Mathf.Log(1f-p))/(PlanningHorizon*limbs*ContactValueCount);if(gradient!=null)gradient[contact+c]=M3ContactLossWeight*(p-target)/(p*(1f-p)*PlanningHorizon*limbs*ContactValueCount);}}}return endpointLoss+contactLoss;}
    // M3 predicts the next seven held actions (0.7 simulated seconds), not arrival at a distant curriculum goal.
    // Keep the full physical goal in the observation, but train M2 toward this reachable local displacement.
    public static Vector2 PlanningGoal(Vector2 goal){float distance=goal.magnitude;return distance<=M2PlanningGoalDisplacement?goal:goal*(M2PlanningGoalDisplacement/Mathf.Max(distance,1e-6f));}
    public static float M2GoalLoss(float[] predicted,Vector2 goal,Vector2 heading){Vector2 target=PlanningGoal(goal);float total=GoalStepWeights.Sum(),loss=0f;for(int s=0;s<PlanningHorizon;s++){int i=s*PoseValueCount;float x=predicted[i]-target.x,y=predicted[i+1]-target.y,hs=predicted[i+2]-heading.x,hc=predicted[i+3]-heading.y;loss+=GoalStepWeights[s]*(x*x+y*y+M2HeadingLossWeight*(hs*hs+hc*hc))/total;}return loss;}
    private static float M2Loss(float[] predicted,Vector2 goal,Vector2 heading,float[,] actions,int activeLimbs,float[] gradient,out float goalLoss,out float energyLoss){Vector2 target=PlanningGoal(goal);float total=GoalStepWeights.Sum();goalLoss=0f;if(gradient!=null)Array.Clear(gradient,0,gradient.Length);for(int s=0;s<PlanningHorizon;s++){int i=s*PoseValueCount;float x=(predicted[i]-target.x)/.25f,y=(predicted[i+1]-target.y)/.25f,hs=predicted[i+2]-heading.x,hc=predicted[i+3]-heading.y,k=GoalStepWeights[s]/total;goalLoss+=k*(4f*(x*x+y*y)+hs*hs+hc*hc);if(gradient!=null){gradient[i]=8f*k*x/.25f;gradient[i+1]=8f*k*y/.25f;gradient[i+2]=2f*k*hs;gradient[i+3]=2f*k*hc;}}int limbs=Mathf.Clamp(activeLimbs,0,actions.GetLength(1)),count=Mathf.Max(1,actions.GetLength(0)*limbs);energyLoss=0f;for(int s=0;s<actions.GetLength(0);s++)for(int l=0;l<limbs;l++){float n=actions[s,l]/8f;energyLoss+=ActionEnergyWeight*n*n/count;if(s>0){float smooth=(actions[s,l]-actions[s-1,l])/8f;energyLoss+=.02f*smooth*smooth/count;}}return goalLoss+energyLoss;}
    private static void AddEnergyGradient(float[,] g,float[,] a,int activeLimbs){int limbs=Mathf.Clamp(activeLimbs,0,a.GetLength(1)),count=Mathf.Max(1,a.GetLength(0)*limbs);for(int s=0;s<a.GetLength(0);s++)for(int l=0;l<limbs;l++)g[s,l]+=2f*ActionEnergyWeight*a[s,l]/(64f*count);}

    public static float ActionBiasStrength(int tick){if(tick>=ActionBiasEndTick)return 0f;double p=Math.Max(0d,Math.Min(1d,tick/(double)ActionBiasEndTick));return Math.Max(1e-6f,(float)(.25d*(1d+Math.Cos(Math.PI*p))));}
    public static float ExplorationSigma(int updates){float p=Mathf.Clamp01(updates/(float)ExplorationDecayUpdates);return p>=1f?ExplorationFloorSigma:ExplorationStartSigma*Mathf.Pow(ExplorationFloorSigma/ExplorationStartSigma,p);}
    public float EffectiveActionBias(int tick)=>HasBidirectionalMovementEvidence?ActionBiasStrength(tick):Mathf.Max(AssistedBiasStrength,ActionBiasStrength(tick));
    public float EffectiveExplorationSigma(int freshSamples)=>HasBidirectionalMovementEvidence?ExplorationSigma(freshSamples):Mathf.Max(.15f,ExplorationSigma(freshSamples));
    public static float BiasAction(float action,float strength,int parity,int actionTick,int direction=1){if(strength<=0f)return Mathf.Clamp(action,-8f,8f);float phase=2f*Mathf.PI*Mathf.Repeat(actionTick,ScaffoldPeriodTicks)/ScaffoldPeriodTicks+(parity&1)*Mathf.PI;float target=(direction<0?-1f:1f)*strength*ScaffoldActionDegrees*Mathf.Sin(phase);return Mathf.Clamp(action+target,-8f,8f);}
    private static float[,] ApplyActionBias(float[,] raw,NativeObservation o,float strength){var result=new float[PlanningHorizon,MaxLimbs];int direction=ClassifyWorldGoalDirection(o.worldGoal.x-o.startWorldPosition.x);if(direction==0)direction=1;for(int s=0;s<PlanningHorizon;s++)for(int l=0;l<o.limbCount;l++){int parity=0;for(int i=0;i<PositionEncodingSize;i++)parity^=Mathf.RoundToInt((o.positionEncodings[l*PositionEncodingSize+i]+1f)*(i+3));result[s,l]=BiasAction(raw[s,l],strength,parity,o.tick+s*ActionTicks,direction);}return result;}
    private float[,] DecodeRhythmicActions(float[,] modifiers,NativeObservation observation,float assistance,out float frequency,out float phase,out float[,] derivative)=>DecodeRhythmicActionsInternal(modifiers,observation,assistance,oscillatorPhase,out frequency,out phase,out derivative);
    private static float[,] DecodeRhythmicActionsForTesting(float[,] modifiers,NativeObservation observation,float assistance,out float frequency,out float phase,out float[,] derivative)=>DecodeRhythmicActionsInternal(modifiers,observation,assistance,0f,out frequency,out phase,out derivative);
    private static float[,] DecodeRhythmicActionsInternal(float[,] modifiers,NativeObservation observation,float assistance,float carriedPhase,out float frequency,out float phase,out float[,] derivative)
    {
        float amount=Mathf.Clamp01(assistance/AssistedBiasStrength),rhythmBlend=.35f*amount,modifierBlend=.15f*amount;float seed=modifiers[0,0]/MaximumActionDegrees;float predictedFrequency=Mathf.Lerp(.25f,3f,((float)Math.Tanh(seed)+1f)*.5f),predictedAdjustment=(float)Math.Tanh(seed)*Mathf.PI;frequency=Mathf.Lerp(predictedFrequency,.5f,rhythmBlend);phase=carriedPhase+Mathf.Lerp(predictedAdjustment,0f,rhythmBlend);float[,] actions=new float[PlanningHorizon,MaxLimbs];derivative=new float[PlanningHorizon,MaxLimbs];for(int s=0;s<PlanningHorizon;s++)for(int l=0;l<observation.limbCount;l++){float z=Mathf.Clamp(modifiers[s,l]/MaximumActionDegrees,-1f,1f);int parity=ScaffoldParity(observation,l);float amplitude=Mathf.Lerp(4f*(z+1f),ScaffoldActionDegrees,modifierBlend),phaseOffset=Mathf.Lerp(z*Mathf.PI,parity*Mathf.PI,modifierBlend),offset=Mathf.Lerp(2f*z,0f,modifierBlend);float theta=phase+2f*Mathf.PI*frequency*((s+.5f)*ActionTicks*.02f)+phaseOffset;float raw=amplitude*Mathf.Sin(theta)+offset;actions[s,l]=Mathf.Clamp(raw,-MaximumActionDegrees,MaximumActionDegrees);float unclamped=Mathf.Abs(raw)<MaximumActionDegrees?1f:0f;derivative[s,l]=unclamped*(1f-modifierBlend)*(4f*Mathf.Sin(theta)+amplitude*Mathf.Cos(theta)*Mathf.PI+2f)/MaximumActionDegrees;}return actions;
    }
    private static int ScaffoldParity(NativeObservation observation,int limb){int root=limb*PositionEncodingSize;int hash=0;for(int i=0;i<15;i++)hash=hash*31+Mathf.RoundToInt(observation.positionEncodings[root+i]*1024f);return hash&1;}
    public static float[] JointFeatures(float angleDegrees,float speed,bool environment=false,bool self=false,bool other=false){float a=angleDegrees*Mathf.Deg2Rad,w=Mathf.Clamp(speed/720f,-1f,1f);float[] result=new float[JointFeatureSize];result[0]=Mathf.Sin(a);result[1]=Mathf.Cos(a);result[2]=w*Mathf.Cos(a);result[3]=-w*Mathf.Sin(a);result[4]=environment?1f:0f;result[5]=self?1f:0f;result[6]=other?1f:0f;return result;}
    public static float[] JointFeatures(Limb limb,Vector2 baseLocal,Vector2 tipLocal,Vector2 tipVelocity){float[] result=JointFeatures(limb.JointAngle,limb.JointSpeed,limb.TouchingEnvironment,limb.TouchingSelf,limb.TouchingOtherCreature);result[7]=Mathf.Clamp(baseLocal.x/BodyMorphologyRules.TorsoWidth,-2f,2f);result[8]=Mathf.Clamp(baseLocal.y/BodyMorphologyRules.TorsoHeight,-2f,2f);result[9]=Mathf.Clamp(tipLocal.x/BodyMorphologyRules.TorsoWidth,-2f,2f);result[10]=Mathf.Clamp(tipLocal.y/BodyMorphologyRules.TorsoHeight,-2f,2f);result[11]=Mathf.Clamp(tipVelocity.x/M3VelocityScale,-1f,1f);result[12]=Mathf.Clamp(tipVelocity.y/M3VelocityScale,-1f,1f);result[13]=limb.dimensions.x/BodyMorphologyRules.LimbWidth;result[14]=limb.dimensions.y/BodyMorphologyRules.LimbHeight;result[15]=Mathf.Clamp(limb.Mass/10f,0f,1f);result[16]=Mathf.Clamp(limb.Inertia/10f,0f,1f);result[17]=Mathf.Clamp(limb.maxMotorTorque/BodyMorphologyRules.JointTorque,0f,2f);result[18]=Mathf.Clamp(limb.ExecutedIntervalDelta/MaximumActionDegrees,-1f,1f);result[19]=Mathf.Clamp(limb.MinAngle/180f,-1f,1f);result[20]=Mathf.Clamp(limb.MaxAngle/180f,-1f,1f);result[21]=Mathf.Clamp(limb.ContactTangentialVelocity/M3VelocityScale,-1f,1f);return result;}
    public static float[] JointPositionEncoding(int[] path,int slot)=>JointPositionEncoding(path,slot,Vector2.zero);
    public static float[] JointPositionEncoding(int[] path,int slot,Vector2 baseLocal){float[] result=new float[PositionEncodingSize];int depth=Mathf.Clamp(path?.Length??0,0,MaxPathDepth);if(depth==0){path=new[]{slot};depth=1;}for(int d=0;d<depth;d++){float phase=2f*Mathf.PI*Mathf.Repeat(path[d],8)/8f;int i=d*5;result[i]=1f;result[i+1]=Mathf.Sin(phase);result[i+2]=Mathf.Cos(phase);result[i+3]=Mathf.Sin(2f*phase);result[i+4]=Mathf.Cos(2f*phase);}result[15]=depth/(float)MaxPathDepth;float x=Mathf.Clamp(baseLocal.x/BodyMorphologyRules.TorsoWidth,-2f,2f),y=Mathf.Clamp(baseLocal.y/BodyMorphologyRules.TorsoHeight,-2f,2f);result[16]=x;result[17]=y;result[18]=Mathf.Sin(Mathf.PI*x);result[19]=Mathf.Cos(Mathf.PI*x);result[20]=Mathf.Sin(Mathf.PI*y);result[21]=Mathf.Cos(Mathf.PI*y);result[22]=Mathf.Sin(2f*Mathf.PI*x);result[23]=Mathf.Cos(2f*Mathf.PI*y);return result;}
    public const float FixedGoalWorldHeight=WorldLayout.GroundTop+.5f;
    public static Vector2 FixedTrainingGoal(int tick)=>new Vector2(((Mathf.Max(0,tick)/GoalWindowTicks)&1)==0?CurriculumGoalMagnitude:-CurriculumGoalMagnitude,0f);
    public static bool CanPlaceFixedTrainingGoal(Vector2 torsoPosition,int tick)=>Mathf.Abs(torsoPosition.x+FixedTrainingGoal(tick).x)<=WorldLayout.GoalHalfWidth;
    public static int ClassifyWorldGoalDirection(float x)=>x<-.15f?-1:x>.15f?1:0;
    public static float BidirectionalFitness(float left,int ln,bool lc,float right,int rn,bool rc)=>ln<MinimumM2FitnessSamples||rn<MinimumM2FitnessSamples||!lc||!rc||!IsFinite(left)||!IsFinite(right)?float.PositiveInfinity:Mathf.Max(left,right);
    public static bool IsFinite(float value)=>!float.IsNaN(value)&&!float.IsInfinity(value);

    private void RecordFitness(float loss){if(!IsFinite(loss)||LatchedDirection==0)return;var q=LatchedDirection<0?leftLosses:rightLosses;q.Enqueue(loss);while(q.Count>M2FitnessWindow)q.Dequeue();}
    public void RecordMeasuredProgress(Vector2 d){if(LatchedDirection<0)LeftBestTrialProgress=Mathf.Max(LeftBestTrialProgress,-d.x);else if(LatchedDirection>0)RightBestTrialProgress=Mathf.Max(RightBestTrialProgress,d.x);}
    public void RepairFrom(NativeBrainWeights source){lock(trainingStateLock){Weights=source.Clone();M2Optimizer=new NativeOptimizerState();M2Protection=new NativeSynapticIntelligence();}}
    public void RelatchFixedTrainingGoal(){fixedGoalBlock=int.MinValue;hasGoal=false;}
    public NativeCreatureSave Capture(){lock(trainingStateLock)return new NativeCreatureSave{weights=Weights.Clone(),m2Optimizer=M2Optimizer.Clone(),m2Protection=M2Protection.Clone(),goalX=CurrentGoal.x,goalY=CurrentGoal.y,goalHeadingSin=CurrentGoalHeading.x,goalHeadingCos=CurrentGoalHeading.y,worldGoalX=CurrentWorldGoal.x,worldGoalY=CurrentWorldGoal.y,worldGoalHeadingSin=CurrentWorldGoalHeading.x,worldGoalHeadingCos=CurrentWorldGoalHeading.y,fixedGoalHeadingSin=fixedGoalWorldHeading.x,fixedGoalHeadingCos=fixedGoalWorldHeading.y,goalTicksRemaining=GoalTicksRemaining,fixedGoalBlock=fixedGoalBlock,m1AnchorX=m1GoalAnchor.x,m1AnchorY=m1GoalAnchor.y,m1AnchorInitialized=m1GoalAnchorInitialized,explorationState=exploration.State,oscillatorPhase=oscillatorPhase,leftLosses=leftLosses.ToList(),rightLosses=rightLosses.ToList(),leftBestProgress=LeftBestTrialProgress,rightBestProgress=RightBestTrialProgress};}
    public void Restore(NativeCreatureSave save){if(save==null)return;if(save.weights!=null)Weights=save.weights;M2Optimizer=save.m2Optimizer??new NativeOptimizerState();M2Protection=save.m2Protection??new NativeSynapticIntelligence();CurrentGoal=new Vector2(save.goalX,save.goalY);CurrentGoalHeading=NormalizeHeading(new Vector2(save.goalHeadingSin,save.goalHeadingCos),Vector2.up);CurrentWorldGoal=new Vector2(save.worldGoalX,save.worldGoalY);CurrentWorldGoalHeading=NormalizeHeading(new Vector2(save.worldGoalHeadingSin,save.worldGoalHeadingCos),Vector2.up);fixedGoalWorldHeading=NormalizeHeading(new Vector2(save.fixedGoalHeadingSin,save.fixedGoalHeadingCos),CurrentWorldGoalHeading);GoalTicksRemaining=save.goalTicksRemaining;fixedGoalBlock=save.fixedGoalBlock;m1GoalAnchor=new Vector2(save.m1AnchorX,save.m1AnchorY);m1GoalAnchorInitialized=save.m1AnchorInitialized;hasGoal=true;exploration.State=save.explorationState;oscillatorPhase=Mathf.Repeat(save.oscillatorPhase,2f*Mathf.PI);leftLosses.Clear();rightLosses.Clear();foreach(float v in (save.leftLosses??new List<float>()).TakeLast(M2FitnessWindow))leftLosses.Enqueue(v);foreach(float v in (save.rightLosses??new List<float>()).TakeLast(M2FitnessWindow))rightLosses.Enqueue(v);LeftBestTrialProgress=save.leftBestProgress;RightBestTrialProgress=save.rightBestProgress;}

    private void RunM1(float[] input,out Vector2 goalOffset,out Vector2 heading){var a=ForwardDense(input,Weights.m1Input,Weights.m1Bias,0,M1InputSize,M1Width,true).output;var b=ForwardDense(a,Weights.m1Residual,Weights.m1Bias,M1Width,M1Width,M1Width,true).output;for(int i=0;i<M1Width;i++)a[i]=(float)Math.Tanh(a[i]+b[i]);var o=ForwardDense(a,Weights.m1Output,Weights.m1Bias,M1Width*2,M1Width,4,false).output;goalOffset=new Vector2((float)Math.Tanh(o[0]),(float)Math.Tanh(o[1]));heading=NormalizeHeading(new Vector2((float)Math.Tanh(o[2]),(float)Math.Tanh(o[3])),Vector2.up);}
    private void GoalFromOutput(float[] output,float[] fallbackInput,out Vector2 goalOffset,out Vector2 heading){if(output==null||output.Length<4){RunM1(fallbackInput,out goalOffset,out heading);return;}goalOffset=new Vector2(Mathf.Clamp(output[0],-1f,1f),Mathf.Clamp(output[1],-1f,1f));heading=NormalizeHeading(new Vector2(Mathf.Clamp(output[2],-1f,1f),Mathf.Clamp(output[3],-1f,1f)),Vector2.up);}
    private static Vector2 SoftBiasedGoal(Vector2 raw){float m=Mathf.Clamp01(raw.magnitude);Vector2 d=m>.0001f?raw/m:Vector2.right;return d*(.35f+.65f*m);}
    public static Vector2 HeadingEncoding(float degrees){float radians=degrees*Mathf.Deg2Rad;return new Vector2(Mathf.Sin(radians),Mathf.Cos(radians));}
    public static Vector2 NormalizeHeading(Vector2 heading,Vector2 fallback){if(heading.sqrMagnitude>1e-8f)return heading.normalized;return fallback.sqrMagnitude>1e-8f?fallback.normalized:Vector2.up;}
    public static Vector2 HeadingTowards(Vector2 direction,float fallbackDegrees){return direction.sqrMagnitude>1e-8f?HeadingEncoding(Mathf.Atan2(direction.y,direction.x)*Mathf.Rad2Deg):HeadingEncoding(fallbackDegrees);}
    public static Vector2 RelativeHeading(Vector2 worldHeading,float sequenceStartRotationDegrees){float headingDegrees=Mathf.Atan2(worldHeading.x,worldHeading.y)*Mathf.Rad2Deg;return HeadingEncoding(headingDegrees-sequenceStartRotationDegrees);}
    private static float[] TorsoFeatures(NativeLocalProprioception p,Vector2 goal,Vector2 goalHeading,bool includeGoal,float[] terrain){float a=p.worldRotationDegrees*Mathf.Deg2Rad;float[] baseFeatures=includeGoal?new[]{p.worldPosition.x/WorldLayout.WorldHalfWidth,p.worldPosition.y/WorldLayout.SpawnRowSpacing,p.localLinearVelocity.x,p.localLinearVelocity.y,Mathf.Sin(a),Mathf.Cos(a),goal.x,goal.y,goalHeading.x,goalHeading.y}:new[]{p.worldPosition.x/WorldLayout.WorldHalfWidth,p.worldPosition.y/WorldLayout.SpawnRowSpacing,p.localLinearVelocity.x,p.localLinearVelocity.y,Mathf.Sin(a),Mathf.Cos(a)};float[] result=new float[baseFeatures.Length+12];Array.Copy(baseFeatures,result,baseFeatures.Length);if(terrain!=null)Array.Copy(terrain,0,result,baseFeatures.Length,Mathf.Min(12,terrain.Length));return result;}
    private float Gaussian(){float a=Mathf.Max(1e-7f,exploration.NextFloat()),b=exploration.NextFloat();return Mathf.Sqrt(-2f*Mathf.Log(a))*Mathf.Cos(2f*Mathf.PI*b);}
    private static float Mean(IEnumerable<float> values){int n=0;float sum=0f;foreach(float v in values){sum+=v;n++;}return n==0?float.PositiveInfinity:sum/n;}

    private static M2Cache ForwardM2(NativeObservation o,NativeBrainWeights w)
    {
        var c=new M2Cache{observation=o,context=ForwardDense(o.torsoWithGoal,w.m2Context,w.m2Bias,0,M2ContextSize,Hidden,true),limbs=new JointCache[o.limbCount],actions=new float[PlanningHorizon,MaxLimbs]};float[][] tokens=new float[o.limbCount][];
        for(int l=0;l<o.limbCount;l++){c.limbs[l]=ForwardJoint(Slice(o.jointFeatures,l*JointFeatureSize,JointFeatureSize),Slice(o.positionEncodings,l*PositionEncodingSize,PositionEncodingSize),w.m2Joint,w.m2Position,w.m2Bias,Hidden);tokens[l]=c.limbs[l].output;}
        c.attention=ForwardAttention(tokens,w.m2AttentionQuery,w.m2AttentionKey,w.m2AttentionValue,w.m2Norm,0,M2AttentionHeads);c.attention2=ForwardAttention(c.attention.output,w.m2AttentionQuery2,w.m2AttentionKey2,w.m2AttentionValue2,w.m2Norm,Hidden,M2AttentionHeads);c.heads=new MlpCache[o.limbCount];c.steps=new StepDecoderCache[o.limbCount][];
        for(int l=0;l<o.limbCount;l++){c.heads[l]=ForwardMlp(Concat(c.attention2.output[l],c.context.output),w.m2Fusion,w.m2Residual,new[]{w.m2Deep1,w.m2Deep2,w.m2Deep3,w.m2Deep4,w.m2Deep5,w.m2Deep6,w.m2Deep7,w.m2Deep8},w.m2Bias,w.m2Norm,Hidden*2);c.steps[l]=new StepDecoderCache[PlanningHorizon];for(int s=0;s<PlanningHorizon;s++){float[] input=new float[Hidden];for(int h=0;h<Hidden;h++)input[h]=c.heads[l].output[h]+w.m2StepEmbedding[s*Hidden+h];var norm=ForwardRms(input,w.m2Norm,Hidden*10);var layer=ForwardDense(norm.output,w.m2Output,w.m2Bias,Hidden*12,Hidden,1,false);float value=(float)Math.Tanh(layer.pre[0])*MaximumActionDegrees;c.steps[l][s]=new StepDecoderCache{step=s,input=input,norm=norm,layer=layer,output=value};c.actions[s,l]=value;}}return c;
    }
    private static void BackwardM2(M2Cache c,float[,] actionGradient,NativeBrainWeights w,Dictionary<string,float[]> g)
    {
        float[][] attentionGradient=Enumerable.Range(0,c.observation.limbCount).Select(_=>new float[Hidden]).ToArray();float[] contextGradient=new float[Hidden];
        for(int l=0;l<c.observation.limbCount;l++){float[] hiddenGradient=new float[Hidden];for(int s=0;s<PlanningHorizon;s++){var step=c.steps[l][s];float t=step.output/MaximumActionDegrees;float[] raw={actionGradient[s,l]*MaximumActionDegrees*(1f-t*t)};float[] normalizedGradient=BackwardDense(step.layer,raw,w.m2Output,g["output"],g["bias"]);float[] ig=BackwardRms(step.norm,normalizedGradient,g["norm"]);for(int h=0;h<Hidden;h++){hiddenGradient[h]+=ig[h];g["stepEmbedding"][s*Hidden+h]+=ig[h];}}float[] fg=BackwardMlp(c.heads[l],hiddenGradient,w.m2Fusion,w.m2Residual,new[]{w.m2Deep1,w.m2Deep2,w.m2Deep3,w.m2Deep4,w.m2Deep5,w.m2Deep6,w.m2Deep7,w.m2Deep8},g["fusion"],g["residual"],new[]{g["deep1"],g["deep2"],g["deep3"],g["deep4"],g["deep5"],g["deep6"],g["deep7"],g["deep8"]},g["bias"],g["norm"]);Array.Copy(fg,attentionGradient[l],Hidden);for(int h=0;h<Hidden;h++)contextGradient[h]+=fg[Hidden+h];}
        float[][] firstBlockGradient=BackwardAttention(c.attention2,attentionGradient,w.m2AttentionQuery2,w.m2AttentionKey2,w.m2AttentionValue2,g["attentionQuery2"],g["attentionKey2"],g["attentionValue2"],g["norm"]);float[][] tg=BackwardAttention(c.attention,firstBlockGradient,w.m2AttentionQuery,w.m2AttentionKey,w.m2AttentionValue,g["attentionQuery"],g["attentionKey"],g["attentionValue"],g["norm"]);for(int l=0;l<c.observation.limbCount;l++)BackwardJoint(c.limbs[l],tg[l],w.m2Joint,w.m2Position,g["joint"],g["position"],g["bias"],Hidden);BackwardDense(c.context,contextGradient,w.m2Context,g["context"],g["bias"]);
    }
    private static M3Cache ForwardM3(NativeObservation o,float[,] actions,NativeDynamicsWeights w)
    {
        var c=new M3Cache{observation=o,actions=actions,context=ForwardDense(o.torsoWithoutGoal,w.context,w.bias,0,M3ContextSize,Hidden,true),limbs=new JointCache[o.limbCount]};float[][] tokens=new float[o.limbCount][];
        for(int l=0;l<o.limbCount;l++){float[] input=new float[M3JointInputSize];Array.Copy(o.jointFeatures,l*JointFeatureSize,input,0,JointFeatureSize);for(int s=0;s<PlanningHorizon;s++)input[JointFeatureSize+s]=actions[s,l]/MaximumActionDegrees;c.limbs[l]=ForwardJoint(input,Slice(o.positionEncodings,l*PositionEncodingSize,PositionEncodingSize),w.joint,w.position,w.bias,Hidden);tokens[l]=c.limbs[l].output;}
        c.attention=ForwardAttention(tokens,w.attentionQuery,w.attentionKey,w.attentionValue,w.norm,0,M3AttentionHeads);
        float[][] queries=new float[PlanningHorizon][];for(int s=0;s<PlanningHorizon;s++){queries[s]=new float[Hidden];for(int h=0;h<Hidden;h++)queries[s][h]=c.context.output[h]+w.horizonQueries[s*Hidden+h];}c.cross=ForwardCrossAttention(queries,c.attention.output,w.crossQuery,w.crossKey,w.crossValue,w.norm,Hidden,Hidden*2,M3AttentionHeads);c.heads=new MlpCache[PlanningHorizon];c.outputLayers=new DenseCache[PlanningHorizon];c.rawOutputs=new float[PlanningHorizon][];c.prediction=new float[M3OutputSize];c.auxiliary=new float[M3AuxiliaryOutputSize];
        for(int s=0;s<PlanningHorizon;s++){c.heads[s]=ForwardMlp(Concat(c.cross.output[s],c.context.output),w.fusion,w.residual,new[]{w.deep1,w.deep2,w.deep3,w.deep4,w.deep5,w.deep6},w.bias,w.norm,Hidden*3);c.outputLayers[s]=ForwardDense(c.heads[s].output,w.output,w.bias,Hidden*10,Hidden,M3ValuesPerHorizon,false);c.rawOutputs[s]=new float[M3ValuesPerHorizon];int endpointEnd=PoseValueCount+MaxLimbs*EndpointValueCount;for(int j=0;j<endpointEnd;j++)c.rawOutputs[s][j]=j<2||j>=PoseValueCount?c.outputLayers[s].pre[j]:(float)Math.Tanh(c.outputLayers[s].pre[j]);float norm=Mathf.Sqrt(c.rawOutputs[s][2]*c.rawOutputs[s][2]+c.rawOutputs[s][3]*c.rawOutputs[s][3]);if(norm>1e-5f){c.rawOutputs[s][2]/=norm;c.rawOutputs[s][3]/=norm;}else{c.rawOutputs[s][2]=0f;c.rawOutputs[s][3]=1f;}for(int j=endpointEnd;j<M3ValuesPerHorizon;j++)c.rawOutputs[s][j]=Sigmoid(c.outputLayers[s].pre[j]);for(int j=0;j<PoseValueCount;j++)c.prediction[s*PoseValueCount+j]=c.rawOutputs[s][j];for(int j=0;j<AuxiliaryValueCount;j++)c.auxiliary[s*AuxiliaryValueCount+j]=c.rawOutputs[s][PoseValueCount+j];}return c;
    }
    private static float[,] BackwardM3(M3Cache c,float[] poseGradient,float[] auxiliaryGradient,NativeDynamicsWeights w,Dictionary<string,float[]> supplied)
    {
        var g=supplied;float[][] crossGradient=Enumerable.Range(0,PlanningHorizon).Select(_=>new float[Hidden]).ToArray();float[] contextGradient=new float[Hidden];
        for(int s=0;s<PlanningHorizon;s++){float[] og=new float[M3ValuesPerHorizon];for(int j=0;j<PoseValueCount;j++)og[j]=(poseGradient?[s*PoseValueCount+j]).GetValueOrDefault();for(int j=0;j<AuxiliaryValueCount;j++)og[PoseValueCount+j]=(auxiliaryGradient?[s*AuxiliaryValueCount+j]).GetValueOrDefault();int endpointEnd=PoseValueCount+MaxLimbs*EndpointValueCount;for(int j=2;j<4;j++)og[j]*=1f-c.rawOutputs[s][j]*c.rawOutputs[s][j];for(int j=4;j<6;j++)og[j]*=1f-c.rawOutputs[s][j]*c.rawOutputs[s][j];for(int j=endpointEnd;j<M3ValuesPerHorizon;j++)og[j]*=c.rawOutputs[s][j]*(1f-c.rawOutputs[s][j]);float[] hidden=BackwardDense(c.outputLayers[s],og,w.output,G(g,"output"),G(g,"bias"));float[] fg=BackwardMlp(c.heads[s],hidden,w.fusion,w.residual,new[]{w.deep1,w.deep2,w.deep3,w.deep4,w.deep5,w.deep6},G(g,"fusion"),G(g,"residual"),new[]{G(g,"deep1"),G(g,"deep2"),G(g,"deep3"),G(g,"deep4"),G(g,"deep5"),G(g,"deep6")},G(g,"bias"),G(g,"norm"));Array.Copy(fg,crossGradient[s],Hidden);for(int h=0;h<Hidden;h++)contextGradient[h]+=fg[Hidden+h];}
        CrossBackward cb=BackwardCrossAttention(c.cross,crossGradient,w.crossQuery,w.crossKey,w.crossValue,G(g,"crossQuery"),G(g,"crossKey"),G(g,"crossValue"),G(g,"norm"));for(int s=0;s<PlanningHorizon;s++)for(int h=0;h<Hidden;h++){contextGradient[h]+=cb.queryGradient[s][h];if(g!=null)g["horizonQueries"][s*Hidden+h]+=cb.queryGradient[s][h];}
        float[][] tg=BackwardAttention(c.attention,cb.tokenGradient,w.attentionQuery,w.attentionKey,w.attentionValue,G(g,"attentionQuery"),G(g,"attentionKey"),G(g,"attentionValue"),G(g,"norm"));float[,] result=new float[PlanningHorizon,MaxLimbs];for(int l=0;l<c.observation.limbCount;l++){float[] ig=BackwardJoint(c.limbs[l],tg[l],w.joint,w.position,G(g,"joint"),G(g,"position"),G(g,"bias"),Hidden);for(int s=0;s<PlanningHorizon;s++)result[s,l]=ig[JointFeatureSize+s]/MaximumActionDegrees;}BackwardDense(c.context,contextGradient,w.context,G(g,"context"),G(g,"bias"));return result;
    }

    private static JointCache ForwardJoint(float[] input,float[] position,float[] iw,float[] pw,float[] bias,int offset){var c=new JointCache{input=input,position=position,pre=new float[Hidden],output=new float[Hidden]};for(int h=0;h<Hidden;h++){float v=bias[offset+h];for(int i=0;i<input.Length;i++)v+=input[i]*iw[i*Hidden+h];for(int i=0;i<position.Length;i++)v+=position[i]*pw[i*Hidden+h];c.pre[h]=v;c.output[h]=SiLU(v);}return c;}
    private static float[] BackwardJoint(JointCache c,float[] og,float[] iw,float[] pw,float[] iwg,float[] pwg,float[] bg,int offset){float[] ig=new float[c.input.Length];for(int h=0;h<Hidden;h++){float g=og[h]*SiLUDerivative(c.pre[h]);if(bg!=null)bg[offset+h]+=g;for(int i=0;i<c.input.Length;i++){if(iwg!=null)iwg[i*Hidden+h]+=c.input[i]*g;ig[i]+=iw[i*Hidden+h]*g;}for(int i=0;i<c.position.Length;i++)if(pwg!=null)pwg[i*Hidden+h]+=c.position[i]*g;}return ig;}
    private static AttentionCache ForwardAttention(float[][] input,float[] qw,float[] kw,float[] vw,float[] gamma,int gammaOffset,int heads)
    {
        int n=input.Length;var c=new AttentionCache{input=input,normalized=new RmsCache[n],q=new float[n][],k=new float[n][],v=new float[n][],output=new float[n][],probability=new float[heads,n,n],heads=heads};for(int i=0;i<n;i++){c.normalized[i]=ForwardRms(input[i],gamma,gammaOffset);c.q[i]=Linear(c.normalized[i].output,qw);c.k[i]=Linear(c.normalized[i].output,kw);c.v[i]=Linear(c.normalized[i].output,vw);c.output[i]=(float[])input[i].Clone();}
        for(int head=0;head<heads;head++){int start=AttentionHeadStart(head,heads),headWidth=AttentionHeadWidth(head,heads);float scale=1f/Mathf.Sqrt(headWidth);float[] scores=new float[n];for(int i=0;i<n;i++){float max=float.NegativeInfinity,sum=0f;for(int j=0;j<n;j++){float dot=0f;for(int h=0;h<headWidth;h++)dot+=c.q[i][start+h]*c.k[j][start+h];scores[j]=dot*scale;max=Mathf.Max(max,scores[j]);}for(int j=0;j<n;j++){c.probability[head,i,j]=Mathf.Exp(Mathf.Clamp(scores[j]-max,-20f,20f));sum+=c.probability[head,i,j];}for(int j=0;j<n;j++)c.probability[head,i,j]/=Mathf.Max(1e-8f,sum);for(int h=0;h<headWidth;h++){int index=start+h;for(int j=0;j<n;j++)c.output[i][index]+=c.probability[head,i,j]*c.v[j][index];}}}return c;
    }
    private static float[][] BackwardAttention(AttentionCache c,float[][] og,float[] qw,float[] kw,float[] vw,float[] qwg,float[] kwg,float[] vwg,float[] gammaGradient)
    {
        int n=c.input.Length;float[][] ig=Enumerable.Range(0,n).Select(_=>new float[Hidden]).ToArray(),qg=Enumerable.Range(0,n).Select(_=>new float[Hidden]).ToArray(),kg=Enumerable.Range(0,n).Select(_=>new float[Hidden]).ToArray(),vg=Enumerable.Range(0,n).Select(_=>new float[Hidden]).ToArray();float[,,] pg=new float[c.heads,n,n];
        for(int head=0;head<c.heads;head++){int start=AttentionHeadStart(head,c.heads),headWidth=AttentionHeadWidth(head,c.heads);for(int i=0;i<n;i++)for(int h=0;h<headWidth;h++){int index=start+h;float gradient=og[i][index];ig[i][index]+=gradient;for(int j=0;j<n;j++){pg[head,i,j]+=gradient*c.v[j][index];vg[j][index]+=gradient*c.probability[head,i,j];}}}
        for(int head=0;head<c.heads;head++){int start=AttentionHeadStart(head,c.heads),headWidth=AttentionHeadWidth(head,c.heads);float scale=1f/Mathf.Sqrt(headWidth);for(int i=0;i<n;i++){float mean=0f;for(int j=0;j<n;j++)mean+=pg[head,i,j]*c.probability[head,i,j];for(int j=0;j<n;j++){float scoreGradient=c.probability[head,i,j]*(pg[head,i,j]-mean)*scale;for(int h=0;h<headWidth;h++){int index=start+h;qg[i][index]+=scoreGradient*c.k[j][index];kg[j][index]+=scoreGradient*c.q[i][index];}}}}
        for(int i=0;i<n;i++){float[] ng=new float[Hidden];BackwardLinear(c.normalized[i].output,qg[i],qw,qwg,ng);BackwardLinear(c.normalized[i].output,kg[i],kw,kwg,ng);BackwardLinear(c.normalized[i].output,vg[i],vw,vwg,ng);float[] rg=BackwardRms(c.normalized[i],ng,gammaGradient);for(int h=0;h<Hidden;h++)ig[i][h]+=rg[h];}return ig;
    }
    private static CrossAttentionCache ForwardCrossAttention(float[][] queries,float[][] tokens,float[] qw,float[] kw,float[] vw,float[] gamma,int queryGammaOffset,int tokenGammaOffset,int heads)
    {
        int qn=queries.Length,n=tokens.Length;var c=new CrossAttentionCache{queries=queries,tokens=tokens,normalizedQueries=new RmsCache[qn],normalizedTokens=new RmsCache[n],q=new float[qn][],k=new float[n][],v=new float[n][],output=new float[qn][],probability=new float[heads,qn,n],heads=heads};for(int i=0;i<qn;i++){c.normalizedQueries[i]=ForwardRms(queries[i],gamma,queryGammaOffset);c.q[i]=Linear(c.normalizedQueries[i].output,qw);c.output[i]=(float[])queries[i].Clone();}for(int j=0;j<n;j++){c.normalizedTokens[j]=ForwardRms(tokens[j],gamma,tokenGammaOffset);c.k[j]=Linear(c.normalizedTokens[j].output,kw);c.v[j]=Linear(c.normalizedTokens[j].output,vw);}int hw=Hidden/heads;float[] scores=new float[n];for(int head=0;head<heads;head++){int start=head*hw;float scale=1f/Mathf.Sqrt(hw);for(int i=0;i<qn;i++){float max=float.NegativeInfinity,sum=0f;for(int j=0;j<n;j++){float dot=0f;for(int h=0;h<hw;h++)dot+=c.q[i][start+h]*c.k[j][start+h];scores[j]=dot*scale;max=Mathf.Max(max,scores[j]);}for(int j=0;j<n;j++){float p=Mathf.Exp(Mathf.Clamp(scores[j]-max,-20f,20f));c.probability[head,i,j]=p;sum+=p;}for(int j=0;j<n;j++)c.probability[head,i,j]/=Mathf.Max(1e-8f,sum);for(int h=0;h<hw;h++)for(int j=0;j<n;j++)c.output[i][start+h]+=c.probability[head,i,j]*c.v[j][start+h];}}return c;
    }
    private static CrossBackward BackwardCrossAttention(CrossAttentionCache c,float[][] og,float[] qw,float[] kw,float[] vw,float[] qwg,float[] kwg,float[] vwg,float[] gammaGradient)
    {
        int qn=c.queries.Length,n=c.tokens.Length,hw=Hidden/c.heads;float[][] qig=Enumerable.Range(0,qn).Select(_=>new float[Hidden]).ToArray(),tig=Enumerable.Range(0,n).Select(_=>new float[Hidden]).ToArray(),qg=Enumerable.Range(0,qn).Select(_=>new float[Hidden]).ToArray(),kg=Enumerable.Range(0,n).Select(_=>new float[Hidden]).ToArray(),vg=Enumerable.Range(0,n).Select(_=>new float[Hidden]).ToArray();float[,,] pg=new float[c.heads,qn,n];for(int i=0;i<qn;i++)Array.Copy(og[i],qig[i],Hidden);for(int head=0;head<c.heads;head++){int start=head*hw;for(int i=0;i<qn;i++)for(int h=0;h<hw;h++){int x=start+h;for(int j=0;j<n;j++){pg[head,i,j]+=og[i][x]*c.v[j][x];vg[j][x]+=og[i][x]*c.probability[head,i,j];}}}for(int head=0;head<c.heads;head++){int start=head*hw;float scale=1f/Mathf.Sqrt(hw);for(int i=0;i<qn;i++){float mean=0f;for(int j=0;j<n;j++)mean+=pg[head,i,j]*c.probability[head,i,j];for(int j=0;j<n;j++){float sg=c.probability[head,i,j]*(pg[head,i,j]-mean)*scale;for(int h=0;h<hw;h++){int x=start+h;qg[i][x]+=sg*c.k[j][x];kg[j][x]+=sg*c.q[i][x];}}}}for(int i=0;i<qn;i++){float[] normalizedGradient=new float[Hidden];BackwardLinear(c.normalizedQueries[i].output,qg[i],qw,qwg,normalizedGradient);float[] rmsGradient=BackwardRms(c.normalizedQueries[i],normalizedGradient,gammaGradient);for(int h=0;h<Hidden;h++)qig[i][h]+=rmsGradient[h];}for(int j=0;j<n;j++){float[] normalizedGradient=new float[Hidden];BackwardLinear(c.normalizedTokens[j].output,kg[j],kw,kwg,normalizedGradient);BackwardLinear(c.normalizedTokens[j].output,vg[j],vw,vwg,normalizedGradient);tig[j]=BackwardRms(c.normalizedTokens[j],normalizedGradient,gammaGradient);}return new CrossBackward{queryGradient=qig,tokenGradient=tig};
    }

    private static MlpCache ForwardMlp(float[] input,float[] fw,float[] rw,float[][] deep,float[] bias,float[] norm,int normOffset)
    {
        var c=new MlpCache{fusion=ForwardDense(input,fw,bias,Hidden*2,Hidden*2,Hidden,true),norms=new RmsCache[deep.Length+1]};c.norms[0]=ForwardRms(c.fusion.output,norm,normOffset);c.residual=ForwardDense(c.norms[0].output,rw,bias,Hidden*3,Hidden,Hidden,true);c.merged=new float[Hidden];for(int h=0;h<Hidden;h++)c.merged[h]=c.fusion.output[h]+c.residual.output[h];c.deepLayers=new DenseCache[deep.Length];float[] current=c.merged;for(int i=0;i<deep.Length;i++){c.norms[i+1]=ForwardRms(current,norm,normOffset+Hidden*(i+1));c.deepLayers[i]=ForwardDense(c.norms[i+1].output,deep[i],bias,Hidden*(4+i),Hidden,Hidden,true);float[] next=new float[Hidden];for(int h=0;h<Hidden;h++)next[h]=current[h]+c.deepLayers[i].output[h];current=next;}c.output=current;return c;
    }
    private static float[] BackwardMlp(MlpCache c,float[] og,float[] fw,float[] rw,float[][] deep,float[] fwg,float[] rwg,float[][] deepg,float[] bg,float[] normGradient)
    {
        float[] gradient=(float[])og.Clone();for(int i=c.deepLayers.Length-1;i>=0;i--){float[] normalized=BackwardDense(c.deepLayers[i],gradient,deep[i],deepg?[i],bg);float[] extra=BackwardRms(c.norms[i+1],normalized,normGradient);for(int h=0;h<Hidden;h++)gradient[h]+=extra[h];}float[] fusionGradient=(float[])gradient.Clone();float[] residualNormalized=BackwardDense(c.residual,gradient,rw,rwg,bg);float[] residualInput=BackwardRms(c.norms[0],residualNormalized,normGradient);for(int h=0;h<Hidden;h++)fusionGradient[h]+=residualInput[h];return BackwardDense(c.fusion,fusionGradient,fw,fwg,bg);
    }

    private static RmsCache ForwardRms(float[] input,float[] gamma,int offset){float mean=0f;for(int i=0;i<Hidden;i++)mean+=input[i]*input[i]/Hidden;float inv=1f/Mathf.Sqrt(mean+RmsNormEpsilon);float[] output=new float[Hidden],used=new float[Hidden];for(int i=0;i<Hidden;i++){used[i]=gamma[offset+i];output[i]=input[i]*used[i]*inv;}return new RmsCache{input=input,output=output,gamma=used,gammaOffset=offset,inverse=inv};}
    private static float[] BackwardRms(RmsCache c,float[] og,float[] gammaGradient){float dot=0f;for(int i=0;i<Hidden;i++){dot+=og[i]*c.gamma[i]*c.input[i];if(gammaGradient!=null)gammaGradient[c.gammaOffset+i]+=og[i]*c.input[i]*c.inverse;}float correction=c.inverse*c.inverse*c.inverse*dot/Hidden;float[] ig=new float[Hidden];for(int i=0;i<Hidden;i++)ig[i]=og[i]*c.gamma[i]*c.inverse-c.input[i]*correction;return ig;}
    private static HeadCache ForwardHead(float[] input,float[] fw,float[] rw,float[][] deep,float[] ow,float[] bias,int outputCount,float scale){var c=new HeadCache{fusion=ForwardDense(input,fw,bias,Hidden*2,Hidden*2,Hidden,true),outputScale=scale};c.residual=ForwardDense(c.fusion.output,rw,bias,Hidden*3,Hidden,Hidden,true);c.merged=new float[Hidden];for(int h=0;h<Hidden;h++)c.merged[h]=(float)Math.Tanh(c.fusion.output[h]+c.residual.output[h]);c.deepLayers=new DenseCache[deep.Length];float[] current=c.merged;for(int i=0;i<deep.Length;i++){c.deepLayers[i]=ForwardDense(current,deep[i],bias,Hidden*(4+i),Hidden,Hidden,true);current=c.deepLayers[i].output;}c.outputLayer=ForwardDense(current,ow,bias,Hidden*(4+deep.Length),Hidden,outputCount,false);c.output=new float[outputCount];for(int i=0;i<outputCount;i++)c.output[i]=(float)Math.Tanh(c.outputLayer.pre[i])*scale;return c;}
    private static float[] BackwardHead(HeadCache c,float[] og,float[] fw,float[] rw,float[][] deep,float[] ow,float[] fwg,float[] rwg,float[][] deepg,float[] owg,float[] bg){float[] pg=new float[og.Length];for(int i=0;i<og.Length;i++){float t=c.output[i]/c.outputScale;pg[i]=og[i]*c.outputScale*(1f-t*t);}float[] mg=BackwardDense(c.outputLayer,pg,ow,owg,bg);for(int i=c.deepLayers.Length-1;i>=0;i--)mg=BackwardDense(c.deepLayers[i],mg,deep[i],deepg[i],bg);float[] fg=new float[Hidden],rg=new float[Hidden];for(int h=0;h<Hidden;h++){float gradient=mg[h]*(1f-c.merged[h]*c.merged[h]);fg[h]=gradient;rg[h]=gradient;}float[] extra=BackwardDense(c.residual,rg,rw,rwg,bg);for(int h=0;h<Hidden;h++)fg[h]+=extra[h];return BackwardDense(c.fusion,fg,fw,fwg,bg);}
    private static DenseCache ForwardDense(float[] input,float[] weights,float[] bias,int offset,int inputCount,int outputCount,bool activate){var c=new DenseCache{input=input,pre=new float[outputCount],output=new float[outputCount],biasOffset=offset,activate=activate};for(int o=0;o<outputCount;o++){float v=bias[offset+o];for(int i=0;i<inputCount;i++)v+=input[i]*weights[i*outputCount+o];c.pre[o]=v;c.output[o]=activate?SiLU(v):v;}return c;}
    private static float[] BackwardDense(DenseCache c,float[] og,float[] weights,float[] wg,float[] bg){int outputs=og.Length;float[] ig=new float[c.input.Length];for(int o=0;o<outputs;o++){float g=og[o]*(c.activate?SiLUDerivative(c.pre[o]):1f);if(bg!=null)bg[c.biasOffset+o]+=g;for(int i=0;i<c.input.Length;i++){if(wg!=null)wg[i*outputs+o]+=c.input[i]*g;ig[i]+=weights[i*outputs+o]*g;}}return ig;}
    private static Dictionary<string,float[]> Zero(IEnumerable<KeyValuePair<string,float[]>> parameters){var g=new Dictionary<string,float[]>();foreach(var p in parameters)g[p.Key]=new float[p.Value.Length];return g;}
    private static void ApplyAdam(IEnumerable<KeyValuePair<string,float[]>> parameters,Dictionary<string,float[]> gradients,NativeOptimizerState optimizer,float learningRate,NativeSynapticIntelligence protection=null){var list=parameters.ToList();protection?.BeginStep(list,gradients);protection?.AddPenalty(list,gradients);float norm2=0f;foreach(float[] values in gradients.Values)for(int i=0;i<values.Length;i++)norm2+=values[i]*values[i];float clip=1f/Mathf.Max(1f,Mathf.Sqrt(norm2));optimizer.step++;float firstCorrection=1f-Mathf.Pow(.9f,optimizer.step),secondCorrection=1f-Mathf.Pow(.999f,optimizer.step);foreach(var p in list){var slot=optimizer.Get(p.Key,p.Value.Length);float[] g=gradients[p.Key];for(int i=0;i<p.Value.Length;i++){float v=g[i]*clip;slot.first[i]=.9f*slot.first[i]+.1f*v;slot.second[i]=.999f*slot.second[i]+.001f*v*v;float mh=slot.first[i]/firstCorrection,vh=slot.second[i]/secondCorrection;p.Value[i]-=learningRate*mh/(Mathf.Sqrt(vh)+1e-8f);}}protection?.EndStep(list,optimizer.step);}
    private static float[] Linear(float[] input,float[] weights){float[] o=new float[Hidden];for(int i=0;i<Hidden;i++)for(int h=0;h<Hidden;h++)o[h]+=input[i]*weights[i*Hidden+h];return o;}
    private static int AttentionHeadStart(int head,int heads)=>head*Hidden/heads;
    private static int AttentionHeadWidth(int head,int heads)=>(head+1)*Hidden/heads-AttentionHeadStart(head,heads);
    private static void BackwardLinear(float[] input,float[] og,float[] weights,float[] wg,float[] ig){for(int i=0;i<Hidden;i++)for(int h=0;h<Hidden;h++){if(wg!=null)wg[i*Hidden+h]+=input[i]*og[h];ig[i]+=weights[i*Hidden+h]*og[h];}}
    public static float SiLU(float value)=>value*Sigmoid(value);
    public static float SiLUDerivative(float value){float s=Sigmoid(value);return s+value*s*(1f-s);}
    public static float[] RmsNormForTesting(float[] input,float[] gamma){int n=input.Length;float mean=0f;for(int i=0;i<n;i++)mean+=input[i]*input[i]/n;float inv=1f/Mathf.Sqrt(mean+RmsNormEpsilon);float[] output=new float[n];for(int i=0;i<n;i++)output[i]=input[i]*gamma[i]*inv;return output;}
    public static float[] RmsNormInputGradientForTesting(float[] input,float[] gamma,float[] upstream){int n=input.Length;float mean=0f,dot=0f;for(int i=0;i<n;i++){mean+=input[i]*input[i]/n;dot+=upstream[i]*gamma[i]*input[i];}float inv=1f/Mathf.Sqrt(mean+RmsNormEpsilon),correction=inv*inv*inv*dot/n;float[] gradient=new float[n];for(int i=0;i<n;i++)gradient[i]=upstream[i]*gamma[i]*inv-input[i]*correction;return gradient;}
    private static float Sigmoid(float value){value=Mathf.Clamp(value,-30f,30f);return 1f/(1f+Mathf.Exp(-value));}
    private static float[] G(Dictionary<string,float[]> gradients,string name)=>gradients==null?null:gradients[name];
    private static float Dot(float[] a,float[] b){float v=0f;for(int i=0;i<a.Length;i++)v+=a[i]*b[i];return v;}
    private static float SumAbsDifference(float[] a,float[] b){float total=0f;for(int i=0;i<Math.Min(a.Length,b.Length);i++)total+=Mathf.Abs(a[i]-b[i]);return total;}
    private static float[] Slice(float[] a,int start,int count){float[] r=new float[count];Array.Copy(a,start,r,0,count);return r;}
    private static float[] Concat(float[] a,float[] b){float[] r=new float[a.Length+b.Length];Array.Copy(a,r,a.Length);Array.Copy(b,0,r,a.Length,b.Length);return r;}
    private static float[] MeanTokens(float[][] tokens){float[] r=new float[Hidden];if(tokens.Length==0)return r;foreach(float[] t in tokens)for(int h=0;h<Hidden;h++)r[h]+=t[h]/tokens.Length;return r;}
}

[Serializable] public sealed class NativeOptimizerSlot{public string name;[JsonIgnore] public float[] first,second;}
[Serializable] public sealed class NativeDeterministicRng{public ulong State;public NativeDeterministicRng():this(1UL){}public NativeDeterministicRng(ulong seed){State=seed==0?1UL:seed;}private ulong NextRaw(){State^=State<<13;State^=State>>7;State^=State<<17;return State;}public ulong NextUInt64()=>NextRaw();public float NextFloat()=>((NextRaw()>>40)&0xFFFFFF)/(float)0x1000000;public int NextInt(int exclusiveMax){if(exclusiveMax<=0)throw new ArgumentOutOfRangeException(nameof(exclusiveMax));uint bound=(uint)exclusiveMax,threshold=unchecked(0u-bound)%bound;uint value;do{value=(uint)NextRaw();}while(value<threshold);return (int)(value%bound);}public long NextLong(long exclusiveMax){if(exclusiveMax<=0)throw new ArgumentOutOfRangeException(nameof(exclusiveMax));ulong bound=(ulong)exclusiveMax,threshold=unchecked(0UL-bound)%bound,value;do{value=NextRaw();}while(value<threshold);return (long)(value%bound);}}
[Serializable] public sealed class NativeOptimizerState{public int step;[JsonIgnore] public List<NativeOptimizerSlot> slots=new List<NativeOptimizerSlot>();public NativeOptimizerSlot Get(string name,int length){if(slots==null)slots=new List<NativeOptimizerSlot>();var s=slots.FirstOrDefault(v=>v.name==name);if(s==null){s=new NativeOptimizerSlot{name=name};slots.Add(s);}if(s.first==null||s.first.Length!=length)s.first=new float[length];if(s.second==null||s.second.Length!=length)s.second=new float[length];return s;}public NativeOptimizerState Clone(){var copy=new NativeOptimizerState{step=step};foreach(var slot in slots??new List<NativeOptimizerSlot>())copy.slots.Add(new NativeOptimizerSlot{name=slot.name,first=slot.first==null?null:(float[])slot.first.Clone(),second=slot.second==null?null:(float[])slot.second.Clone()});return copy;}}
[Serializable] public sealed class NativeObservation
{
    public float[] torsoWithGoal,torsoWithoutGoal,jointFeatures,positionEncodings,limbMask;
    public int[] parentSlots;
    public int limbCount,tick,episode;public string controllerId,bodySignature;public bool practice;
    public float goalX,goalY,goalHeadingSin,goalHeadingCos,worldGoalX,worldGoalY,worldGoalHeadingSin,worldGoalHeadingCos,startWorldX,startWorldY,startWorldRotationDegrees;
    [JsonIgnore] public Vector2 goal{get=>new Vector2(goalX,goalY);set{goalX=value.x;goalY=value.y;}}
    [JsonIgnore] public Vector2 goalHeading{get=>new Vector2(goalHeadingSin,goalHeadingCos);set{goalHeadingSin=value.x;goalHeadingCos=value.y;}}
    [JsonIgnore] public Vector2 worldGoal{get=>new Vector2(worldGoalX,worldGoalY);set{worldGoalX=value.x;worldGoalY=value.y;}}
    [JsonIgnore] public Vector2 worldGoalHeading{get=>new Vector2(worldGoalHeadingSin,worldGoalHeadingCos);set{worldGoalHeadingSin=value.x;worldGoalHeadingCos=value.y;}}
    [JsonIgnore] public Vector2 startWorldPosition{get=>new Vector2(startWorldX,startWorldY);set{startWorldX=value.x;startWorldY=value.y;}}
}
[Serializable] public sealed class NativePosePrediction{public readonly float[] poses;public NativePosePrediction(float[] values){poses=values??new float[NativeCreatureModel.M3OutputSize];}public Vector2 PositionAt(int step){int i=step*NativeCreatureModel.PoseValueCount;return new Vector2(poses[i],poses[i+1]);}public Vector2 HeadingAt(int step){int i=step*NativeCreatureModel.PoseValueCount;return new Vector2(poses[i+2],poses[i+3]);}}
public sealed class NativeActionSequence{public readonly float[,] actions;public readonly float[,] executedActions;public readonly int limbCount;public readonly Vector2 goal,goalHeading,worldGoal,worldGoalHeading;public readonly NativePosePrediction prediction;public readonly float biasStrength,explorationSigma,rhythmFrequency,rhythmPhase;public readonly int retryCount;public readonly float initialPredictedLoss,finalPredictedLoss;public NativeActionSequence(float[,] a,int count,Vector2 g,Vector2 gh,Vector2 wg,Vector2 wgh,NativePosePrediction p,float b,float s,float frequency=.5f,float phase=0f,int retries=0,float initialLoss=0f,float finalLoss=0f){actions=a;executedActions=(float[,])a.Clone();limbCount=count;goal=g;goalHeading=gh;worldGoal=wg;worldGoalHeading=wgh;prediction=p;biasStrength=b;explorationSigma=s;rhythmFrequency=frequency;rhythmPhase=phase;retryCount=retries;initialPredictedLoss=initialLoss;finalPredictedLoss=finalLoss;}public float[] ActionAt(int step){float[] r=new float[NativeCreatureModel.MaxLimbs];for(int i=0;i<limbCount;i++)r[i]=actions[step,i];return r;}public void RecordExecuted(int step,IReadOnlyList<Limb> limbs){for(int i=0;i<limbCount;i++)executedActions[step,i]=i<limbs.Count&&limbs[i]!=null?limbs[i].ExecutedIntervalDelta:actions[step,i];}}
[Serializable] public sealed class NativeCompletedSequence{public string sampleId,bodySignature,controllerId;public NativeObservation observation;public float[] actions,actualPoses,actualAuxiliary,executedActions;public float rhythmFrequency,rhythmPhase;public int retryCount,modelVersion;public float[,] ActionMatrix(){var result=new float[NativeCreatureModel.PlanningHorizon,NativeCreatureModel.MaxLimbs];if(actions==null)return result;for(int s=0;s<NativeCreatureModel.PlanningHorizon;s++)for(int l=0;l<NativeCreatureModel.MaxLimbs;l++){int i=s*NativeCreatureModel.MaxLimbs+l;if(i<actions.Length)result[s,l]=actions[i];}return result;}public NativeCompletedSequence Clone()=>new NativeCompletedSequence{sampleId=sampleId,bodySignature=bodySignature,controllerId=controllerId,observation=NativeReplayBuffer.CloneObservation(observation),actions=actions==null?null:(float[])actions.Clone(),actualPoses=actualPoses==null?null:(float[])actualPoses.Clone(),actualAuxiliary=actualAuxiliary==null?null:(float[])actualAuxiliary.Clone(),executedActions=executedActions==null?null:(float[])executedActions.Clone(),rhythmFrequency=rhythmFrequency,rhythmPhase=rhythmPhase,retryCount=retryCount,modelVersion=modelVersion};}
public struct NativeLocalProprioception{public Vector2 worldPosition,localLinearVelocity;public float worldRotationDegrees;public Vector2 WorldToTorsoVector(Vector2 worldVector)=>Quaternion.Euler(0f,0f,-worldRotationDegrees)*worldVector;}
[Serializable] public sealed class NativeCreatureSave{public NativeBrainWeights weights;public NativeOptimizerState m2Optimizer;public NativeSynapticIntelligence m2Protection;public float goalX,goalY,goalHeadingSin,goalHeadingCos,worldGoalX,worldGoalY,worldGoalHeadingSin,worldGoalHeadingCos,fixedGoalHeadingSin,fixedGoalHeadingCos,m1AnchorX,m1AnchorY,oscillatorPhase;public int goalTicksRemaining,fixedGoalBlock;public bool m1AnchorInitialized;public ulong explorationState;public List<float> leftLosses,rightLosses;public float leftBestProgress,rightBestProgress;public NativeCreatureSave Clone(){var copy=(NativeCreatureSave)MemberwiseClone();copy.weights=weights?.Clone();copy.m2Optimizer=m2Optimizer?.Clone();copy.m2Protection=m2Protection?.Clone();copy.leftLosses=leftLosses==null?new List<float>():new List<float>(leftLosses);copy.rightLosses=rightLosses==null?new List<float>():new List<float>(rightLosses);return copy;}}
[Serializable] public sealed class NativeCreatureCheckpoint{public string creatureId,speciesId,m1SpeciesId,bodyGenomeJson;public NativeCreatureSave brain;public RtNeatGoalGenome m1Genome;public NativeCurriculumState curriculum;public NativeM3LearningState m3;public float bodyFitness,deathPenalty,m1EnergyFitness,previousEnergy;public bool deathRecorded,protectedOffspring;public int bodyAgeGenerations,temporaryGoalRewardBlock;}
[Serializable] public sealed class NativeEcosystemCheckpoint{public int schema=26;public const string ConfigurationFingerprint="native-v26-unity-graph64-h4-ppo-cpg-a5-r25-m3ensemble3-school4";public string configuration=ConfigurationFingerprint,tensorGeneration,tensorFile,tensorSha256;public int tick,generation,controlStep,specialistSelectionCursor,sharedM3Samples,freshSequenceSamples,sharedM3OptimizerSteps,learnerQueueDrops,goalSuccesses,goalFailures;public string experimentId;public bool capabilityValidated;public long randomState,nextEvolutionTicks;public NativeRtNeatGoalPolicy rtNeat;public NativeSharedLearningState sharedLearning;public NativeMovementLearningState movementLearning;public List<NativeCreatureCheckpoint> creatures=new List<NativeCreatureCheckpoint>();public static bool IsCompatibleConfiguration(string value)=>value==ConfigurationFingerprint;}
[Serializable] public sealed class NativeM2BatchMetrics{public int sampleCount,optimizerSteps;public float loss,goalLoss,energyLoss;}
[Serializable] public sealed class NativeM3BatchMetrics{public int sampleCount,optimizerSteps;public float loss,poseMse,relativeLoss,velocityLoss,contactLoss;}
internal sealed class DenseCache{public float[] input,pre,output;public int biasOffset;public bool activate;}
internal sealed class JointCache{public float[] input,position,pre,output;}
internal sealed class RmsCache{public float[] input,output,gamma;public float inverse;public int gammaOffset;}
internal sealed class AttentionCache{public float[][] input,q,k,v,output;public RmsCache[] normalized;public float[,,] probability;public int heads;}
internal sealed class CrossAttentionCache{public float[][] queries,tokens,q,k,v,output;public RmsCache[] normalizedQueries,normalizedTokens;public float[,,] probability;public int heads;}
internal sealed class CrossBackward{public float[][] queryGradient,tokenGradient;}
internal sealed class MlpCache{public DenseCache fusion,residual;public DenseCache[] deepLayers;public RmsCache[] norms;public float[] merged,output;}
internal sealed class StepDecoderCache{public int step;public float[] input;public RmsCache norm;public DenseCache layer;public float output;}
internal sealed class HeadCache{public DenseCache fusion,residual,outputLayer;public DenseCache[] deepLayers;public float[] merged,output;public float outputScale;}
internal sealed class M2Cache{public NativeObservation observation;public DenseCache context;public JointCache[] limbs;public AttentionCache attention,attention2;public MlpCache[] heads;public StepDecoderCache[][] steps;public float[,] actions;}
internal sealed class M3Cache{public NativeObservation observation;public float[,] actions;public DenseCache context;public JointCache[] limbs;public AttentionCache attention;public CrossAttentionCache cross;public MlpCache[] heads;public DenseCache[] outputLayers;public float[][] rawOutputs;public float[] prediction,auxiliary;}
